package rules_test

import (
	"context"
	"strings"
	"testing"

	"github.com/faustbrian/gox/internal/analysis"
	"github.com/faustbrian/gox/internal/rules"
	"github.com/faustbrian/gox/internal/source"
)

func TestDuplicateConditionReportsEveryRepeatedSideEffectFreeConditionOnce(t *testing.T) {
	t.Parallel()

	input := `package sample
func classify(a, b bool) int {
	if a { return 1
	} else if b { return 2
	} else if a { return 3
	} else if a { return 4
	} else if b { return 5
	}
	return 0
}
`
	result := runDuplicateCondition(t, input)
	if len(result.Diagnostics) != 2 {
		t.Fatalf("diagnostics = %#v, want two repeated occurrences", result.Diagnostics)
	}
	firstA := strings.Index(input, "if a") + len("if ")
	firstB := strings.Index(input, "if b") + len("if ")
	repeatedA := strings.Index(input[firstA+1:], "if a") + firstA + 1 + len("if ")
	repeatedB := strings.LastIndex(input, "if b") + len("if ")
	for index, want := range []struct{ repeated, first int }{
		{repeated: repeatedA, first: firstA},
		{repeated: repeatedB, first: firstB},
	} {
		diagnostic := result.Diagnostics[index]
		if diagnostic.Range != (source.Range{Start: want.repeated, End: want.repeated + 1}) ||
			len(diagnostic.Related) != 1 ||
			diagnostic.Related[0].Range != (source.Range{Start: want.first, End: want.first + 1}) {
			t.Fatalf("diagnostic %d = %#v", index, diagnostic)
		}
	}
}

func TestDuplicateConditionConservativeAndDistinctChainsDoNotReport(t *testing.T) {
	t.Parallel()

	tests := map[string]string{
		"call": `package sample
func f() bool { return true }
func run() { if f() {} else if f() {} }
`,
		"receive": `package sample
func run(ch <-chan bool) { if <-ch {} else if <-ch {} }
`,
		"address": `package sample
func run(value *int) { if &value != nil {} else if &value != nil {} }
`,
		"initializer": `package sample
func run() { if value := true; value {} else if value {} }
`,
		"distinct": `package sample
func run(a, b bool) { if a {} else if b {} }
`,
		"separate chains": `package sample
func run(a bool) { if a {}; if a {} }
`,
	}
	for name, input := range tests {
		name, input := name, input
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			result := runDuplicateCondition(t, input)
			if len(result.Diagnostics) != 0 {
				t.Fatalf("diagnostics = %#v, want none", result.Diagnostics)
			}
		})
	}
}

func TestDuplicateConditionHandlesElseIfCommentsSuppressionsAndTypeErrors(t *testing.T) {
	t.Parallel()

	input := `package sample
func run() {
	if missing {
	} else // ownership comment
	//gox:ignore duplicate-condition -- intentional fallback
	if missing {
	}
}
`
	result := runDuplicateCondition(t, input)
	if len(result.Diagnostics) != 0 || len(result.Suppressed) != 1 ||
		result.Suppressed[0].Diagnostic.RuleID != "duplicate-condition" {
		t.Fatalf("result = %#v, want one suppressed type-invalid diagnostic", result)
	}
}

func TestDuplicateConditionExcludesGeneratedFiles(t *testing.T) {
	t.Parallel()

	result := runDuplicateCondition(t, `// Code generated by fixture. DO NOT EDIT.
package sample
func run(a bool) { if a {} else if a {} }
`)
	if len(result.Diagnostics) != 0 || len(result.Selection) != 2 {
		t.Fatalf("result = %#v, want selected rule with no generated-file diagnostic", result)
	}
}

func TestDefaultRegistryDocumentsDuplicateConditionWithoutAFix(t *testing.T) {
	t.Parallel()

	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	metadata, found := registry.Metadata("duplicate-condition")
	if !found || metadata.Requirement != rules.RequireSyntax ||
		metadata.DefaultSeverity != rules.SeverityWarn ||
		metadata.MinimumGoVersion != "1.26" ||
		metadata.RunOnGenerated || len(metadata.Fixes) != 0 ||
		len(metadata.Presets) != 1 || metadata.Presets[0] != rules.PresetCorrectness {
		t.Fatalf("metadata = %#v, found = %v", metadata, found)
	}
}

func TestDuplicateConditionHonorsSeverityOverrides(t *testing.T) {
	t.Parallel()

	input := "package sample\nfunc run(a bool) { if a {} else if a {} }\n"
	file, err := source.Load("sample.go", []byte(input))
	if err != nil {
		t.Fatal(err)
	}
	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	for _, test := range []struct {
		severity rules.Severity
		count    int
	}{
		{severity: rules.SeverityError, count: 1},
		{severity: rules.SeverityOff, count: 0},
	} {
		result, err := analysis.Run(context.Background(), file, registry, analysis.RunOptions{
			Preset: rules.PresetCorrectness,
			Overrides: map[string]rules.Severity{
				"duplicate-condition": test.severity,
			},
		})
		if err != nil {
			t.Fatal(err)
		}
		if len(result.Diagnostics) != test.count {
			t.Fatalf("severity %s diagnostics = %#v", test.severity, result.Diagnostics)
		}
		if test.count == 1 && result.Diagnostics[0].Severity != rules.SeverityError {
			t.Fatalf("diagnostic severity = %s, want error", result.Diagnostics[0].Severity)
		}
	}
}

func BenchmarkDuplicateCondition(b *testing.B) {
	input := "package sample\nfunc run(a, b, c bool) {\n"
	for range 100 {
		input += "if a && b {} else if b && c {} else if a && b {}\n"
	}
	input += "}\n"
	file, err := source.Load("sample.go", []byte(input))
	if err != nil {
		b.Fatal(err)
	}
	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		b.Fatal(err)
	}
	b.ReportAllocs()
	b.ResetTimer()
	for range b.N {
		result, err := analysis.Run(context.Background(), file, registry, analysis.RunOptions{
			Preset: rules.PresetCorrectness,
		})
		if err != nil {
			b.Fatal(err)
		}
		if len(result.Diagnostics) != 100 {
			b.Fatalf("diagnostics = %d, want 100", len(result.Diagnostics))
		}
	}
}

func runDuplicateCondition(t *testing.T, input string) analysis.Result {
	t.Helper()
	file, err := source.Load("sample.go", []byte(input))
	if err != nil {
		t.Fatal(err)
	}
	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.Run(context.Background(), file, registry, analysis.RunOptions{
		Preset: rules.PresetCorrectness,
	})
	if err != nil {
		t.Fatal(err)
	}
	return result
}
