package rules_test

import (
	"context"
	"fmt"
	"go/ast"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/faustbrian/gox/internal/analysis"
	"github.com/faustbrian/gox/internal/rules"
	"github.com/faustbrian/gox/internal/source"
)

type benchmarkErrorsIsArgumentsTypesRule struct{}

func (benchmarkErrorsIsArgumentsTypesRule) Metadata() rules.Metadata {
	return rules.Metadata{
		ID: "benchmark-errors-is-arguments-types",
		Summary: "provides a types traversal baseline",
		Documentation: "Provides a no-op typed call traversal for benchmark comparison.",
		DefaultSeverity: rules.SeverityWarn,
		Presets: []rules.Preset{rules.PresetSuspicious},
		MinimumGoVersion: "1.26",
		Requirement: rules.RequireTypes,
		NodeInterests: []rules.NodeKind{rules.NodeCallExpr},
		Categories: []rules.Category{rules.CategoryCorrectness},
		Examples: []rules.Example{{Incorrect: "bad()", Correct: "good()"}},
	}
}

func (benchmarkErrorsIsArgumentsTypesRule) RunTypes(
	*rules.TypesContext,
	ast.Node,
) ([]rules.Finding, error) {
	return nil, nil
}

func TestErrorsIsArgumentsReportsExternalSentinelsInTheFirstPosition(t *testing.T) {
	t.Parallel()

	input := `package sample
import (
	errs "errors"
	"io"
)
var localSentinel = errs.New("local")
func run(err error) {
	errs.Is(io.EOF, err)
	(errs.Is)((io.ErrClosedPipe), localSentinel)
}
`
	result := runErrorsIsArguments(t, input, nil)
	want := []string{"io.EOF", "(io.ErrClosedPipe)"}
	if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != len(want) {
		t.Fatalf("result = %#v, want %d errors-is-arguments diagnostics", result, len(want))
	}
	searchStart := 0
	for index, expression := range want {
		offset := strings.Index(input[searchStart:], expression)
		if offset < 0 {
			t.Fatalf("input does not contain %q after %d", expression, searchStart)
		}
		offset += searchStart
		diagnostic := result.Files[0].Diagnostics[index]
		if diagnostic.RuleID != "errors-is-arguments" ||
			diagnostic.MessageKey != "reversed-arguments" ||
			diagnostic.Message != "errors.Is arguments appear to be reversed" ||
			diagnostic.Help !=
				"pass the error value first and the package sentinel second" ||
			diagnostic.Range !=
				(source.Range{Start: offset, End: offset + len(expression)}) ||
			len(diagnostic.Fixes) != 0 {
			t.Fatalf("diagnostic %d = %#v", index, diagnostic)
		}
		searchStart = offset + len(expression)
	}
}

func TestErrorsIsArgumentsAcceptsCorrectAndAmbiguousCalls(t *testing.T) {
	t.Parallel()

	input := `package sample
import (
	errs "errors"
	"io"
	"io/fs"
)
var localSentinel = errs.New("local")
var localAlias = io.EOF
type checker struct{}
func (checker) Is(error, error) bool { return false }
type holder struct{ err error }
func fakeIs(error, error) bool { return false }
func run(err error) {
	errs.Is(err, io.EOF)
	errs.Is(io.EOF, fs.ErrNotExist)
	errs.Is(localSentinel, err)
	errs.Is(localAlias, err)
	errs.Is(holder{err: io.EOF}.err, err)
	errs.Is(func() error { return io.EOF }(), err)
	errs.Is([]error{io.EOF}[0], err)
	checker{}.Is(io.EOF, err)
	fakeIs(io.EOF, err)
}
`
	result := runErrorsIsArguments(t, input, nil)
	if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != 0 {
		t.Fatalf("result = %#v, want no diagnostics", result)
	}
}

func TestErrorsIsArgumentsSupportsDotImportsAndPackagePolicies(t *testing.T) {
	t.Parallel()

	suppressed := runErrorsIsArguments(
		t,
		`package sample
import (
	. "errors"
	"io"
)
func run(err error) {
	//gox:ignore errors-is-arguments -- compatibility boundary
	Is(io.EOF, err)
}
`,
		nil,
	)
	if len(suppressed.Files) != 1 ||
		len(suppressed.Files[0].Diagnostics) != 0 ||
		len(suppressed.Files[0].Suppressed) != 1 ||
		suppressed.Files[0].Suppressed[0].Diagnostic.RuleID != "errors-is-arguments" {
		t.Fatalf("suppressed result = %#v", suppressed)
	}

	generated := runErrorsIsArguments(
		t,
		`// Code generated by fixture. DO NOT EDIT.
package sample
import ("errors"; "io")
func run(err error) { errors.Is(io.EOF, err) }
`,
		nil,
	)
	if len(generated.Files) != 1 || len(generated.Files[0].Diagnostics) != 0 {
		t.Fatalf("generated result = %#v", generated)
	}

	illTyped := runErrorsIsArguments(
		t,
		`package sample
import ("errors"; "io")
func run(err error) { missing(); errors.Is(io.EOF, err) }
`,
		nil,
	)
	if len(illTyped.LoadDiagnostics) == 0 ||
		len(illTyped.Files) != 1 ||
		len(illTyped.Files[0].Diagnostics) != 0 {
		t.Fatalf("ill-typed result = %#v", illTyped)
	}

	severity := runErrorsIsArguments(
		t,
		`package sample
import ("errors"; "io")
func run(err error) { errors.Is(io.EOF, err) }
`,
		map[string]rules.Severity{"errors-is-arguments": rules.SeverityError},
	)
	if len(severity.Files) != 1 ||
		len(severity.Files[0].Diagnostics) != 1 ||
		severity.Files[0].Diagnostics[0].Severity != rules.SeverityError {
		t.Fatalf("severity result = %#v", severity)
	}
}

func TestDefaultRegistryDocumentsErrorsIsArgumentsWithoutAFix(t *testing.T) {
	t.Parallel()

	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	metadata, found := registry.Metadata("errors-is-arguments")
	if !found ||
		metadata.Requirement != rules.RequireTypes ||
		metadata.DefaultSeverity != rules.SeverityWarn ||
		metadata.MinimumGoVersion != "1.25" ||
		metadata.RunOnGenerated ||
		metadata.RunDespiteTypeErrors ||
		len(metadata.Fixes) != 0 ||
		len(metadata.Presets) != 1 ||
		metadata.Presets[0] != rules.PresetSuspicious ||
		len(metadata.Examples) == 0 ||
		len(metadata.KnownLimitations) == 0 {
		t.Fatalf("metadata = %#v, found = %v", metadata, found)
	}
}

func BenchmarkErrorsIsArgumentsSharedTypes(b *testing.B) {
	root := b.TempDir()
	if err := os.WriteFile(
		filepath.Join(root, "go.mod"),
		[]byte("module example.com/errorsisargumentsbenchmark\n\ngo 1.26.0\n"),
		0o600,
	);
		err != nil {
		b.Fatal(err)
	}
	var input strings.Builder
	input.WriteString(
		"package sample\nimport (\"errors\"; \"io\")\nfunc inspect(err error) {\n",
	)
	for range 100 {
		fmt.Fprintln(&input, "errors.Is(io.EOF, err)")
	}
	input.WriteString("}\n")
	if err := os.WriteFile(filepath.Join(root, "sample.go"), []byte(input.String()), 0o600);
		err != nil {
		b.Fatal(err)
	}
	loaded, err := analysis.LoadPackages(
		context.Background(),
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			Requirement: rules.RequireTypes,
		},
	)
	if err != nil {
		b.Fatal(err)
	}
	productionRegistry, err := rules.NewDefaultRegistry()
	if err != nil {
		b.Fatal(err)
	}
	productionSelection, err := productionRegistry.Resolve(
		rules.PresetSuspicious,
		map[string]rules.Severity{
			"context-key": rules.SeverityOff,
			"defer-in-infinite-loop": rules.SeverityOff,
			"nilness": rules.SeverityOff,
		},
	)
	if err != nil {
		b.Fatal(err)
	}
	baselineRegistry, err := rules.NewRegistry(benchmarkErrorsIsArgumentsTypesRule{})
	if err != nil {
		b.Fatal(err)
	}
	baselineSelection, err := baselineRegistry.Resolve(rules.PresetSuspicious, nil)
	if err != nil {
		b.Fatal(err)
	}

	b.Run(
		"baseline",
		func(b *testing.B) {
			benchmarkErrorsIsArgumentsExecution(
				b,
				loaded,
				baselineRegistry,
				baselineSelection,
				0,
			)
		},
	)
	b.Run(
		"errors-is-arguments",
		func(b *testing.B) {
			benchmarkErrorsIsArgumentsExecution(
				b,
				loaded,
				productionRegistry,
				productionSelection,
				100,
			)
		},
	)
}

func benchmarkErrorsIsArgumentsExecution(
	b *testing.B,
	loaded analysis.PackageLoadResult,
	registry *rules.Registry,
	selection []rules.Selection,
	wantDiagnostics int,
) {
	b.Helper()
	b.ReportAllocs()
	for range b.N {
		diagnostics, err := analysis.RunTypes(
			context.Background(),
			loaded,
			registry,
			selection,
		)
		if err != nil {
			b.Fatal(err)
		}
		if len(diagnostics) != wantDiagnostics {
			b.Fatalf("diagnostics = %d, want %d", len(diagnostics), wantDiagnostics)
		}
	}
}

func runErrorsIsArguments(
	t *testing.T,
	input string,
	overrides map[string]rules.Severity,
) analysis.PackageResult {
	t.Helper()
	root := t.TempDir()
	if err := os.WriteFile(
		filepath.Join(root, "go.mod"),
		[]byte("module example.com/errorsisarguments\n\ngo 1.26.0\n"),
		0o600,
	);
		err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "sample.go"), []byte(input), 0o600); err != nil {
		t.Fatal(err)
	}
	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	if overrides == nil {
		overrides = make(map[string]rules.Severity)
	}
	overrides["context-key"] = rules.SeverityOff
	overrides["defer-in-infinite-loop"] = rules.SeverityOff
	overrides["nilness"] = rules.SeverityOff
	if _, configured := overrides["errors-is-arguments"]; !configured {
		overrides["errors-is-arguments"] = rules.SeverityWarn
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{Preset: rules.PresetSuspicious, Overrides: overrides},
		analysis.PackageLoadOptions{Dir: root, Patterns: []string{"."}},
	)
	if err != nil {
		t.Fatal(err)
	}
	return result
}
