package rules_test

import (
	"context"
	"strings"
	"testing"

	"github.com/faustbrian/glippy/internal/analysis"
	"github.com/faustbrian/glippy/internal/rules"
	"github.com/faustbrian/glippy/internal/source"
)

func TestIdenticalBranchesReportsEquivalentIfElseBodies(t *testing.T) {
	t.Parallel()

	input := `package sample
func run(ready bool) {
	if ready {
		work()
	} else {
		work()
	}
}
func work() {}
`
	result := runIdenticalBranches(t, input)
	if len(result.Diagnostics) != 1 {
		t.Fatalf("diagnostics = %#v, want one", result.Diagnostics)
	}
	diagnostic := result.Diagnostics[0]
	first := strings.Index(input, "{\n\t\twork()")
	second := strings.LastIndex(input, "{\n\t\twork()")
	if diagnostic.RuleID != "identical-branches" ||
		diagnostic.MessageKey != "identical-else-branch" ||
		diagnostic.Range.Start != second ||
		len(diagnostic.Related) != 1 ||
		diagnostic.Related[0].Range.Start != first ||
		len(diagnostic.Fixes) != 0 {
		t.Fatalf("diagnostic = %#v", diagnostic)
	}
}

func TestIdenticalBranchesIgnoresDistinctCommentedAndMissingElseBodies(t *testing.T) {
	t.Parallel()

	tests := map[string]string{
		"distinct": `package sample
func run(ready bool) { if ready { first() } else { second() } }
func first() {}; func second() {}
`,
		"commented distinction": `package sample
func run(ready bool) {
	if ready { // fast path
		work()
	} else { // fallback path
		work()
	}
}
func work() {}
`,
		"no else": `package sample
func run(ready bool) { if ready { work() } }
func work() {}
`,
		"else if": `package sample
func run(first, second bool) {
	if first { work() } else if second { work() }
}
func work() {}
`,
	}
	for name, input := range tests {
		name, input := name, input
		t.Run(
			name,
			func(t *testing.T) {
				t.Parallel()
				result := runIdenticalBranches(t, input)
				if len(result.Diagnostics) != 0 {
					t.Fatalf("diagnostics = %#v, want none", result.Diagnostics)
				}
			},
		)
	}
}

func TestIdenticalBranchesHonorsSuppressionsAndGeneratedFiles(t *testing.T) {
	t.Parallel()

	suppressed := runIdenticalBranches(
		t,
		`package sample
func run(ready bool) {
	//glippy:ignore identical-branches -- compatibility branches remain explicit
	if ready { work() } else { work() }
}
func work() {}
`,
	)
	if len(suppressed.Diagnostics) != 0 || len(suppressed.Suppressed) != 1 {
		t.Fatalf("suppressed result = %#v", suppressed)
	}

	generated := runIdenticalBranches(
		t,
		`// Code generated by fixture. DO NOT EDIT.
package sample
func run(ready bool) { if ready { work() } else { work() } }
func work() {}
`,
	)
	if len(generated.Diagnostics) != 0 {
		t.Fatalf("generated diagnostics = %#v, want none", generated.Diagnostics)
	}
}

func TestDefaultRegistryDocumentsIdenticalBranches(t *testing.T) {
	t.Parallel()

	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	metadata, found := registry.Metadata("identical-branches")
	if !found ||
		metadata.Requirement != rules.RequireSyntax ||
		metadata.DefaultSeverity != rules.SeverityWarn ||
		metadata.RunOnGenerated ||
		len(metadata.Fixes) != 0 ||
		len(metadata.Presets) != 1 ||
		metadata.Presets[0] != rules.PresetSuspicious {
		t.Fatalf("metadata = %#v, found = %v", metadata, found)
	}
}

func BenchmarkIdenticalBranches(b *testing.B) {
	input := "package sample\nfunc run(ready bool) {\n"
	for range 100 {
		input += "if ready { work() } else { work() }\n"
	}
	input += "}\nfunc work() {}\n"
	file, err := source.Load("sample.go", []byte(input))
	if err != nil {
		b.Fatal(err)
	}
	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		b.Fatal(err)
	}
	b.ReportAllocs()
	b.ResetTimer()
	for range b.N {
		result, err := analysis.Run(
			context.Background(),
			file,
			registry,
			analysis.RunOptions{
				Presets: []rules.Preset{},
				Overrides: map[string]rules.Severity{
					"identical-branches": rules.SeverityWarn,
				},
			},
		)
		if err != nil {
			b.Fatal(err)
		}
		if len(result.Diagnostics) != 100 {
			b.Fatalf("diagnostics = %d, want 100", len(result.Diagnostics))
		}
	}
}

func runIdenticalBranches(t *testing.T, input string) analysis.Result {
	t.Helper()
	file, err := source.Load("sample.go", []byte(input))
	if err != nil {
		t.Fatal(err)
	}
	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.Run(
		context.Background(),
		file,
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{
				"identical-branches": rules.SeverityWarn,
			},
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	return result
}
