package rules_test

import (
	"context"
	"strings"
	"testing"

	"github.com/faustbrian/glippy/internal/analysis"
	"github.com/faustbrian/glippy/internal/rules"
	"github.com/faustbrian/glippy/internal/source"
)

func TestIneffectiveBreakReportsFinalUnlabeledBreaksInsideLoopSwitchesAndSelects(t *testing.T) {
	t.Parallel()

	input := `package sample
func run(ch <-chan int, values []int) {
	for {
		switch {
		case true:
			break
		default:
			if ready {
				break
			} else {
				break
			}
		}
	}
	for range values {
		select {
		case <-ch:
			break
		default:
		}
	}
}
`
	result := runIneffectiveBreak(t, input)
	if len(result.Diagnostics) != 4 {
		t.Fatalf("diagnostics = %#v, want four ineffective breaks", result.Diagnostics)
	}
	offset := 0
	for index, diagnostic := range result.Diagnostics {
		position := strings.Index(input[offset:], "break") + offset
		if position < offset ||
			diagnostic.RuleID != "ineffective-break" ||
			diagnostic.Range !=
				(source.Range{Start: position, End: position + len("break")}) ||
			diagnostic.MessageKey != "ineffective-break" ||
			len(diagnostic.Fixes) != 1 ||
			diagnostic.Fixes[0].Name != "remove-break" ||
			diagnostic.Fixes[0].Safety != rules.FixSuggestion ||
			len(diagnostic.Fixes[0].Edits) != 1 ||
			diagnostic.Fixes[0].Edits[0] !=
				(rules.Edit{
					Range: source.Range{
						Start: position,
						End: position + len("break"),
					},
				}) {
			t.Fatalf(
				"diagnostic %d = %#v, want break at %d",
				index,
				diagnostic,
				position,
			)
		}
		offset = position + len("break")
	}
}

func TestIneffectiveBreakPreservesEffectiveAndOutOfScopeBreaks(t *testing.T) {
	t.Parallel()

	input := `package sample
func run(ready bool) {
outer:
	for {
		switch {
		case ready:
			break outer
		case !ready:
			break
			use()
		default:
			{
				break
			}
		}
		for {
			switch {
			default:
				break
			}
		}
	}
	switch {
	default:
		break
	}
}
`
	result := runIneffectiveBreak(t, input)
	if len(result.Diagnostics) != 1 {
		t.Fatalf("diagnostics = %#v, want only the inner-loop break", result.Diagnostics)
	}
	want := strings.LastIndex(input[:strings.LastIndex(input, "\tswitch")], "break")
	if result.Diagnostics[0].Range != (source.Range{Start: want, End: want + len("break")}) {
		t.Fatalf(
			"diagnostic = %#v, want inner-loop break at %d",
			result.Diagnostics[0],
			want,
		)
	}
}

func TestIneffectiveBreakHonorsSuppressionsAndGeneratedFiles(t *testing.T) {
	t.Parallel()

	input := `package sample
func run() {
	for {
		switch {
		default:
			//glippy:ignore ineffective-break -- intentional switch-only exit
			break
		}
	}
}
`
	result := runIneffectiveBreak(t, input)
	if len(result.Diagnostics) != 0 ||
		len(result.Suppressed) != 1 ||
		result.Suppressed[0].Diagnostic.RuleID != "ineffective-break" {
		t.Fatalf("suppressed result = %#v", result)
	}

	generated := runIneffectiveBreak(
		t,
		`// Code generated by fixture. DO NOT EDIT.
package sample
func run() { for { switch { default: break } } }
`,
	)
	if len(generated.Diagnostics) != 0 || len(generated.Selection) != 2 {
		t.Fatalf("generated result = %#v", generated)
	}
}

func TestDefaultRegistryDocumentsIneffectiveBreakSuggestionFix(t *testing.T) {
	t.Parallel()

	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	metadata, found := registry.Metadata("ineffective-break")
	if !found ||
		metadata.Requirement != rules.RequireSyntax ||
		metadata.DefaultSeverity != rules.SeverityWarn ||
		metadata.MinimumGoVersion != "1.25" ||
		metadata.RunOnGenerated ||
		len(metadata.Fixes) != 1 ||
		metadata.Fixes[0] !=
			(rules.FixMetadata{
				Name: "remove-break",
				Description: "remove the ineffective break",
				Safety: rules.FixSuggestion,
			}) ||
		len(metadata.Presets) != 1 ||
		metadata.Presets[0] != rules.PresetCorrectness {
		t.Fatalf("metadata = %#v, found = %v", metadata, found)
	}
}

func TestIneffectiveBreakHonorsSeverityOverrides(t *testing.T) {
	t.Parallel()

	input := "package sample\nfunc run() { for { switch { default: break } } }\n"
	file, err := source.Load("sample.go", []byte(input))
	if err != nil {
		t.Fatal(err)
	}
	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	for _, test := range
		[]struct {
			severity rules.Severity
			count int
		}{
			{severity: rules.SeverityError, count: 1},
			{severity: rules.SeverityOff, count: 0},
		} {
		result, err := analysis.Run(
			context.Background(),
			file,
			registry,
			analysis.RunOptions{
				Preset: rules.PresetCorrectness,
				Overrides: map[string]rules.Severity{
					"ineffective-break": test.severity,
				},
			},
		)
		if err != nil {
			t.Fatal(err)
		}
		if len(result.Diagnostics) != test.count {
			t.Fatalf("severity %s diagnostics = %#v", test.severity, result.Diagnostics)
		}
		if test.count == 1 && result.Diagnostics[0].Severity != rules.SeverityError {
			t.Fatalf(
				"diagnostic severity = %s, want error",
				result.Diagnostics[0].Severity,
			)
		}
	}
}

func BenchmarkIneffectiveBreak(b *testing.B) {
	var input strings.Builder
	input.WriteString("package sample\nfunc run() {\n")
	for range 100 {
		input.WriteString("for { select { default: break } }\n")
	}
	input.WriteString("}\n")
	file, err := source.Load("sample.go", []byte(input.String()))
	if err != nil {
		b.Fatal(err)
	}
	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		b.Fatal(err)
	}
	b.ReportAllocs()
	b.ResetTimer()
	for range b.N {
		result, err := analysis.Run(
			context.Background(),
			file,
			registry,
			analysis.RunOptions{Preset: rules.PresetCorrectness},
		)
		if err != nil {
			b.Fatal(err)
		}
		if len(result.Diagnostics) != 100 {
			b.Fatalf("diagnostics = %d, want 100", len(result.Diagnostics))
		}
	}
}

func runIneffectiveBreak(t *testing.T, input string) analysis.Result {
	t.Helper()
	file, err := source.Load("sample.go", []byte(input))
	if err != nil {
		t.Fatal(err)
	}
	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.Run(
		context.Background(),
		file,
		registry,
		analysis.RunOptions{Preset: rules.PresetCorrectness},
	)
	if err != nil {
		t.Fatal(err)
	}
	return result
}
