package rules_test

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/faustbrian/gox/internal/analysis"
	"github.com/faustbrian/gox/internal/rules"
)

type benchmarkSSARule struct{}

func (benchmarkSSARule) Metadata() rules.Metadata {
	return rules.Metadata{
		ID: "benchmark-ssa",
		Summary: "measures shared SSA construction",
		Documentation: "Provides a no-op SSA callback for benchmark comparison.",
		DefaultSeverity: rules.SeverityWarn,
		Presets: []rules.Preset{rules.PresetSuspicious},
		MinimumGoVersion: "1.26",
		Requirement: rules.RequireSSA,
		Categories: []rules.Category{rules.CategoryCorrectness},
		Examples: []rules.Example{{Incorrect: "bad()", Correct: "good()"}},
	}
}

func (benchmarkSSARule) RunSSA(*rules.SSAContext) ([]rules.Finding, error) {
	return nil, nil
}

func TestNilnessReportsOnlyProvenSSAFindings(t *testing.T) {
	t.Parallel()

	root, path := writeNilnessModule(
		t,
		`package sample

func inspect(pointer *int, values []int) {
	if pointer == nil {
		_ = *pointer
	}
	if pointer != nil {
		_ = *pointer
	}
	if values == nil {
		_ = (*[1]int)(values)
	}
}

func impossible() {
	channel := make(chan int)
	if channel == nil { println(channel) }
}

func nilPanic() { panic(nil) }

func unknown(pointer *int) { _ = *pointer }
`,
	)
	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}

	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{Preset: rules.PresetSuspicious},
		analysis.PackageLoadOptions{Dir: root, Patterns: []string{"."}},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 1 || result.Files[0].Path != path {
		t.Fatalf("RunPackages() files = %#v", result.Files)
	}

	got := make([]string, len(result.Files[0].Diagnostics))
	file, found := result.Sources.Lookup(path)
	if !found {
		t.Fatalf("RunPackages() did not retain %q", path)
	}
	for index, diagnostic := range result.Files[0].Diagnostics {
		text, valid := file.Slice(diagnostic.Range)
		if !valid || text == "" {
			t.Fatalf(
				"diagnostic %d range = %#v, text = %q, valid = %v",
				index,
				diagnostic.Range,
				text,
				valid,
			)
		}
		if diagnostic.RuleID != "nilness" ||
			diagnostic.Severity != rules.SeverityWarn ||
			len(diagnostic.Fixes) != 0 {
			t.Fatalf("diagnostic %d = %#v", index, diagnostic)
		}
		got[index] = diagnostic.MessageKey + ":" + text
	}
	want := []string{"nilderef:*", "conversionpanic:(", "cond:==", "nilpanic:("}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("nilness diagnostics = %#v, want %#v", got, want)
	}
}

func TestNilnessHonorsSuppressionGeneratedAndTypeErrorPolicies(t *testing.T) {
	t.Parallel()

	root, path := writeNilnessModule(
		t,
		`// Code generated by fixture. DO NOT EDIT.
package sample

func generated(pointer *int) {
	if pointer == nil {
		_ = *pointer
	}
}
`,
	)
	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{Preset: rules.PresetSuspicious},
		analysis.PackageLoadOptions{Dir: root, Patterns: []string{"."}},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 1 ||
		result.Files[0].Path != path ||
		len(result.Files[0].Diagnostics) != 0 ||
		len(result.Files[0].Suppressed) != 0 ||
		len(result.Files[0].UnusedSuppressions) != 0 ||
		len(result.Files[0].SuppressionProblems) != 0 {
		t.Fatalf("generated result = %#v", result)
	}

	brokenRoot, _ := writeNilnessModule(
		t,
		`package sample
func broken(pointer *missing) { _ = *pointer }
`,
	)
	broken, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{Preset: rules.PresetSuspicious},
		analysis.PackageLoadOptions{Dir: brokenRoot, Patterns: []string{"."}},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(broken.LoadDiagnostics) == 0 ||
		len(broken.Files) != 1 ||
		len(broken.Files[0].Diagnostics) != 0 {
		t.Fatalf("type-error result = %#v", broken)
	}
}

func TestNilnessSuppressionsAndSeverityUseCanonicalRuleIdentity(t *testing.T) {
	t.Parallel()

	root, _ := writeNilnessModule(
		t,
		`package sample
func inspect(pointer *int) {
	if pointer == nil {
		//gox:ignore nilness -- guarded for a proving fixture
		_ = *pointer
	}
}
`,
	)
	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Preset: rules.PresetSuspicious,
			Overrides: map[string]rules.Severity{"nilness": rules.SeverityError},
		},
		analysis.PackageLoadOptions{Dir: root, Patterns: []string{"."}},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 1 ||
		len(result.Files[0].Diagnostics) != 0 ||
		len(result.Files[0].Suppressed) != 1 ||
		result.Files[0].Suppressed[0].Diagnostic.RuleID != "nilness" ||
		result.Files[0].Suppressed[0].Diagnostic.Severity != rules.SeverityError ||
		len(result.Files[0].UnusedSuppressions) != 0 ||
		len(result.Files[0].SuppressionProblems) != 0 {
		t.Fatalf("suppressed result = %#v", result.Files)
	}
}

func TestNilnessDoesNotGuessInterproceduralNoReturn(t *testing.T) {
	t.Parallel()

	root, _ := writeNilnessModule(
		t,
		`package sample
func stop() { panic("stop") }
func inspect(pointer *int) {
	if pointer != nil { stop() }
	if pointer != nil { println(pointer) }
}
`,
	)
	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{Preset: rules.PresetSuspicious},
		analysis.PackageLoadOptions{Dir: root, Patterns: []string{"."}},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != 0 {
		t.Fatalf("interprocedural no-return result = %#v", result.Files)
	}
}

func TestDefaultRegistryDocumentsNilnessWithoutAFix(t *testing.T) {
	t.Parallel()

	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	metadata, found := registry.Metadata("nilness")
	if !found ||
		metadata.Requirement != rules.RequireSSA ||
		metadata.DefaultSeverity != rules.SeverityWarn ||
		metadata.MinimumGoVersion != "1.25" ||
		metadata.RunOnGenerated ||
		metadata.RunDespiteTypeErrors ||
		len(metadata.Fixes) != 0 ||
		len(metadata.Presets) != 1 ||
		metadata.Presets[0] != rules.PresetSuspicious ||
		len(metadata.Examples) == 0 ||
		len(metadata.KnownLimitations) == 0 {
		t.Fatalf("metadata = %#v, found = %v", metadata, found)
	}
}

func TestTypesControlFlowAndSSARulesRemainOptIn(t *testing.T) {
	t.Parallel()

	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	correctness, err := registry.Resolve(rules.PresetCorrectness, nil)
	if err != nil {
		t.Fatal(err)
	}
	if len(correctness) != 2 ||
		correctness[0].ID != "duplicate-condition" ||
		correctness[1].ID != "ineffective-break" {
		t.Fatalf("correctness selection = %#v", correctness)
	}
	suspicious, err := registry.Resolve(rules.PresetSuspicious, nil)
	if err != nil {
		t.Fatal(err)
	}
	if len(suspicious) != 4 ||
		suspicious[0].ID != "context-key" ||
		suspicious[0].Requirement != rules.RequireTypes ||
		suspicious[1].ID != "defer-in-infinite-loop" ||
		suspicious[1].Requirement != rules.RequireControlFlow ||
		suspicious[2].ID != "errors-is-arguments" ||
		suspicious[2].Requirement != rules.RequireTypes ||
		suspicious[3].ID != "nilness" ||
		suspicious[3].Requirement != rules.RequireSSA {
		t.Fatalf("suspicious selection = %#v", suspicious)
	}
}

func BenchmarkNilnessSharedSSA(b *testing.B) {
	root := b.TempDir()
	if err := os.WriteFile(
		filepath.Join(root, "go.mod"),
		[]byte("module example.com/nilness\n\ngo 1.26.0\n"),
		0o600,
	);
		err != nil {
		b.Fatal(err)
	}
	var input strings.Builder
	input.WriteString("package sample\n")
	for index := range 100 {
		fmt.Fprintf(
			&input,
			"func inspect%d(pointer *int) { if pointer == nil { _ = *pointer } }\n",
			index,
		)
	}
	if err := os.WriteFile(filepath.Join(root, "sample.go"), []byte(input.String()), 0o600);
		err != nil {
		b.Fatal(err)
	}
	loaded, err := analysis.LoadPackages(
		context.Background(),
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			Requirement: rules.RequireSSA,
		},
	)
	if err != nil {
		b.Fatal(err)
	}
	nilnessRegistry, err := rules.NewDefaultRegistry()
	if err != nil {
		b.Fatal(err)
	}
	nilnessSelection, err := nilnessRegistry.Resolve(
		rules.PresetSuspicious,
		map[string]rules.Severity{
			"context-key": rules.SeverityOff,
			"defer-in-infinite-loop": rules.SeverityOff,
			"errors-is-arguments": rules.SeverityOff,
		},
	)
	if err != nil {
		b.Fatal(err)
	}
	baselineRegistry, err := rules.NewRegistry(benchmarkSSARule{})
	if err != nil {
		b.Fatal(err)
	}
	baselineSelection, err := baselineRegistry.Resolve(rules.PresetSuspicious, nil)
	if err != nil {
		b.Fatal(err)
	}

	b.Run(
		"baseline",
		func(b *testing.B) {
			benchmarkSSAExecution(b, loaded, baselineRegistry, baselineSelection, 0)
		},
	)
	b.Run(
		"nilness",
		func(b *testing.B) {
			benchmarkSSAExecution(b, loaded, nilnessRegistry, nilnessSelection, 100)
		},
	)
}

func benchmarkSSAExecution(
	b *testing.B,
	loaded analysis.PackageLoadResult,
	registry *rules.Registry,
	selection []rules.Selection,
	wantDiagnostics int,
) {
	b.Helper()
	b.ReportAllocs()
	for range b.N {
		diagnostics, err := analysis.RunSSA(
			context.Background(),
			loaded,
			registry,
			selection,
		)
		if err != nil {
			b.Fatal(err)
		}
		if len(diagnostics) != wantDiagnostics {
			b.Fatalf("diagnostics = %d, want %d", len(diagnostics), wantDiagnostics)
		}
	}
}

func writeNilnessModule(t *testing.T, source string) (string, string) {
	t.Helper()
	root := t.TempDir()
	if err := os.WriteFile(
		filepath.Join(root, "go.mod"),
		[]byte("module example.com/nilness\n\ngo 1.26.0\n"),
		0o600,
	);
		err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(root, "sample.go")
	if err := os.WriteFile(path, []byte(source), 0o600); err != nil {
		t.Fatal(err)
	}
	return root, path
}
