package rules_test

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/faustbrian/glippy/internal/analysis"
	"github.com/faustbrian/glippy/internal/rules"
)

type benchmarkSSARule struct{}

func (benchmarkSSARule) Metadata() rules.Metadata {
	return rules.Metadata{
		ID: "benchmark-ssa",
		Summary: "measures shared SSA construction",
		Documentation: "Provides a no-op SSA callback for benchmark comparison.",
		DefaultSeverity: rules.SeverityWarn,
		Presets: []rules.Preset{rules.PresetSuspicious},
		MinimumGoVersion: "1.26",
		Requirement: rules.RequireSSA,
		Categories: []rules.Category{rules.CategoryCorrectness},
		Examples: []rules.Example{{Incorrect: "bad()", Correct: "good()"}},
	}
}

func (benchmarkSSARule) RunSSA(*rules.SSAContext) ([]rules.Finding, error) {
	return nil, nil
}

func TestNilnessReportsOnlyProvenSSAFindings(t *testing.T) {
	t.Parallel()

	root, path := writeNilnessModule(
		t,
		`package sample

func inspect(pointer *int, values []int) {
	if pointer == nil {
		_ = *pointer
	}
	if pointer != nil {
		_ = *pointer
	}
	if values == nil {
		_ = (*[1]int)(values)
	}
}

func impossible() {
	channel := make(chan int)
	if channel == nil { println(channel) }
}

func nilPanic() { panic(nil) }

func unknown(pointer *int) { _ = *pointer }
`,
	)
	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}

	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{Preset: rules.PresetSuspicious},
		analysis.PackageLoadOptions{Dir: root, Patterns: []string{"."}},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 1 || result.Files[0].Path != path {
		t.Fatalf("RunPackages() files = %#v", result.Files)
	}

	got := make([]string, len(result.Files[0].Diagnostics))
	file, found := result.Sources.Lookup(path)
	if !found {
		t.Fatalf("RunPackages() did not retain %q", path)
	}
	for index, diagnostic := range result.Files[0].Diagnostics {
		text, valid := file.Slice(diagnostic.Range)
		if !valid || text == "" {
			t.Fatalf(
				"diagnostic %d range = %#v, text = %q, valid = %v",
				index,
				diagnostic.Range,
				text,
				valid,
			)
		}
		if diagnostic.RuleID != "nilness" ||
			diagnostic.Severity != rules.SeverityWarn ||
			len(diagnostic.Fixes) != 0 {
			t.Fatalf("diagnostic %d = %#v", index, diagnostic)
		}
		got[index] = diagnostic.MessageKey + ":" + text
	}
	want := []string{"nilderef:*", "conversionpanic:(", "cond:==", "nilpanic:("}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("nilness diagnostics = %#v, want %#v", got, want)
	}
}

func TestNilnessHonorsSuppressionGeneratedAndTypeErrorPolicies(t *testing.T) {
	t.Parallel()

	root, path := writeNilnessModule(
		t,
		`// Code generated by fixture. DO NOT EDIT.
package sample

func generated(pointer *int) {
	if pointer == nil {
		_ = *pointer
	}
}
`,
	)
	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{Preset: rules.PresetSuspicious},
		analysis.PackageLoadOptions{Dir: root, Patterns: []string{"."}},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 1 ||
		result.Files[0].Path != path ||
		len(result.Files[0].Diagnostics) != 0 ||
		len(result.Files[0].Suppressed) != 0 ||
		len(result.Files[0].UnusedSuppressions) != 0 ||
		len(result.Files[0].SuppressionProblems) != 0 {
		t.Fatalf("generated result = %#v", result)
	}

	brokenRoot, _ := writeNilnessModule(
		t,
		`package sample
func broken(pointer *missing) { _ = *pointer }
`,
	)
	broken, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{Preset: rules.PresetSuspicious},
		analysis.PackageLoadOptions{Dir: brokenRoot, Patterns: []string{"."}},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(broken.LoadDiagnostics) == 0 ||
		len(broken.Files) != 1 ||
		len(broken.Files[0].Diagnostics) != 0 {
		t.Fatalf("type-error result = %#v", broken)
	}
}

func TestNilnessSuppressionsAndSeverityUseCanonicalRuleIdentity(t *testing.T) {
	t.Parallel()

	root, _ := writeNilnessModule(
		t,
		`package sample
func inspect(pointer *int) {
	if pointer == nil {
		//glippy:ignore nilness -- guarded for a proving fixture
		_ = *pointer
	}
}
`,
	)
	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Preset: rules.PresetSuspicious,
			Overrides: map[string]rules.Severity{"nilness": rules.SeverityError},
		},
		analysis.PackageLoadOptions{Dir: root, Patterns: []string{"."}},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 1 ||
		len(result.Files[0].Diagnostics) != 0 ||
		len(result.Files[0].Suppressed) != 1 ||
		result.Files[0].Suppressed[0].Diagnostic.RuleID != "nilness" ||
		result.Files[0].Suppressed[0].Diagnostic.Severity != rules.SeverityError ||
		len(result.Files[0].UnusedSuppressions) != 0 ||
		len(result.Files[0].SuppressionProblems) != 0 {
		t.Fatalf("suppressed result = %#v", result.Files)
	}
}

func TestNilnessUsesPackageNoReturnSummaries(t *testing.T) {
	t.Parallel()

	input := `package sample
func stop() { panic("stop") }
func inspect(pointer *int) {
	if pointer != nil { stop() }
	if pointer != nil { println(pointer) }
}
`
	root, _ := writeNilnessModule(t, input)
	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{Preset: rules.PresetSuspicious},
		analysis.PackageLoadOptions{Dir: root, Patterns: []string{"."}},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != 1 {
		t.Fatalf("interprocedural no-return result = %#v", result.Files)
	}
	secondCondition := strings.LastIndex(input, "pointer != nil")
	diagnostic := result.Files[0].Diagnostics[0]
	if secondCondition < 0 ||
		diagnostic.RuleID != "nilness" ||
		diagnostic.MessageKey != "cond" ||
		diagnostic.Range.Start != secondCondition + len("pointer ") ||
		diagnostic.Range.End != diagnostic.Range.Start + len("!=") {
		t.Fatalf("interprocedural no-return result = %#v", result.Files)
	}
}

func TestNilnessUsesImportedReturnStateFacts(t *testing.T) {
	t.Parallel()

	root, path := writeNilnessModule(
		t,
		`package sample

import "example.com/nilness/delegate"

func inspect(found bool) {
	value, err := delegate.Lookup(found)
	if err != nil {
		_ = *value
		if value == nil { println("always") }
		if value != nil { println("impossible") }
	}
	if err == nil {
		if value == nil { println("impossible") }
		if value != nil { println("always") }
	}
}

func compound(found bool, report bool) {
	value, err := delegate.Lookup(found)
	if value != nil || err == nil || report {
		println(value != nil)
	}
}

`,
	)
	if err := os.MkdirAll(filepath.Join(root, "helper"), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(
		filepath.Join(root, "helper", "helper.go"),
		[]byte(
			`package helper

import "errors"

type Value struct{ Number int }

func Lookup(found bool) (*Value, error) {
	if !found { return nil, errors.New("missing") }
	return &Value{}, nil
}
`,
		),
		0o600,
	);
		err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(root, "delegate"), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(
		filepath.Join(root, "delegate", "delegate.go"),
		[]byte(
			`package delegate

import "example.com/nilness/helper"

func Lookup(found bool) (*helper.Value, error) { return helper.Lookup(found) }
`,
		),
		0o600,
	);
		err != nil {
		t.Fatal(err)
	}
	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{"nilness": rules.SeverityWarn},
		},
		analysis.PackageLoadOptions{Dir: root, Patterns: []string{"."}},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 1 || result.Files[0].Path != path {
		t.Fatalf("imported return-state files = %#v", result.Files)
	}
	file, found := result.Sources.Lookup(path)
	if !found {
		t.Fatal("imported return-state source is missing")
	}
	got := make([]string, len(result.Files[0].Diagnostics))
	messages := make([]string, len(result.Files[0].Diagnostics))
	for index, diagnostic := range result.Files[0].Diagnostics {
		text, valid := file.Slice(diagnostic.Range)
		if !valid {
			t.Fatalf("diagnostic %d range = %#v", index, diagnostic.Range)
		}
		got[index] = diagnostic.MessageKey + ":" + text
		messages[index] = diagnostic.Message
	}
	want := []string{"nilderef:*", "cond:==", "cond:!=", "cond:==", "cond:!="}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("imported return-state diagnostics = %#v, want %#v", got, want)
	}
	wantMessages := []string{
		"nil dereference in load",
		"tautological condition: nil == nil",
		"impossible condition: nil != nil",
		"impossible condition: non-nil == nil",
		"tautological condition: non-nil != nil",
	}
	if !reflect.DeepEqual(messages, wantMessages) {
		t.Fatalf("imported return-state messages = %#v, want %#v", messages, wantMessages)
	}
}

func TestNilnessPreservesReturnStateAssertionsInTestFiles(t *testing.T) {
	t.Parallel()

	input := `package sample

import "testing"

func TestLookup(t *testing.T) {
	value, err := lookup(false)
	if err == nil { t.Fatal("lookup succeeded") }
	if value != nil { t.Errorf("value = %v, want nil", value) }
	_ = *value

	value, err = lookup(true)
	if err != nil { t.Fatal(err) }
	if value == nil { t.Fatalf("value = nil, want non-nil") }
	if value != nil { println(value) }
	if value == nil { panic("unreachable") }
}

type fakeT struct{}

func (*fakeT) Fatalf(string, ...any) {}

func verifyWithLookalike(t *fakeT) {
	value, err := lookup(false)
	if err == nil { return }
	if value != nil { t.Fatalf("value = %v, want nil", value) }
}

func verifyWithFailNow(t *testing.T) {
	value, err := lookup(false)
	if err == nil { return }
	if value != nil { t.FailNow() }
}

func verifyWithFail(t *testing.T) {
	value, err := lookup(false)
	if err == nil { return }
	if value != nil { t.Fail() }
}

func verifyWithError(t *testing.T) {
	value, err := lookup(false)
	if err == nil { return }
	if value != nil { t.Error("unexpected value") }
}

func verifyWithFatal(t *testing.T) {
	value, err := lookup(false)
	if err == nil { return }
	if value != nil { t.Fatal("unexpected value") }
}

func currentT(t *testing.T) *testing.T { return t }

func verifySideEffectingReceiver(t *testing.T) {
	value, err := lookup(false)
	if err == nil { return }
	if value != nil { currentT(t).Fatal("unexpected value") }
}

func mutate() any { return nil }

func verifySideEffectingArgument(t *testing.T) {
	value, err := lookup(false)
	if err == nil { return }
	if value != nil { t.Fatalf("value = %v, mutation = %v", value, mutate()) }
}

func verifyReceivingArgument(t *testing.T, messages <-chan string) {
	value, err := lookup(false)
	if err == nil { return }
	if value != nil { t.Fatal(<-messages) }
}

func verifyIndexingArgument(t *testing.T, messages []string) {
	value, err := lookup(false)
	if err == nil { return }
	if value != nil { t.Fatal(messages[0]) }
}

func verifyDereferencingArgument(t *testing.T, message *string) {
	value, err := lookup(false)
	if err == nil { return }
	if value != nil { t.Fatal(*message) }
}

type expectation struct{ message string }

func verifyValueSelector(t *testing.T, want expectation) {
	value, err := lookup(false)
	if err == nil { return }
	if value != nil { t.Error(want.message) }
}

func verifyIndirectSelector(t *testing.T, want *expectation) {
	value, err := lookup(false)
	if err == nil { return }
	if value != nil { t.Error(want.message) }
}

func verifyExtraBranchWork(t *testing.T) {
	value, err := lookup(false)
	if err == nil { return }
	if value != nil { println(value); t.Fatal("unexpected value") }
}

func verifyElseBranch(t *testing.T) {
	value, err := lookup(false)
	if err == nil { return }
	if value != nil { t.Fatal("unexpected value") } else { println("expected") }
}
`
	root, path := writeNilnessModuleFile(t, "sample_test.go", input)
	productionPath := filepath.Join(root, "sample.go")
	if err := os.WriteFile(
		productionPath,
		[]byte(
			`package sample

import (
	"errors"
	"testing"
)

type Value struct{}

func lookup(found bool) (*Value, error) {
	if !found { return nil, errors.New("missing") }
	return &Value{}, nil
}

func verifyOutsideTest(t *testing.T) {
	value, err := lookup(false)
	if err == nil { return }
	if value != nil { t.Fatalf("value = %v, want nil", value) }
}
`,
		),
		0o600,
	);
		err != nil {
		t.Fatal(err)
	}
	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{"nilness": rules.SeverityWarn},
		},
		analysis.PackageLoadOptions{Dir: root, Patterns: []string{"."}, Tests: true},
	)
	if err != nil {
		t.Fatal(err)
	}
	var testResult *analysis.Result
	var productionResult *analysis.Result
	for index := range result.Files {
		switch result.Files[index].Path {
		case path:
			testResult = &result.Files[index]
		case productionPath:
			productionResult = &result.Files[index]
		}
	}
	if testResult == nil || productionResult == nil {
		t.Fatalf("test assertion files = %#v", result.Files)
	}
	file, found := result.Sources.Lookup(path)
	if !found {
		t.Fatal("test assertion source is missing")
	}
	got := make(map[int]string, len(testResult.Diagnostics))
	for index, diagnostic := range testResult.Diagnostics {
		text, valid := file.Slice(diagnostic.Range)
		if !valid {
			t.Fatalf("diagnostic %d range = %#v", index, diagnostic.Range)
		}
		if _, duplicate := got[diagnostic.Range.Start]; duplicate {
			t.Fatalf("duplicate diagnostic start at %d", diagnostic.Range.Start)
		}
		got[diagnostic.Range.Start] = diagnostic.MessageKey + ":" + text
	}
	diagnosticOffset := func(functionName, statement, operator string) int {
		t.Helper()
		functionOffset := strings.Index(input, "func " + functionName + "(")
		if functionOffset < 0 {
			t.Fatalf("function %q is missing from test input", functionName)
		}
		statementOffset := strings.Index(input[functionOffset:], statement)
		operatorOffset := strings.Index(statement, operator)
		if statementOffset < 0 || operatorOffset < 0 {
			t.Fatalf(
				"statement %q or operator %q is missing from function %q",
				statement,
				operator,
				functionName,
			)
		}
		return functionOffset + statementOffset + operatorOffset
	}
	want := map[int]string{
		diagnosticOffset("TestLookup", "_ = *value", "*"): "nilderef:*",
		diagnosticOffset(
			"TestLookup",
			"if value != nil { println(value) }",
			"!=",
		): "cond:!=",
		diagnosticOffset(
			"TestLookup",
			"if value == nil { panic(\"unreachable\") }",
			"==",
		): "cond:==",
		diagnosticOffset(
			"verifyWithLookalike",
			"if value != nil { t.Fatalf(\"value = %v, want nil\", value) }",
			"!=",
		): "cond:!=",
		diagnosticOffset(
			"verifySideEffectingReceiver",
			"if value != nil { currentT(t).Fatal(\"unexpected value\") }",
			"!=",
		): "cond:!=",
		diagnosticOffset(
			"verifySideEffectingArgument",
			"if value != nil { t.Fatalf(\"value = %v, mutation = %v\", value, mutate()) }",
			"!=",
		): "cond:!=",
		diagnosticOffset(
			"verifyReceivingArgument",
			"if value != nil { t.Fatal(<-messages) }",
			"!=",
		): "cond:!=",
		diagnosticOffset(
			"verifyIndexingArgument",
			"if value != nil { t.Fatal(messages[0]) }",
			"!=",
		): "cond:!=",
		diagnosticOffset(
			"verifyDereferencingArgument",
			"if value != nil { t.Fatal(*message) }",
			"!=",
		): "cond:!=",
		diagnosticOffset(
			"verifyIndirectSelector",
			"if value != nil { t.Error(want.message) }",
			"!=",
		): "cond:!=",
		diagnosticOffset(
			"verifyExtraBranchWork",
			"if value != nil { println(value); t.Fatal(\"unexpected value\") }",
			"!=",
		): "cond:!=",
		diagnosticOffset(
			"verifyElseBranch",
			"if value != nil { t.Fatal(\"unexpected value\") } else { println(\"expected\") }",
			"!=",
		): "cond:!=",
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("test assertion diagnostics = %#v, want %#v", got, want)
	}
	allowedAssertions := []int{
		diagnosticOffset(
			"TestLookup",
			"if value != nil { t.Errorf(\"value = %v, want nil\", value) }",
			"!=",
		),
		diagnosticOffset(
			"TestLookup",
			"if value == nil { t.Fatalf(\"value = nil, want non-nil\") }",
			"==",
		),
		diagnosticOffset("verifyWithFailNow", "if value != nil { t.FailNow() }", "!="),
		diagnosticOffset("verifyWithFail", "if value != nil { t.Fail() }", "!="),
		diagnosticOffset(
			"verifyWithError",
			"if value != nil { t.Error(\"unexpected value\") }",
			"!=",
		),
		diagnosticOffset(
			"verifyWithFatal",
			"if value != nil { t.Fatal(\"unexpected value\") }",
			"!=",
		),
		diagnosticOffset(
			"verifyValueSelector",
			"if value != nil { t.Error(want.message) }",
			"!=",
		),
	}
	for _, offset := range allowedAssertions {
		if diagnostic, found := got[offset]; found {
			t.Fatalf("allowed testing assertion at %d reported %q", offset, diagnostic)
		}
	}
	if len(productionResult.Diagnostics) != 1 ||
		productionResult.Diagnostics[0].MessageKey != "cond" {
		t.Fatalf("production testing assertion = %#v", productionResult.Diagnostics)
	}
}

func TestNilnessDoesNotLoadReturnStatesAcrossModuleBoundaries(t *testing.T) {
	t.Parallel()

	root, path := writeNilnessModule(
		t,
		`package sample

import "example.com/external/helper"

func inspect(found bool) {
	value, err := helper.Lookup(found)
	if err != nil { _ = *value }
}
`,
	)
	external := t.TempDir()
	if err := os.WriteFile(
		filepath.Join(external, "go.mod"),
		[]byte("module example.com/external\n\ngo 1.26.0\n"),
		0o600,
	);
		err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(
		filepath.Join(external, "helper.go"),
		[]byte(
			`package helper

import "errors"

type Value struct{}
func Lookup(found bool) (*Value, error) {
	if !found { return nil, errors.New("missing") }
	return &Value{}, nil
}
`,
		),
		0o600,
	);
		err != nil {
		t.Fatal(err)
	}
	module := "module example.com/nilness\n\ngo 1.26.0\n\nrequire example.com/external v0.0.0\nreplace example.com/external => " +
		external +
		"\n"
	if err := os.WriteFile(filepath.Join(root, "go.mod"), []byte(module), 0o600); err != nil {
		t.Fatal(err)
	}
	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{"nilness": rules.SeverityWarn},
		},
		analysis.PackageLoadOptions{Dir: root, Patterns: []string{"."}},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 1 ||
		result.Files[0].Path != path ||
		len(result.Files[0].Diagnostics) != 0 {
		t.Fatalf("external return-state result = %#v", result.Files)
	}
}

func TestNilnessUsesAuthoritativeNoReturnFunctions(t *testing.T) {
	t.Parallel()

	input := `package sample
import "os"
func inspect(pointer *int) {
	if pointer != nil { os.Exit(1) }
	if pointer != nil { println(pointer) }
}
`
	root, _ := writeNilnessModule(t, input)
	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{Preset: rules.PresetSuspicious},
		analysis.PackageLoadOptions{Dir: root, Patterns: []string{"."}},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != 1 {
		t.Fatalf("authoritative no-return result = %#v", result.Files)
	}
	secondCondition := strings.LastIndex(input, "pointer != nil")
	diagnostic := result.Files[0].Diagnostics[0]
	if secondCondition < 0 ||
		diagnostic.RuleID != "nilness" ||
		diagnostic.MessageKey != "cond" ||
		diagnostic.Range.Start != secondCondition + len("pointer ") ||
		diagnostic.Range.End != diagnostic.Range.Start + len("!=") {
		t.Fatalf("authoritative no-return result = %#v", result.Files)
	}
}

func TestDefaultRegistryDocumentsNilnessWithoutAFix(t *testing.T) {
	t.Parallel()

	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	metadata, found := registry.Metadata("nilness")
	if !found ||
		metadata.Requirement != rules.RequireSSA ||
		metadata.DefaultSeverity != rules.SeverityWarn ||
		metadata.MinimumGoVersion != "1.25" ||
		metadata.RunOnGenerated ||
		metadata.RunDespiteTypeErrors ||
		len(metadata.Fixes) != 0 ||
		len(metadata.Presets) != 1 ||
		metadata.Presets[0] != rules.PresetSuspicious ||
		len(metadata.Examples) == 0 ||
		len(metadata.KnownLimitations) == 0 {
		t.Fatalf("metadata = %#v, found = %v", metadata, found)
	}
}

func TestTypesControlFlowAndSSARulesRemainOptIn(t *testing.T) {
	t.Parallel()

	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		t.Fatal(err)
	}
	correctness, err := registry.Resolve(rules.PresetCorrectness, nil)
	if err != nil {
		t.Fatal(err)
	}
	if len(correctness) != 2 ||
		correctness[0].ID != "duplicate-condition" ||
		correctness[1].ID != "ineffective-break" {
		t.Fatalf("correctness selection = %#v", correctness)
	}
	suspicious, err := registry.Resolve(rules.PresetSuspicious, nil)
	if err != nil {
		t.Fatal(err)
	}
	if len(suspicious) != 5 ||
		suspicious[0].ID != "context-key" ||
		suspicious[0].Requirement != rules.RequireTypes ||
		suspicious[1].ID != "defer-in-infinite-loop" ||
		suspicious[1].Requirement != rules.RequireControlFlow ||
		suspicious[2].ID != "errors-is-arguments" ||
		suspicious[2].Requirement != rules.RequireTypes ||
		suspicious[3].ID != "identical-branches" ||
		suspicious[3].Requirement != rules.RequireSyntax ||
		suspicious[4].ID != "nilness" ||
		suspicious[4].Requirement != rules.RequireSSA {
		t.Fatalf("suspicious selection = %#v", suspicious)
	}
}

func BenchmarkNilnessSharedSSA(b *testing.B) {
	root := b.TempDir()
	if err := os.WriteFile(
		filepath.Join(root, "go.mod"),
		[]byte("module example.com/nilness\n\ngo 1.26.0\n"),
		0o600,
	);
		err != nil {
		b.Fatal(err)
	}
	var input strings.Builder
	input.WriteString("package sample\n")
	for index := range 100 {
		fmt.Fprintf(
			&input,
			"func inspect%d(pointer *int) { if pointer == nil { _ = *pointer } }\n",
			index,
		)
	}
	if err := os.WriteFile(filepath.Join(root, "sample.go"), []byte(input.String()), 0o600);
		err != nil {
		b.Fatal(err)
	}
	loaded, err := analysis.LoadPackages(
		context.Background(),
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			Requirement: rules.RequireSSA,
		},
	)
	if err != nil {
		b.Fatal(err)
	}
	nilnessRegistry, err := rules.NewDefaultRegistry()
	if err != nil {
		b.Fatal(err)
	}
	nilnessSelection, err := nilnessRegistry.Resolve(
		rules.PresetSuspicious,
		map[string]rules.Severity{
			"context-key": rules.SeverityOff,
			"defer-in-infinite-loop": rules.SeverityOff,
			"errors-is-arguments": rules.SeverityOff,
		},
	)
	if err != nil {
		b.Fatal(err)
	}
	baselineRegistry, err := rules.NewRegistry(benchmarkSSARule{})
	if err != nil {
		b.Fatal(err)
	}
	baselineSelection, err := baselineRegistry.Resolve(rules.PresetSuspicious, nil)
	if err != nil {
		b.Fatal(err)
	}

	b.Run(
		"baseline",
		func(b *testing.B) {
			benchmarkSSAExecution(b, loaded, baselineRegistry, baselineSelection, 0)
		},
	)
	b.Run(
		"nilness",
		func(b *testing.B) {
			benchmarkSSAExecution(b, loaded, nilnessRegistry, nilnessSelection, 100)
		},
	)
}

func BenchmarkNilnessImportedReturnStates(b *testing.B) {
	root := b.TempDir()
	if err := os.WriteFile(
		filepath.Join(root, "go.mod"),
		[]byte("module example.com/nilness\n\ngo 1.26.0\n"),
		0o600,
	);
		err != nil {
		b.Fatal(err)
	}
	var source strings.Builder
	source.WriteString("package sample\n\nimport \"example.com/nilness/helper\"\n")
	for index := range 100 {
		fmt.Fprintf(
			&source,
			"func inspect%d(found bool) { value, err := helper.Lookup(found); if err != nil { _ = *value }; if err == nil { if value == nil { println(value) } } }\n",
			index,
		)
	}
	if err := os.WriteFile(filepath.Join(root, "sample.go"), []byte(source.String()), 0o600);
		err != nil {
		b.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(root, "helper"), 0o700); err != nil {
		b.Fatal(err)
	}
	if err := os.WriteFile(
		filepath.Join(root, "helper", "helper.go"),
		[]byte(
			`package helper

import "errors"

type Value struct{}
func Lookup(found bool) (*Value, error) {
	if !found { return nil, errors.New("missing") }
	return &Value{}, nil
}
`,
		),
		0o600,
	);
		err != nil {
		b.Fatal(err)
	}
	loaded, err := analysis.LoadPackages(
		context.Background(),
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			Requirement: rules.RequireSSA,
			LoadEffectFacts: true,
		},
	)
	if err != nil {
		b.Fatal(err)
	}
	registry, err := rules.NewDefaultRegistry()
	if err != nil {
		b.Fatal(err)
	}
	selection, err := registry.Resolve(
		rules.PresetSuspicious,
		map[string]rules.Severity{
			"context-key": rules.SeverityOff,
			"defer-in-infinite-loop": rules.SeverityOff,
			"errors-is-arguments": rules.SeverityOff,
			"identical-branches": rules.SeverityOff,
		},
	)
	if err != nil {
		b.Fatal(err)
	}
	benchmarkSSAExecution(b, loaded, registry, selection, 200)
}

func benchmarkSSAExecution(
	b *testing.B,
	loaded analysis.PackageLoadResult,
	registry *rules.Registry,
	selection []rules.Selection,
	wantDiagnostics int,
) {
	b.Helper()
	b.ReportAllocs()
	for range b.N {
		diagnostics, err := analysis.RunSSA(
			context.Background(),
			loaded,
			registry,
			selection,
		)
		if err != nil {
			b.Fatal(err)
		}
		if len(diagnostics) != wantDiagnostics {
			b.Fatalf("diagnostics = %d, want %d", len(diagnostics), wantDiagnostics)
		}
	}
}

func writeNilnessModule(t testing.TB, source string) (string, string) {
	t.Helper()
	return writeNilnessModuleFile(t, "sample.go", source)
}

func writeNilnessModuleFile(t testing.TB, filename string, source string) (string, string) {
	t.Helper()
	root := t.TempDir()
	if err := os.WriteFile(
		filepath.Join(root, "go.mod"),
		[]byte("module example.com/nilness\n\ngo 1.26.0\n"),
		0o600,
	);
		err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(root, filename)
	if err := os.WriteFile(path, []byte(source), 0o600); err != nil {
		t.Fatal(err)
	}
	return root, path
}
