package report

import (
	"fmt"
	"strings"

	"github.com/faustbrian/glippy/internal/rules"
)

// RenderRuleCatalogMarkdown renders every registered rule from canonical
// metadata in deterministic rule-ID order.
func RenderRuleCatalogMarkdown(registry *rules.Registry) ([]byte, error) {
	if registry == nil {
		return nil, fmt.Errorf("render rule catalog requires a registry")
	}

	ids := registry.IDs()
	var output strings.Builder
	output.WriteString("# Lint Rules\n\n")
	output.WriteString(
		"<!-- Code generated by go generate ./internal/report; DO NOT EDIT. -->\n\n",
	)
	output.WriteString(
		"This catalog is rendered from the same immutable rule metadata used by the\n",
	)
	output.WriteString("registry, scheduler, configuration decoder, and `glippy explain`.\n")
	output.WriteString(
		"Preset membership and defaults describe the current development binary and are\n",
	)
	output.WriteString("not stable release promises.\n\n")
	output.WriteString("## Rules\n\n")
	if len(ids) == 0 {
		output.WriteString("None.\n")
		return []byte(output.String()), nil
	}
	for _, id := range ids {
		fmt.Fprintf(&output, "- [%s](#%s)\n", id, id)
	}
	output.WriteByte('\n')

	for index, id := range ids {
		metadata, found := registry.Metadata(id)
		if !found {
			return nil, fmt.Errorf("registered rule %q has no metadata", id)
		}
		writeRuleMarkdown(&output, metadata)
		if index + 1 < len(ids) {
			output.WriteByte('\n')
		}
	}
	return []byte(output.String()), nil
}

func writeRuleMarkdown(output *strings.Builder, metadata rules.Metadata) {
	fmt.Fprintf(output, "## %s\n\n%s\n\n", metadata.ID, metadata.Summary)
	writeWrappedMarkdown(output, "", "", metadata.Documentation, 100)
	output.WriteByte('\n')
	fmt.Fprintf(output, "- Default severity: `%s`\n", metadata.DefaultSeverity)
	fmt.Fprintf(output, "- Presets: %s\n", markdownPresetList(metadata.Presets))
	fmt.Fprintf(output, "- Minimum Go: `%s`\n", metadata.MinimumGoVersion)
	fmt.Fprintf(output, "- Analysis tier: %s\n", metadata.Requirement)
	fmt.Fprintf(output, "- Node interests: %s\n", markdownNodeKindList(metadata.NodeInterests))
	fmt.Fprintf(output, "- Dependency syntax: %s\n", catalogDependencyPolicy(metadata))
	fmt.Fprintf(output, "- Generated files: %s\n", catalogGeneratedPolicy(metadata))
	fmt.Fprintf(output, "- Type-error packages: %s\n", catalogTypeErrorPolicy(metadata))
	fmt.Fprintf(output, "- Categories: %s\n", markdownCategoryList(metadata.Categories))

	if metadata.Deprecation != nil {
		output.WriteString("\n### Deprecation\n\n")
		fmt.Fprintf(output, "- Since: `%s`\n", metadata.Deprecation.Since)
		if metadata.Deprecation.Replacement != "" {
			fmt.Fprintf(
				output,
				"- Replacement: `%s`\n",
				metadata.Deprecation.Replacement,
			)
		}
		writeWrappedMarkdown(output, "- Message: ", "  ", metadata.Deprecation.Message, 100)
	}

	output.WriteString("\n### Fixes\n\n")
	if len(metadata.Fixes) == 0 {
		output.WriteString("None.\n")
	}
	for _, fix := range metadata.Fixes {
		writeWrappedMarkdown(
			output,
			fmt.Sprintf("- `%s` (`%s`): ", fix.Name, fix.Safety),
			"  ",
			fix.Description,
			100,
		)
	}

	output.WriteString("\n### Configuration\n\n")
	if len(metadata.Options) == 0 {
		output.WriteString("None.\n")
	}
	for _, option := range metadata.Options {
		requirement := "required"
		if !option.Required && option.Default != nil {
			requirement = "optional, default `" + option.Default.String() + "`"
		}
		if option.Minimum != nil || option.Maximum != nil {
			requirement += ", range `" + optionRange(option) + "`"
		}
		writeWrappedMarkdown(
			output,
			fmt.Sprintf("- `%s` (`%s`; %s): ", option.Name, option.Kind, requirement),
			"  ",
			option.Summary,
			100,
		)
	}

	output.WriteString("\n### Known limitations\n\n")
	if len(metadata.KnownLimitations) == 0 {
		output.WriteString("None documented.\n")
	}
	for _, limitation := range metadata.KnownLimitations {
		writeWrappedMarkdown(output, "- ", "  ", limitation, 100)
	}

	for index, example := range metadata.Examples {
		title := strings.TrimSpace(example.Title)
		if title == "" {
			title = fmt.Sprintf("Example %d", index + 1)
		} else {
			title = "Example: " + title
		}
		fmt.Fprintf(output, "\n### %s\n\n**Incorrect**\n\n", title)
		writeMarkdownGoBlock(output, example.Incorrect)
		output.WriteString("\n**Correct**\n\n")
		writeMarkdownGoBlock(output, example.Correct)
	}
}

func markdownPresetList(values []rules.Preset) string {
	items := make([]string, len(values))
	for index, value := range values {
		items[index] = string(value)
	}
	return markdownCodeList(items)
}

func markdownNodeKindList(values []rules.NodeKind) string {
	if len(values) == 0 {
		return "none"
	}
	items := make([]string, len(values))
	for index, value := range values {
		items[index] = string(value)
	}
	return markdownCodeList(items)
}

func markdownCategoryList(values []rules.Category) string {
	items := make([]string, len(values))
	for index, value := range values {
		items[index] = string(value)
	}
	return markdownCodeList(items)
}

func markdownCodeList(values []string) string {
	return "`" + strings.Join(values, "`, `") + "`"
}

func catalogDependencyPolicy(metadata rules.Metadata) string {
	if metadata.RequiresDependencySyntax {
		return "required"
	}
	return "not required"
}

func catalogGeneratedPolicy(metadata rules.Metadata) string {
	if metadata.RunOnGenerated {
		return "included"
	}
	return "excluded"
}

func catalogTypeErrorPolicy(metadata rules.Metadata) string {
	if metadata.Requirement < rules.RequireTypes {
		return "not applicable"
	}
	if metadata.RunDespiteTypeErrors {
		return "included"
	}
	return "excluded"
}

func writeMarkdownGoBlock(output *strings.Builder, source string) {
	source = strings.TrimRight(source, "\r\n")
	fence := strings.Repeat("`", maximumBacktickRun(source) + 1)
	if len(fence) < 3 {
		fence = "```"
	}
	output.WriteString(fence)
	output.WriteString("go\n")
	output.WriteString(source)
	output.WriteByte('\n')
	output.WriteString(fence)
	output.WriteByte('\n')
}

func maximumBacktickRun(value string) int {
	maximum := 0
	current := 0
	for _, character := range value {
		if character == '`' {
			current++
			if current > maximum {
				maximum = current
			}
			continue
		}
		current = 0
	}
	return maximum
}

func writeWrappedMarkdown(
	output *strings.Builder,
	firstPrefix, continuationPrefix, value string,
	width int,
) {
	lines := strings.Split(strings.TrimSpace(value), "\n")
	for lineIndex, line := range lines {
		if lineIndex > 0 && strings.TrimSpace(line) == "" {
			output.WriteByte('\n')
			continue
		}
		words := strings.Fields(line)
		prefix := firstPrefix
		output.WriteString(prefix)
		column := len(prefix)
		for index, word := range words {
			separator := 0
			if index > 0 {
				separator = 1
			}
			if separator > 0 && column + separator + len(word) > width {
				output.WriteByte('\n')
				prefix = continuationPrefix
				output.WriteString(prefix)
				column = len(prefix)
				separator = 0
			}
			if separator > 0 {
				output.WriteByte(' ')
				column++
			}
			output.WriteString(word)
			column += len(word)
		}
		output.WriteByte('\n')
		firstPrefix = continuationPrefix
	}
}
