//go:build !glippy_never
// +build !glippy_never

// Code generated by the Glippy directive corpus. DO NOT EDIT.

package hostile

/*
#cgo CFLAGS: -DGLIPPY_DIRECTIVE_CORPUS=1
*/
import "C"

import _ "embed"

import _ "unsafe"

var _ = C.GLIPPY_DIRECTIVE_CORPUS

//go:embed directives.go
var embeddedDirectiveCorpus string

//go:linkname linkedDirectiveTarget example.com/glippy/directiveTarget
func linkedDirectiveTarget()

//go:generate go run example.invalid/generator
//go:noinline
//line directive_logical.go:100
func directiveTarget(value int) int {
	//glippy:ignore example because ownership is under test
	if value < 0 { return -value };return value
}
