package rulecatalog_test

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/faustbrian/glippy/internal/analysis"
	"github.com/faustbrian/glippy/internal/rulecatalog"
	"github.com/faustbrian/glippy/internal/rules"
)

func TestBlankErrorDiscardReportsOnlyBlankErrorResults(t *testing.T) {
	t.Parallel()

	input := `package sample

import "bytes"

func fail() error { return nil }
func pair() (int, error) { return 0, nil }
func errorFirst() (error, int) { return nil, 0 }
func number() int { return 0 }

func run(buffer *bytes.Buffer) error {
	_ = fail()
	value, _ := pair()
	_, _ = errorFirst()
	_, _ = number(), fail()
	_ = number()
	_, handled := pair()
	_, _ = buffer.WriteString("infallible")
	fail()
	_ = value
	return handled
}

func direct(err error) { _ = err }
`
	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/blankerror\n\ngo 1.26.0\n",
	)
	path := filepath.Join(root, "sample.go")
	writeFixture(t, path, input)
	result := runBlankErrorDiscard(t, root, "go1.26")
	if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != 5 {
		t.Fatalf("blank-error-discard diagnostics = %#v", result.Files)
	}
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	for _, diagnostic := range result.Files[0].Diagnostics {
		if diagnostic.RuleID != "blank-error-discard" ||
			string(content[diagnostic.Range.Start:diagnostic.Range.End]) != "_" ||
			diagnostic.MessageKey != "blank-error-discard" ||
			len(diagnostic.Fixes) != 0 {
			t.Fatalf("blank-error-discard diagnostic = %#v", diagnostic)
		}
	}
}

func TestBlankErrorDiscardHonorsRestrictionPolicy(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/blankpolicy\n\ngo 1.26.0\n",
	)
	writeFixture(
		t,
		filepath.Join(root, "sample.go"),
		`package sample
func fail() error { return nil }
func run() {
	//glippy:ignore blank-error-discard -- cleanup is deliberately best effort
	_ = fail()
}
`,
	)
	result := runBlankErrorDiscard(t, root, "go1.26")
	if len(result.Files) != 1 ||
		len(result.Files[0].Diagnostics) != 0 ||
		len(result.Files[0].Suppressed) != 1 {
		t.Fatalf("suppressed blank-error-discard result = %#v", result.Files)
	}

	generatedRoot := t.TempDir()
	writeFixture(
		t,
		filepath.Join(generatedRoot, "go.mod"),
		"module example.com/blankgenerated\n\ngo 1.26.0\n",
	)
	writeFixture(
		t,
		filepath.Join(generatedRoot, "sample.go"),
		"// Code generated by fixture. DO NOT EDIT.\npackage sample\nfunc fail() error { return nil }\nfunc run() { _ = fail() }\n",
	)
	generated := runBlankErrorDiscard(t, generatedRoot, "go1.26")
	if len(generated.Files) != 1 || len(generated.Files[0].Diagnostics) != 0 {
		t.Fatalf("generated blank-error-discard result = %#v", generated.Files)
	}

	illTypedRoot := t.TempDir()
	writeFixture(
		t,
		filepath.Join(illTypedRoot, "go.mod"),
		"module example.com/blankinvalid\n\ngo 1.26.0\n",
	)
	writeFixture(
		t,
		filepath.Join(illTypedRoot, "sample.go"),
		"package sample\nfunc fail() error { return nil }\nfunc run() { missing(); _ = fail() }\n",
	)
	illTyped := runBlankErrorDiscard(t, illTypedRoot, "go1.26")
	if len(illTyped.LoadDiagnostics) == 0 ||
		len(illTyped.Files) != 1 ||
		len(illTyped.Files[0].Diagnostics) != 0 {
		t.Fatalf("ill-typed blank-error-discard result = %#v", illTyped)
	}

	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	selection, err := registry.ResolveOptions(
		rules.ResolveOptions{
			Presets: []rules.Preset{rules.PresetRestriction},
			SourceGoVersion: "go1.26",
		},
	)
	if err == nil || len(selection) != 0 {
		t.Fatalf("wholesale restriction result = %#v, err = %v", selection, err)
	}
	selection, err = registry.ResolveOptions(
		rules.ResolveOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{
				"blank-error-discard": rules.SeverityWarn,
			},
			SourceGoVersion: "go1.24",
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(selection) != 0 {
		t.Fatalf("old-version restriction selection = %#v", selection)
	}

	metadata, found := registry.Metadata("blank-error-discard")
	if !found ||
		metadata.Requirement != rules.RequireTypes ||
		metadata.DefaultSeverity != rules.SeverityWarn ||
		metadata.MinimumGoVersion != "1.25" ||
		metadata.RunOnGenerated ||
		metadata.RunDespiteTypeErrors ||
		len(metadata.NodeInterests) != 1 ||
		metadata.NodeInterests[0] != rules.NodeAssignStmt ||
		len(metadata.Presets) != 1 ||
		metadata.Presets[0] != rules.PresetRestriction ||
		len(metadata.Options) != 1 ||
		metadata.Options[0].Name != "include-tests" ||
		len(metadata.Fixes) != 0 ||
		len(metadata.Examples) == 0 ||
		len(metadata.KnownLimitations) == 0 {
		t.Fatalf("blank-error-discard metadata = %#v, found = %v", metadata, found)
	}
}

func TestBlankErrorDiscardExcludesTestsUnlessConfigured(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/blanktests\n\ngo 1.26.0\n",
	)
	writeFixture(
		t,
		filepath.Join(root, "sample.go"),
		"package sample\nfunc fail() error { return nil }\n",
	)
	writeFixture(
		t,
		filepath.Join(root, "sample_test.go"),
		"package sample\nimport \"testing\"\nfunc TestFailure(t *testing.T) { _ = fail() }\n",
	)
	withoutTests := runBlankErrorDiscardWithTests(t, root, false)
	if countPackageDiagnostics(withoutTests) != 0 {
		t.Fatalf("default test-file result = %#v", withoutTests)
	}
	withTests := runBlankErrorDiscardWithTests(t, root, true)
	if countPackageDiagnostics(withTests) != 1 {
		t.Fatalf("included test-file result = %#v", withTests)
	}
}

func BenchmarkBlankErrorDiscardTypes(b *testing.B) {
	root := b.TempDir()
	writeFixture(
		b,
		filepath.Join(root, "go.mod"),
		"module example.com/blankbench\n\ngo 1.26.0\n",
	)
	writeFixture(
		b,
		filepath.Join(root, "sample.go"),
		"package sample\nfunc fail() error { return nil }\nfunc run() { _ = fail() }\n",
	)
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		b.Fatal(err)
	}
	benchmarkPackageRuns(
		b,
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{
				"blank-error-discard": rules.SeverityWarn,
			},
			SourceGoVersion: "go1.26",
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			ModuleMode: analysis.ModuleReadonly,
		},
		1,
	)
}

func runBlankErrorDiscard(t testing.TB, root string, goVersion string) analysis.PackageResult {
	t.Helper()
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{
				"blank-error-discard": rules.SeverityWarn,
			},
			SourceGoVersion: goVersion,
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	return result
}

func runBlankErrorDiscardWithTests(
	t testing.TB,
	root string,
	includeTests bool,
) analysis.PackageResult {
	t.Helper()
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{
				"blank-error-discard": rules.SeverityWarn,
			},
			RuleOptions: map[string]rules.OptionSet{
				"blank-error-discard": rules.NewOptionSet(
					map[string]rules.OptionValue{
						"include-tests": rules.BooleanOption(includeTests),
					},
				),
			},
			SourceGoVersion: "go1.26",
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			Tests: true,
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	return result
}
