package rulecatalog_test

import (
	"context"
	"reflect"
	"strings"
	"testing"

	"github.com/faustbrian/glippy/internal/analysis"
	"github.com/faustbrian/glippy/internal/rulecatalog"
	"github.com/faustbrian/glippy/internal/rules"
	"github.com/faustbrian/glippy/internal/source"
)

func TestBusySelectLoopReportsEmptyDefaults(t *testing.T) {
	t.Parallel()

	input := `package sample

func receive(ch <-chan int) {
	for {
		select {
		case <-ch:
		default:
		}
	}
}

func send(ch chan<- int) {
	for {
		select {
		default: // still spins when the send is unavailable
		case ch <- 1:
		}
	}
}

func defaultOnly() {
	for {
		select {
		default:
		}
	}
}

func explicitEmptyStatement() {
	for {
		select {
		default:;
		}
	}
}
`
	result := runBusySelectLoop(t, "sample.go", input, rules.SeverityWarn)
	if len(result.Diagnostics) != 4 {
		t.Fatalf("busy-select-loop result = %#v", result)
	}
	searchFrom := 0
	for index, diagnostic := range result.Diagnostics {
		relative := strings.Index(input[searchFrom:], "default:")
		if relative < 0 {
			t.Fatal("missing default clause marker")
		}
		start := searchFrom + relative
		if diagnostic.RuleID != "busy-select-loop" ||
			diagnostic.Severity != rules.SeverityWarn ||
			diagnostic.MessageKey != "busy-select-loop" ||
			diagnostic.Message !=
				"empty default in this for-select loop causes busy spinning" ||
			diagnostic.Range.Start != start ||
			diagnostic.Range.End != start + len("default:") ||
			len(diagnostic.Fixes) != 0 {
			t.Fatalf("busy-select-loop diagnostic[%d] = %#v", index, diagnostic)
		}
		searchFrom = start + len("default:")
	}
}

func TestBusySelectLoopExcludesNearbyControlFlow(t *testing.T) {
	t.Parallel()

	input := `package sample

func valid(ch <-chan int, keep bool, items []int) {
	select {
	case <-ch:
	default:
	}
	for keep {
		select {
		case <-ch:
		default:
		}
	}
	for index := 0; ; index++ {
		select {
		case <-ch:
		default:
		}
	}
	for {
		work()
		select {
		case <-ch:
		default:
		}
	}
	for {
		select {
		case <-ch:
		default:
			work()
		}
	}
	for {
		select {
		case <-ch:
		}
	}
	for range items {
		select {
		case <-ch:
		default:
		}
	}
}

func work() {}
`
	result := runBusySelectLoop(t, "sample.go", input, rules.SeverityWarn)
	if len(result.Diagnostics) != 0 {
		t.Fatalf("valid busy-select-loop result = %#v", result)
	}
}

func TestBusySelectLoopMetadata(t *testing.T) {
	t.Parallel()

	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	metadata, found := registry.Metadata("busy-select-loop")
	if !found ||
		metadata.DefaultSeverity != rules.SeverityWarn ||
		!reflect.DeepEqual(metadata.Presets, []rules.Preset{rules.PresetSuspicious}) ||
		metadata.MinimumGoVersion != "1.25" ||
		metadata.Requirement != rules.RequireSyntax ||
		!reflect.DeepEqual(metadata.NodeInterests, []rules.NodeKind{rules.NodeForStmt}) ||
		metadata.RunOnGenerated ||
		metadata.RunDespiteTypeErrors ||
		!reflect.DeepEqual(
			metadata.Categories,
			[]rules.Category{rules.CategoryCorrectness, rules.CategorySuspicious},
		) ||
		len(metadata.Fixes) != 0 ||
		len(metadata.Examples) == 0 ||
		len(metadata.KnownLimitations) == 0 {
		t.Fatalf("busy-select-loop metadata = %#v, found = %v", metadata, found)
	}
	selection, err := registry.ResolveOptions(
		rules.ResolveOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{
				"busy-select-loop": rules.SeverityWarn,
			},
			SourceGoVersion: "go1.24",
		},
	)
	if err != nil || len(selection) != 0 {
		t.Fatalf("pre-minimum busy-select-loop selection = %#v, %v", selection, err)
	}
}

func TestBusySelectLoopHonorsSharedPolicies(t *testing.T) {
	t.Parallel()

	visible := runBusySelectLoop(
		t,
		"visible.go",
		`package sample

func visible(ch <-chan int) {
	for {
		select {
		case <-ch:
		default:
		}
	}
}
`,
		rules.SeverityError,
	)
	suppressed := runBusySelectLoop(
		t,
		"suppressed.go",
		`package sample

func suppressed(ch <-chan int) {
	for {
		select {
		case <-ch:
		//glippy:ignore busy-select-loop -- this benchmark intentionally busy-polls
		default:
		}
	}
}
`,
		rules.SeverityError,
	)
	generated := runBusySelectLoop(
		t,
		"generated.go",
		`// Code generated by fixture. DO NOT EDIT.
package sample

func generated(ch <-chan int) {
	for {
		select {
		case <-ch:
		default:
		}
	}
}
`,
		rules.SeverityError,
	)
	if len(visible.Diagnostics) != 1 ||
		visible.Diagnostics[0].RuleID != "busy-select-loop" ||
		visible.Diagnostics[0].Severity != rules.SeverityError {
		t.Fatalf("visible busy-select-loop result = %#v", visible)
	}
	if len(suppressed.Diagnostics) != 0 ||
		len(suppressed.Suppressed) != 1 ||
		suppressed.Suppressed[0].Diagnostic.RuleID != "busy-select-loop" ||
		suppressed.Suppressed[0].Diagnostic.Severity != rules.SeverityError {
		t.Fatalf("suppressed busy-select-loop result = %#v", suppressed)
	}
	if len(generated.Diagnostics) != 0 || len(generated.Suppressed) != 0 {
		t.Fatalf("generated busy-select-loop result = %#v", generated)
	}
}

func runBusySelectLoop(
	t *testing.T,
	path string,
	input string,
	severity rules.Severity,
) analysis.Result {
	t.Helper()
	file, err := source.Load(path, []byte(input))
	if err != nil {
		t.Fatal(err)
	}
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.Run(
		context.Background(),
		file,
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{"busy-select-loop": severity},
			SourceGoVersion: "go1.25",
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	return result
}
