package rulecatalog_test

import (
	"context"
	"path/filepath"
	"reflect"
	"slices"
	"testing"

	"github.com/faustbrian/glippy/internal/analysis"
	"github.com/faustbrian/glippy/internal/rulecatalog"
	"github.com/faustbrian/glippy/internal/rules"
)

func TestStandardCatalogHonorsExactRuleSuppressions(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/standardcatalogsuppressions\n\ngo 1.26.0\n",
	)
	writeFixture(
		t,
		filepath.Join(root, "sample.go"),
		`package sample

import (
	"context"
	"net/http"
	"sync"
	"sync/atomic"
)

type state struct { lock sync.Mutex }
type reader interface { Read() }
type writer interface { Read(int) }

func copied(value *state) state {
	//glippy:ignore copied-lock -- verified compatibility copy
	return *value
}

func asserted(value reader) {
	//glippy:ignore impossible-type-assertion -- compatibility assertion
	_ = value.(writer)
}

func canceled(parent context.Context) context.Context {
	//glippy:ignore context-cancel-leak -- process lifetime context
	child, _ := context.WithCancel(parent)
	return child
}

func fetched() error {
	response, err := http.Get("https://example.test")
	//glippy:ignore http-response-before-error -- legacy request ordering
	defer response.Body.Close()
	if err != nil { return err }
	return nil
}

func incremented(value *uint64) {
	//glippy:ignore atomic-update-assignment -- legacy atomic wrapper
	*value = atomic.AddUint64(value, 1)
}
`,
	)
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{Preset: rules.PresetCorrectness, SourceGoVersion: "go1.26"},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 1 ||
		len(result.Files[0].Diagnostics) != 0 ||
		len(result.Files[0].Suppressed) != 5 {
		t.Fatalf("suppression result = %#v", result)
	}
	want := []string{
		"atomic-update-assignment",
		"context-cancel-leak",
		"copied-lock",
		"http-response-before-error",
		"impossible-type-assertion",
	}
	got := make([]string, len(result.Files[0].Suppressed))
	for index, suppressed := range result.Files[0].Suppressed {
		got[index] = suppressed.Diagnostic.RuleID
	}
	slices.Sort(got)
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("suppressed rules = %q, want %q", got, want)
	}
}

func TestStandardCatalogHonorsGeneratedAndTypeErrorPolicies(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/standardcatalogpolicy\n\ngo 1.26.0\n",
	)
	generatedPath := filepath.Join(root, "generated.go")
	writeFixture(
		t,
		generatedPath,
		`// Code generated by fixture. DO NOT EDIT.
package sample

import (
	"sync"
	"sync/atomic"
)

type generatedState struct { lock sync.Mutex }
func generatedCopy(value *generatedState) generatedState { return *value }
func generatedAtomic(value *uint64) { *value = atomic.AddUint64(value, 1) }
`,
	)
	invalidPath := filepath.Join(root, "invalid", "invalid.go")
	writeFixture(
		t,
		invalidPath,
		`package invalid

import (
	"context"
	"net/http"
	"sync"
	"sync/atomic"
)

type state struct { lock sync.Mutex }
type reader interface { Read() }
type writer interface { Read(int) }

func run(value *state, count *uint64, parent context.Context, item reader) state {
	copy := *value
	*count = atomic.AddUint64(count, 1)
	_, _ = context.WithCancel(parent)
	_ = item.(writer)
	response, err := http.Get("https://example.test")
	defer response.Body.Close()
	if err != nil { return copy }
	var invalid string = 1
	_ = invalid
	return copy
}
`,
	)
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{Preset: rules.PresetCorrectness, SourceGoVersion: "go1.26"},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"./..."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 2 || len(result.LoadDiagnostics) == 0 {
		t.Fatalf("policy result = %#v", result)
	}
	for _, file := range result.Files {
		switch file.Path {
		case generatedPath:
			if len(file.Diagnostics) != 0 {
				t.Fatalf("generated diagnostics = %#v", file.Diagnostics)
			}
		case invalidPath:
			got := make([]string, len(file.Diagnostics))
			for index, diagnostic := range file.Diagnostics {
				got[index] = diagnostic.RuleID
			}
			slices.Sort(got)
			got = slices.Compact(got)
			want := []string{"atomic-update-assignment", "copied-lock"}
			if !reflect.DeepEqual(got, want) {
				t.Fatalf("type-error diagnostics = %q, want %q", got, want)
			}
		default:
			t.Fatalf("unexpected policy path %q", file.Path)
		}
	}
}
