package rulecatalog_test

import (
	"context"
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"github.com/faustbrian/glippy/internal/analysis"
	"github.com/faustbrian/glippy/internal/rulecatalog"
	"github.com/faustbrian/glippy/internal/rules"
)

func TestRegistryIncludesSelfAssignmentContract(t *testing.T) {
	t.Parallel()

	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	metadata, found := registry.Metadata("self-assignment")
	if !found {
		t.Fatal("product registry does not include self-assignment")
	}
	if metadata.DefaultSeverity != rules.SeverityWarn ||
		!reflect.DeepEqual(metadata.Presets, []rules.Preset{rules.PresetCorrectness}) ||
		metadata.MinimumGoVersion != "1.25" ||
		metadata.Requirement != rules.RequireTypes ||
		!reflect.DeepEqual(metadata.NodeInterests, []rules.NodeKind{rules.NodeFile}) ||
		metadata.RunOnGenerated ||
		metadata.RunDespiteTypeErrors ||
		len(metadata.Fixes) != 1 ||
		metadata.Fixes[0].Name != "remove-self-assignment" ||
		metadata.Fixes[0].Safety != rules.FixSuggestion {
		t.Fatalf("self-assignment metadata = %#v", metadata)
	}
}

func TestRegistryIncludesCorrectnessAnalyzerContracts(t *testing.T) {
	t.Parallel()

	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	tests := []struct {
		id string
		requirement rules.Requirement
		nodeInterests []rules.NodeKind
		runDespiteTypeErrors bool
	}{
		{
			id: "atomic-update-assignment",
			requirement: rules.RequireTypes,
			nodeInterests: []rules.NodeKind{rules.NodeFile},
			runDespiteTypeErrors: true,
		},
		{id: "context-cancel-leak", requirement: rules.RequireControlFlow},
		{
			id: "copied-lock",
			requirement: rules.RequireTypes,
			nodeInterests: []rules.NodeKind{rules.NodeFile},
			runDespiteTypeErrors: true,
		},
		{
			id: "http-response-before-error",
			requirement: rules.RequireTypes,
			nodeInterests: []rules.NodeKind{rules.NodeFile},
		},
		{
			id: "impossible-type-assertion",
			requirement: rules.RequireTypes,
			nodeInterests: []rules.NodeKind{rules.NodeFile},
		},
		{
			id: "loop-capture",
			requirement: rules.RequireTypes,
			nodeInterests: []rules.NodeKind{rules.NodeForStmt, rules.NodeRangeStmt},
		},
	}
	for _, test := range tests {
		metadata, found := registry.Metadata(test.id)
		if !found {
			t.Fatalf("product registry does not include %s", test.id)
		}
		if metadata.DefaultSeverity != rules.SeverityWarn ||
			!reflect.DeepEqual(
				metadata.Presets,
				[]rules.Preset{rules.PresetCorrectness},
			) ||
			metadata.MinimumGoVersion != "1.25" ||
			metadata.Requirement != test.requirement ||
			!reflect.DeepEqual(metadata.NodeInterests, test.nodeInterests) ||
			metadata.RunOnGenerated ||
			metadata.RunDespiteTypeErrors != test.runDespiteTypeErrors ||
			len(metadata.Fixes) != 0 {
			t.Fatalf("%s metadata = %#v", test.id, metadata)
		}
	}
}

func TestContextCancelLeakDoesNotLoadDependencySyntax(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/contextcancelcost\n\ngo 1.26.0\n",
	)
	path := filepath.Join(root, "sample.go")
	writeFixture(
		t,
		path,
		`package sample

import "context"

func leak(parent context.Context) context.Context {
	child, _ := context.WithCancel(parent)
	return child
}
`,
	)
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{
				"context-cancel-leak": rules.SeverityWarn,
			},
			SourceGoVersion: "go1.26",
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if paths := result.Sources.Paths(); !reflect.DeepEqual(paths, []string{path}) {
		t.Fatalf(
			"context-cancel-leak loaded %d source files, want only the target source",
			len(paths),
		)
	}
	if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != 1 {
		t.Fatalf("context-cancel-leak result = %#v", result)
	}
}

func TestSelfAssignmentHonorsSuppressionGeneratedAndTypeErrorPolicies(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/selfassignmentpolicy\n\ngo 1.26.0\n",
	)
	suppressedPath := filepath.Join(root, "suppressed.go")
	writeFixture(
		t,
		suppressedPath,
		`package sample

func suppressed(value int) int {
	//glippy:ignore self-assignment -- compatibility assignment
	value = value
	return value
}

`,
	)
	generatedPath := filepath.Join(root, "generated.go")
	writeFixture(
		t,
		generatedPath,
		`// Code generated by fixture. DO NOT EDIT.
package sample

func generated(value int) int {
	value = value
	return value
}
`,
	)
	invalidPath := filepath.Join(root, "invalid", "invalid.go")
	writeFixture(
		t,
		invalidPath,
		`package invalid

func invalid(value int) int {
	value = value
	var text string = 1
	_ = text
	return value
}
`,
	)
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{"self-assignment": rules.SeverityWarn},
			SourceGoVersion: "go1.26",
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"./..."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 3 || len(result.LoadDiagnostics) == 0 {
		t.Fatalf("policy result = %#v", result)
	}
	for _, file := range result.Files {
		switch file.Path {
		case suppressedPath:
			if len(file.Diagnostics) != 0 ||
				len(file.Suppressed) != 1 ||
				file.Suppressed[0].Diagnostic.RuleID != "self-assignment" {
				t.Fatalf("suppressed result = %#v", file)
			}
		case generatedPath, invalidPath:
			if len(file.Diagnostics) != 0 || len(file.Suppressed) != 0 {
				t.Fatalf("excluded result for %s = %#v", file.Path, file)
			}
		default:
			t.Fatalf("unexpected analyzed path %q", file.Path)
		}
	}
}

func BenchmarkSelfAssignmentPackageAnalysis(b *testing.B) {
	root := b.TempDir()
	writeFixture(
		b,
		filepath.Join(root, "go.mod"),
		"module example.com/selfassignmentbenchmark\n\ngo 1.26.0\n",
	)
	writeFixture(
		b,
		filepath.Join(root, "sample.go"),
		"package sample\nfunc reset(value int) int { value = value; return value }\n",
	)
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		b.Fatal(err)
	}
	baseline, err := rules.NewRegistry(benchmarkPackageRule{})
	if err != nil {
		b.Fatal(err)
	}
	options := analysis.RunOptions{
		Presets: []rules.Preset{},
		Overrides: map[string]rules.Severity{"self-assignment": rules.SeverityWarn},
		SourceGoVersion: "go1.26",
	}
	load := analysis.PackageLoadOptions{
		Dir: root,
		Patterns: []string{"."},
		ModuleMode: analysis.ModuleReadonly,
	}
	b.Run(
		"typed-baseline",
		func(b *testing.B) {
			benchmarkPackageRuns(
				b,
				baseline,
				analysis.RunOptions{
					Preset: rules.PresetCorrectness,
					SourceGoVersion: "go1.26",
				},
				load,
				0,
			)
		},
	)
	b.Run(
		"with-rule",
		func(b *testing.B) {
			benchmarkPackageRuns(b, registry, options, load, 1)
		},
	)
}

func BenchmarkCorrectnessAnalyzerCatalogPackageAnalysis(b *testing.B) {
	root := b.TempDir()
	writeFixture(
		b,
		filepath.Join(root, "go.mod"),
		"module example.com/standardcatalogbenchmark\n\ngo 1.26.0\n",
	)
	writeFixture(
		b,
		filepath.Join(root, "sample.go"),
		`package sample

import (
	"context"
	"net/http"
	"sync"
	"sync/atomic"
)

type state struct { lock sync.Mutex }
type reader interface { Read() }
type writer interface { Read(int) }

func copied(value *state) state { return *value }
func asserted(value reader) { _ = value.(writer) }
func canceled(parent context.Context) context.Context {
	child, _ := context.WithCancel(parent)
	return child
}
func fetched() error {
	response, err := http.Get("https://example.test")
	defer response.Body.Close()
	if err != nil { return err }
	return nil
}
func incremented(value *uint64) { *value = atomic.AddUint64(value, 1) }
func captured(values []int) {
	var value int
	for _, value = range values { go func() { _ = value }() }
}
`,
	)
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		b.Fatal(err)
	}
	baseline, err := rules.NewRegistry(benchmarkPackageRule{})
	if err != nil {
		b.Fatal(err)
	}
	load := analysis.PackageLoadOptions{
		Dir: root,
		Patterns: []string{"."},
		ModuleMode: analysis.ModuleReadonly,
	}
	b.Run(
		"typed-baseline",
		func(b *testing.B) {
			benchmarkPackageRuns(
				b,
				baseline,
				analysis.RunOptions{
					Preset: rules.PresetCorrectness,
					SourceGoVersion: "go1.26",
				},
				load,
				0,
			)
		},
	)
	b.Run(
		"with-correctness-analyzers",
		func(b *testing.B) {
			benchmarkPackageRuns(
				b,
				registry,
				analysis.RunOptions{
					Preset: rules.PresetCorrectness,
					SourceGoVersion: "go1.26",
				},
				load,
				6,
			)
		},
	)
	for _, ruleID := range
		[]string{
			"atomic-update-assignment",
			"context-cancel-leak",
			"copied-lock",
			"http-response-before-error",
			"impossible-type-assertion",
			"loop-capture",
		} {
		ruleID := ruleID
		b.Run(
			ruleID,
			func(b *testing.B) {
				benchmarkPackageRuns(
					b,
					registry,
					analysis.RunOptions{
						Presets: []rules.Preset{},
						Overrides: map[string]rules.Severity{
							ruleID: rules.SeverityWarn,
						},
						SourceGoVersion: "go1.26",
					},
					load,
					1,
				)
			},
		)
	}
}

type benchmarkPackageRule struct{}

func (benchmarkPackageRule) Metadata() rules.Metadata {
	return rules.Metadata{
		ID: "typed-baseline",
		Summary: "provides a typed package benchmark baseline",
		Documentation: "Runs no diagnostics while retaining typed package loading.",
		DefaultSeverity: rules.SeverityWarn,
		Presets: []rules.Preset{rules.PresetCorrectness},
		MinimumGoVersion: "1.25",
		Requirement: rules.RequireTypes,
		Categories: []rules.Category{rules.CategoryCorrectness},
		Examples: []rules.Example{{Incorrect: "var value int", Correct: "var value int"}},
	}
}

func (benchmarkPackageRule) RunPackage(*rules.PackageContext) ([]rules.PackageFinding, error) {
	return nil, nil
}

func benchmarkPackageRuns(
	b *testing.B,
	registry *rules.Registry,
	options analysis.RunOptions,
	load analysis.PackageLoadOptions,
	diagnostics int,
) {
	b.Helper()
	b.ResetTimer()
	for range b.N {
		result, err := analysis.RunPackages(context.Background(), registry, options, load)
		if err != nil {
			b.Fatal(err)
		}
		if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != diagnostics {
			b.Fatalf("benchmark result = %#v", result)
		}
	}
}

type fixtureTB interface {
	Helper()
	Fatal(...any)
}

func writeFixture(tb fixtureTB, path, content string) {
	tb.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		tb.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		tb.Fatal(err)
	}
}
