package rulecatalog_test

import (
	"context"
	"path/filepath"
	"reflect"
	"slices"
	"testing"

	"github.com/faustbrian/glippy/internal/analysis"
	"github.com/faustbrian/glippy/internal/rulecatalog"
	"github.com/faustbrian/glippy/internal/rules"
)

func TestComparisonCatalogHonorsSuppressionsGeneratedAndTypeErrorPolicies(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/comparisonpolicy\n\ngo 1.25.0\n",
	)
	writeFixture(
		t,
		filepath.Join(root, "suppressed.go"),
		`package sample

func checks(value uint8) (bool, bool, bool) {
	//glippy:ignore impossible-comparison -- retained compatibility condition
	impossible := value > 255
	//glippy:ignore bad-bit-mask -- retained compatibility mask
	masked := value&2 == 1
	//glippy:ignore contradictory-condition -- retained compatibility condition
	contradictory := value == 1 && value == 2
	return impossible, masked, contradictory
}

func branch(value int) int {
	//glippy:ignore subsumed-condition -- retained compatibility branch
	if value > 0 { return 1 } else if value > 10 { return 2 }
	return 0
}
`,
	)
	writeFixture(
		t,
		filepath.Join(root, "generated.go"),
		`// Code generated by fixture. DO NOT EDIT.
package sample

func generated(value uint8) bool { return value > 255 || value&2 == 1 }
`,
	)
	writeFixture(
		t,
		filepath.Join(root, "invalid", "invalid.go"),
		`package invalid

func invalid(value uint8) bool {
	var text string = 1
	_ = text
	return value > 255 || value&2 == 1
}
`,
	)
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{
				"bad-bit-mask": rules.SeverityWarn,
				"contradictory-condition": rules.SeverityWarn,
				"impossible-comparison": rules.SeverityWarn,
				"subsumed-condition": rules.SeverityWarn,
			},
			SourceGoVersion: "go1.25",
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"./..."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 3 || len(result.LoadDiagnostics) == 0 {
		t.Fatalf("comparison policy result = %#v", result)
	}
	for _, file := range result.Files {
		switch filepath.Base(file.Path) {
		case "suppressed.go":
			if len(file.Diagnostics) != 0 || len(file.Suppressed) != 4 {
				t.Fatalf("suppressed result = %#v", file)
			}
			got := make([]string, len(file.Suppressed))
			for index, suppressed := range file.Suppressed {
				got[index] = suppressed.Diagnostic.RuleID
			}
			slices.Sort(got)
			want := []string{
				"bad-bit-mask",
				"contradictory-condition",
				"impossible-comparison",
				"subsumed-condition",
			}
			if !reflect.DeepEqual(got, want) {
				t.Fatalf("suppressed rules = %q, want %q", got, want)
			}
		case "generated.go", "invalid.go":
			if len(file.Diagnostics) != 0 || len(file.Suppressed) != 0 {
				t.Fatalf("excluded result = %#v", file)
			}
		default:
			t.Fatalf("unexpected file %q", file.Path)
		}
	}
}

func TestComparisonCatalogHonorsMinimumSourceVersion(t *testing.T) {
	t.Parallel()

	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	overrides := map[string]rules.Severity{
		"bad-bit-mask": rules.SeverityWarn,
		"contradictory-condition": rules.SeverityWarn,
		"impossible-comparison": rules.SeverityWarn,
		"subsumed-condition": rules.SeverityWarn,
	}
	selection, err := registry.ResolveOptions(
		rules.ResolveOptions{
			Presets: []rules.Preset{},
			Overrides: overrides,
			SourceGoVersion: "go1.24",
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(selection) != 0 {
		t.Fatalf("pre-minimum comparison selection = %#v", selection)
	}
	selection, err = registry.ResolveOptions(
		rules.ResolveOptions{
			Presets: []rules.Preset{},
			Overrides: overrides,
			SourceGoVersion: "go1.25",
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(selection) != 4 {
		t.Fatalf("minimum-version comparison selection = %#v", selection)
	}
}
