package rulecatalog_test

import (
	"context"
	"reflect"
	"testing"

	"github.com/faustbrian/glippy/internal/analysis"
	"github.com/faustbrian/glippy/internal/rulecatalog"
	"github.com/faustbrian/glippy/internal/rules"
	"github.com/faustbrian/glippy/internal/source"
)

func TestComplexityPresetRegistersCalibratedRules(t *testing.T) {
	t.Parallel()

	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	wantDefaults := map[string]int64{
		"excessive-nesting": 5,
		"too-many-lines": 100,
		"too-many-parameters": 7,
		"too-many-results": 3,
	}
	for id, defaultValue := range wantDefaults {
		metadata, found := registry.Metadata(id)
		if !found ||
			metadata.DefaultSeverity != rules.SeverityWarn ||
			!reflect.DeepEqual(
				metadata.Presets,
				[]rules.Preset{rules.PresetComplexity},
			) ||
			metadata.Requirement != rules.RequireSyntax ||
			metadata.RunOnGenerated ||
			len(metadata.Fixes) != 0 ||
			len(metadata.Options) != 2 ||
			metadata.Options[0].Name != "maximum" ||
			metadata.Options[0].Default == nil ||
			metadata.Options[0].Default.String() !=
				rules.IntegerOption(defaultValue).String() ||
			metadata.Options[0].Minimum == nil ||
			*metadata.Options[0].Minimum != 1 ||
			metadata.Options[0].Maximum == nil {
			t.Fatalf("%s metadata = %#v, found = %t", id, metadata, found)
		}
	}
}

func TestComplexityPresetExcludesTestsUnlessConfigured(t *testing.T) {
	t.Parallel()

	input := "package sample\nfunc fixture(first, second int) {}\n"
	defaultResult := runCatalogComplexityFile(
		t,
		"sample_test.go",
		input,
		"go1.25",
		map[string]rules.OptionSet{
			"too-many-parameters": rules.NewOptionSet(
				map[string]rules.OptionValue{"maximum": rules.IntegerOption(1)},
			),
		},
	)
	if len(defaultResult.Diagnostics) != 0 {
		t.Fatalf("default test complexity diagnostics = %#v", defaultResult.Diagnostics)
	}
	configured := runCatalogComplexityFile(
		t,
		"sample_test.go",
		input,
		"go1.25",
		map[string]rules.OptionSet{
			"too-many-parameters": rules.NewOptionSet(
				map[string]rules.OptionValue{
					"maximum": rules.IntegerOption(1),
					"include-tests": rules.BooleanOption(true),
				},
			),
		},
	)
	if len(configured.Diagnostics) != 1 ||
		configured.Diagnostics[0].RuleID != "too-many-parameters" {
		t.Fatalf("configured test complexity diagnostics = %#v", configured.Diagnostics)
	}
}

func TestComplexityPresetUsesSuppressionsGeneratedPolicyAndGoVersion(t *testing.T) {
	t.Parallel()

	input := `package sample

//glippy:ignore too-many-parameters -- compatibility callback shape
func suppressed(first, second int) {}

func reported(first, second int) {}
`
	result := runCatalogComplexity(
		t,
		input,
		"go1.25",
		map[string]rules.OptionSet{
			"too-many-parameters": rules.NewOptionSet(
				map[string]rules.OptionValue{"maximum": rules.IntegerOption(1)},
			),
		},
	)
	if len(result.Diagnostics) != 1 ||
		result.Diagnostics[0].RuleID != "too-many-parameters" ||
		len(result.Suppressed) != 1 {
		t.Fatalf("complexity suppression result = %#v", result)
	}

	generated := runCatalogComplexity(
		t,
		"// Code generated by fixture. DO NOT EDIT.\n" + input,
		"go1.25",
		nil,
	)
	if len(generated.Diagnostics) != 0 {
		t.Fatalf("generated complexity diagnostics = %#v", generated.Diagnostics)
	}

	older := runCatalogComplexity(t, input, "go1.24", nil)
	if len(older.Diagnostics) != 0 {
		t.Fatalf("Go 1.24 complexity diagnostics = %#v", older.Diagnostics)
	}
}

func BenchmarkComplexityPresetSyntaxAnalysis(b *testing.B) {
	input := []byte(
		"package sample\nfunc run(first, second int) (int, error) { if first > 0 { for second > 0 { second-- } }; return first, nil }\n",
	)
	file, err := source.Load("sample.go", input)
	if err != nil {
		b.Fatal(err)
	}
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		b.Fatal(err)
	}
	b.ReportAllocs()
	b.ResetTimer()
	for range b.N {
		result, runErr := analysis.Run(
			context.Background(),
			file,
			registry,
			analysis.RunOptions{
				Presets: []rules.Preset{rules.PresetComplexity},
				SourceGoVersion: "go1.25",
			},
		)
		if runErr != nil {
			b.Fatal(runErr)
		}
		if len(result.Diagnostics) != 0 {
			b.Fatalf("complexity diagnostics = %#v", result.Diagnostics)
		}
	}
}

func runCatalogComplexity(
	t *testing.T,
	input string,
	goVersion string,
	options map[string]rules.OptionSet,
) analysis.Result {
	return runCatalogComplexityFile(t, "sample.go", input, goVersion, options)
}

func runCatalogComplexityFile(
	t *testing.T,
	path string,
	input string,
	goVersion string,
	options map[string]rules.OptionSet,
) analysis.Result {
	t.Helper()
	file, err := source.Load(path, []byte(input))
	if err != nil {
		t.Fatal(err)
	}
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.Run(
		context.Background(),
		file,
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{rules.PresetComplexity},
			RuleOptions: options,
			SourceGoVersion: goVersion,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	return result
}
