package rulecatalog_test

import (
	"context"
	"path/filepath"
	"reflect"
	"slices"
	"testing"

	"github.com/faustbrian/glippy/internal/analysis"
	"github.com/faustbrian/glippy/internal/rulecatalog"
	"github.com/faustbrian/glippy/internal/rules"
)

func TestLoopAndErrorCatalogHonorsSuppressionGeneratedAndTypeErrorPolicies(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/looperrorpolicy\n\ngo 1.25.0\n",
	)
	writeFixture(
		t,
		filepath.Join(root, "suppressed.go"),
		`package sample

type item struct { ready bool }
func fail() error { return nil }
func cleanup() {}

func suppressed(values []item) {
	//glippy:ignore discarded-error -- deliberate best effort
	fail()
	for _, value := range values {
		//glippy:ignore suspicious-range -- local copy is inspected later
		value.ready = true
		//glippy:ignore defer-in-loop -- bounded batch owns deferred cleanup
		defer cleanup()
	}
}
`,
	)
	writeFixture(
		t,
		filepath.Join(root, "generated.go"),
		`// Code generated by fixture. DO NOT EDIT.
package sample
func generated(values []item) { fail(); for _, value := range values { value.ready = true; defer cleanup() } }
`,
	)
	writeFixture(
		t,
		filepath.Join(root, "invalid", "invalid.go"),
		`package invalid
type item struct { ready bool }
func fail() error { return nil }
func cleanup() {}
func invalid(values []item) { fail(); for _, value := range values { value.ready = true; defer cleanup() }; var text string = 1; _ = text }
`,
	)
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	overrides := map[string]rules.Severity{
		"defer-in-loop": rules.SeverityWarn,
		"discarded-error": rules.SeverityWarn,
		"suspicious-range": rules.SeverityWarn,
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: overrides,
			SourceGoVersion: "go1.25",
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"./..."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 3 || len(result.LoadDiagnostics) == 0 {
		t.Fatalf("loop and error policy result = %#v", result)
	}
	for _, file := range result.Files {
		switch filepath.Base(file.Path) {
		case "suppressed.go":
			if len(file.Diagnostics) != 0 || len(file.Suppressed) != 3 {
				t.Fatalf("suppressed result = %#v", file)
			}
			got := make([]string, len(file.Suppressed))
			for index, suppressed := range file.Suppressed {
				got[index] = suppressed.Diagnostic.RuleID
			}
			slices.Sort(got)
			want := []string{"defer-in-loop", "discarded-error", "suspicious-range"}
			if !reflect.DeepEqual(got, want) {
				t.Fatalf("suppressed rules = %q, want %q", got, want)
			}
		case "generated.go":
			if len(file.Diagnostics) != 0 || len(file.Suppressed) != 0 {
				t.Fatalf("excluded result = %#v", file)
			}
		case "invalid.go":
			if len(file.Diagnostics) != 1 ||
				file.Diagnostics[0].RuleID != "defer-in-loop" ||
				len(file.Suppressed) != 0 {
				t.Fatalf("syntax-tier type-error result = %#v", file)
			}
		default:
			t.Fatalf("unexpected file %q", file.Path)
		}
	}
	selection, err := registry.ResolveOptions(
		rules.ResolveOptions{
			Presets: []rules.Preset{},
			Overrides: overrides,
			SourceGoVersion: "go1.24",
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(selection) != 0 {
		t.Fatalf("pre-minimum selection = %#v", selection)
	}
}
