package rulecatalog_test

import (
	"context"
	"fmt"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/faustbrian/glippy/internal/analysis"
	"github.com/faustbrian/glippy/internal/rulecatalog"
	"github.com/faustbrian/glippy/internal/rules"
)

func TestNetIPBytesEqualReportsSemanticIPComparisons(t *testing.T) {
	t.Parallel()

	input := `package sample

import (
	byteutil "bytes"
	"net"
)

func sameAddress(first, second net.IP) bool {
	return byteutil.Equal(first, second)
}
`
	result := runStandardLibraryArgumentRule(t, input, "net-ip-bytes-equal")
	if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != 1 {
		t.Fatalf("net-ip-bytes-equal result = %#v", result)
	}
	diagnostic := result.Files[0].Diagnostics[0]
	if diagnostic.RuleID != "net-ip-bytes-equal" ||
		diagnostic.MessageKey != "representation-sensitive-comparison" ||
		diagnostic.Message !=
			"bytes.Equal does not account for equivalent net.IP representations" ||
		diagnostic.Range.Start < 0 ||
		diagnostic.Range.End > len(input) ||
		input[diagnostic.Range.Start:diagnostic.Range.End] !=
			"byteutil.Equal(first, second)" ||
		len(diagnostic.Fixes) != 0 {
		t.Fatalf("net-ip-bytes-equal diagnostic = %#v", diagnostic)
	}
}

func TestNetIPBytesEqualRecognizesAliasesAndDotImports(t *testing.T) {
	t.Parallel()

	input := `package sample

import (
	. "bytes"
	"net"
)

type address = net.IP

func sameAddress(first, second address) bool {
	return Equal(first, second)
}
`
	result := runStandardLibraryArgumentRule(t, input, "net-ip-bytes-equal")
	if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != 1 {
		t.Fatalf("aliased net-ip-bytes-equal result = %#v", result)
	}
}

func TestNetIPBytesEqualExcludesNonIPAndIndirectComparisons(t *testing.T) {
	t.Parallel()

	input := `package sample

import (
	"bytes"
	"net"
)

type namedBytes []byte
type namedIP net.IP
type localBytes struct{}

func (localBytes) Equal([]byte, []byte) bool { return false }

func inspect(
	first net.IP,
	second net.IP,
	raw []byte,
	namedFirst namedIP,
	namedSecond namedIP,
	local localBytes,
) {
	_ = bytes.Equal(first, raw)
	_ = bytes.Equal(raw, second)
	_ = bytes.Equal(raw, raw)
	_ = bytes.Equal(namedFirst, namedSecond)
	_ = local.Equal(first, second)
	function := bytes.Equal
	_ = function(first, second)
	_ = first.Equal(second)
}
`
	result := runStandardLibraryArgumentRule(t, input, "net-ip-bytes-equal")
	if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != 0 {
		t.Fatalf("conservative net-ip-bytes-equal result = %#v", result)
	}
}

func TestNetIPBytesEqualMetadataAndGoVersion(t *testing.T) {
	t.Parallel()

	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	metadata, found := registry.Metadata("net-ip-bytes-equal")
	if !found ||
		metadata.DefaultSeverity != rules.SeverityWarn ||
		!reflect.DeepEqual(metadata.Presets, []rules.Preset{rules.PresetCorrectness}) ||
		metadata.MinimumGoVersion != "1.25" ||
		metadata.Requirement != rules.RequireTypes ||
		!reflect.DeepEqual(metadata.NodeInterests, []rules.NodeKind{rules.NodeCallExpr}) ||
		metadata.RunOnGenerated ||
		metadata.RunDespiteTypeErrors ||
		len(metadata.Fixes) != 0 {
		t.Fatalf("net-ip-bytes-equal metadata = %#v, found = %v", metadata, found)
	}
	older, err := registry.ResolveOptions(
		rules.ResolveOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{
				"net-ip-bytes-equal": rules.SeverityWarn,
			},
			SourceGoVersion: "go1.24",
		},
	)
	if err != nil || len(older) != 0 {
		t.Fatalf("go1.24 net-ip-bytes-equal selection = %#v, %v", older, err)
	}
}

func TestNetIPBytesEqualHonorsSharedSourcePolicies(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/net-ip-comparison-policy\n\ngo 1.25.0\n",
	)
	writeFixture(
		t,
		filepath.Join(root, "suppressed.go"),
		`package sample
import (
	"bytes"
	"net"
)
func suppressed(first, second net.IP) bool {
	//glippy:ignore net-ip-bytes-equal -- wire representation comparison
	return bytes.Equal(first, second)
}
`,
	)
	writeFixture(
		t,
		filepath.Join(root, "generated.go"),
		`// Code generated by fixture. DO NOT EDIT.
package sample
import (
	"bytes"
	"net"
)
func generated(first, second net.IP) bool {
	return bytes.Equal(first, second)
}
`,
	)
	writeFixture(
		t,
		filepath.Join(root, "invalid", "invalid.go"),
		`package invalid
import (
	"bytes"
	"net"
)
func invalid(first, second net.IP) bool {
	var text string = 1
	_ = text
	return bytes.Equal(first, second)
}
`,
	)
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{
				"net-ip-bytes-equal": rules.SeverityWarn,
			},
			SourceGoVersion: "go1.25",
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"./..."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 3 || len(result.LoadDiagnostics) == 0 {
		t.Fatalf("net-ip-bytes-equal policy result = %#v", result)
	}
	for _, file := range result.Files {
		switch filepath.Base(file.Path) {
		case "suppressed.go":
			if len(file.Diagnostics) != 0 ||
				len(file.Suppressed) != 1 ||
				file.Suppressed[0].Diagnostic.RuleID != "net-ip-bytes-equal" {
				t.Fatalf("suppressed result = %#v", file)
			}
		case "generated.go", "invalid.go":
			if len(file.Diagnostics) != 0 || len(file.Suppressed) != 0 {
				t.Fatalf("excluded result = %#v", file)
			}
		default:
			t.Fatalf("unexpected policy path %q", file.Path)
		}
	}
}

func BenchmarkNetIPBytesEqual(b *testing.B) {
	root := b.TempDir()
	writeFixture(
		b,
		filepath.Join(root, "go.mod"),
		"module example.com/net-ip-comparison-benchmark\n\ngo 1.25.0\n",
	)
	var input strings.Builder
	input.WriteString("package sample\nimport (\n\t\"bytes\"\n\t\"net\"\n)\n")
	for index := range 100 {
		fmt.Fprintf(
			&input,
			"func compare%d(first, second net.IP) bool { return bytes.Equal(first, second) }\n",
			index,
		)
	}
	writeFixture(b, filepath.Join(root, "sample.go"), input.String())
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		b.Fatal(err)
	}
	b.ReportAllocs()
	b.ResetTimer()
	for range b.N {
		result, runErr := analysis.RunPackages(
			context.Background(),
			registry,
			analysis.RunOptions{
				Presets: []rules.Preset{},
				Overrides: map[string]rules.Severity{
					"net-ip-bytes-equal": rules.SeverityWarn,
				},
				SourceGoVersion: "go1.25",
			},
			analysis.PackageLoadOptions{
				Dir: root,
				Patterns: []string{"."},
				ModuleMode: analysis.ModuleReadonly,
			},
		)
		if runErr != nil {
			b.Fatal(runErr)
		}
		if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != 100 {
			b.Fatalf("net-ip-bytes-equal benchmark result = %#v", result)
		}
	}
}
