package rulecatalog_test

import (
	"context"
	"path/filepath"
	"reflect"
	"slices"
	"testing"

	"github.com/faustbrian/glippy/internal/analysis"
	"github.com/faustbrian/glippy/internal/rulecatalog"
	"github.com/faustbrian/glippy/internal/rules"
)

func TestPedanticCatalogHonorsSharedPolicies(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/pedanticpolicy\n\ngo 1.25.0\n",
	)
	writeFixture(
		t,
		filepath.Join(root, "suppressed.go"),
		`package sample

import "fmt"

type Named struct{}

func (n *Named) First() {}
func (n *Named) Second() {}
//glippy:ignore inconsistent-receiver-name -- retained terminology in an external example
func (named *Named) Third() {}

type Form struct{}

func (f *Form) First() {}
func (f *Form) Second() {}
//glippy:ignore mixed-receiver-type -- value receiver intentionally documents copying
func (f Form) Third() {}

func run(text string) string {
	//glippy:ignore unnecessary-conversion -- explicit boundary for an example
	_ = string(text)
	//glippy:ignore unnecessary-sprintf -- example demonstrates formatting syntax
	_ = fmt.Sprintf("%s", text)
	if text == "" {
		return ""
	//glippy:ignore redundant-else -- paired branches mirror a protocol document
	} else {
		return text
	}
}
`,
	)
	writeFixture(
		t,
		filepath.Join(root, "generated.go"),
		`// Code generated by fixture. DO NOT EDIT.
package sample
import "fmt"
type Generated struct{}
func (g Generated) First() {}
func (generated *Generated) Second() {}
func generated(text string) string { _ = string(text); _ = fmt.Sprintf("%s", text); if text == "" { return "" } else { return text } }
`,
	)
	writeFixture(
		t,
		filepath.Join(root, "invalid", "invalid.go"),
		`package invalid
import "fmt"
type State struct{}
func (s State) First() {}
func (state *State) Second() {}
func invalid(text string) string { _ = string(text); _ = fmt.Sprintf("%s", text); if text == "" { return "" } else { return text }; var value string = 1; _ = value; return text }
`,
	)

	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{rules.PresetPedantic},
			SourceGoVersion: "go1.25",
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"./..."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 3 || len(result.LoadDiagnostics) == 0 {
		t.Fatalf("pedantic policy result = %#v", result)
	}
	for _, file := range result.Files {
		switch filepath.Base(file.Path) {
		case "suppressed.go":
			if len(file.Diagnostics) != 0 || len(file.Suppressed) != 5 {
				t.Fatalf("suppressed pedantic result = %#v", file)
			}
			got := make([]string, len(file.Suppressed))
			for index, suppressed := range file.Suppressed {
				got[index] = suppressed.Diagnostic.RuleID
			}
			slices.Sort(got)
			want := []string{
				"inconsistent-receiver-name",
				"mixed-receiver-type",
				"redundant-else",
				"unnecessary-conversion",
				"unnecessary-sprintf",
			}
			if !reflect.DeepEqual(got, want) {
				t.Fatalf("suppressed pedantic rules = %q, want %q", got, want)
			}
		case "generated.go":
			if len(file.Diagnostics) != 0 || len(file.Suppressed) != 0 {
				t.Fatalf("generated pedantic result = %#v", file)
			}
		case "invalid.go":
			if len(file.Diagnostics) != 1 ||
				file.Diagnostics[0].RuleID != "redundant-else" ||
				len(file.Suppressed) != 0 {
				t.Fatalf("ill-typed pedantic result = %#v", file)
			}
		default:
			t.Fatalf("unexpected pedantic policy path %q", file.Path)
		}
	}

	selection, err := registry.ResolveOptions(
		rules.ResolveOptions{
			Presets: []rules.Preset{rules.PresetPedantic},
			SourceGoVersion: "go1.24",
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(selection) != 0 {
		t.Fatalf("pre-minimum pedantic selection = %#v", selection)
	}
}
