package rulecatalog_test

import (
	"context"
	"path/filepath"
	"reflect"
	"slices"
	"testing"

	"github.com/faustbrian/glippy/internal/analysis"
	"github.com/faustbrian/glippy/internal/rulecatalog"
	"github.com/faustbrian/glippy/internal/rules"
)

func TestPedanticCatalogHonorsSharedPolicies(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/pedanticpolicy\n\ngo 1.25.0\n",
	)
	writeFixture(
		t,
		filepath.Join(root, "suppressed.go"),
		`package sample

import (
	"bytes"
	"fmt"
	"strings"
	"time"
)

// Named demonstrates receiver naming.
type Named struct{}

// First uses the canonical receiver name.
func (n *Named) First() {}
// Second uses the canonical receiver name.
func (n *Named) Second() {}
// Third deliberately uses another receiver name.
//glippy:ignore inconsistent-receiver-name -- retained terminology in an external example
func (named *Named) Third() {}

// Form demonstrates receiver forms.
type Form struct{}

// First uses a pointer receiver.
func (f *Form) First() {}
// Second uses a pointer receiver.
func (f *Form) Second() {}
// Third deliberately uses a value receiver.
//glippy:ignore mixed-receiver-type -- value receiver intentionally documents copying
func (f Form) Third() {}

func run(text string) string {
	values := []string{text}
	other := "value"
	low, high := 1, 2
	var buffer bytes.Buffer
	//glippy:ignore redundant-type-declaration -- explicit type documents the example
	var explicit int = len(text)
	//glippy:ignore manual-min-max -- expanded comparison documents the example
	if low < high { low = high }
	//glippy:ignore empty-branch -- placeholder retained for the example
	if text == "placeholder" {}
	//glippy:ignore unnecessary-conversion -- explicit boundary for an example
	_ = string(text)
	//glippy:ignore unnecessary-sprintf -- example demonstrates formatting syntax
	_ = fmt.Sprintf("%s", text)
	if text == "" {
		return ""
	//glippy:ignore redundant-else -- paired branches mirror a protocol document
	} else {
		return text
	}
	//glippy:ignore needless-blank-identifier -- explicit values document the range arity
	for _, _ = range values {}
	//glippy:ignore redundant-closure -- wrapper preserves terminology in the example
	_ = func(value string) string { return strings.TrimSpace(value) }
	//glippy:ignore redundant-nil-check -- nil is documented separately in this example
	if values != nil && len(values) > 0 { /* condition example */ }
	//glippy:ignore time-since -- expanded form mirrors external documentation
	_ = time.Now().Sub(time.Time{})
	//glippy:ignore time-until -- expanded form mirrors external documentation
	_ = time.Time{}.Sub(time.Now())
	//glippy:ignore buffer-string-conversion -- conversion demonstrates the byte boundary
	_ = string(buffer.Bytes())
	//glippy:ignore unnecessary-format -- formatting API is the subject of the example
	_ = fmt.Sprintf("literal")
	//glippy:ignore inefficient-string-comparison -- normalization steps are shown explicitly
	_ = strings.ToLower(text) == strings.ToLower(other)
	return text + string(rune(explicit + low))
}
`,
	)
	writeFixture(
		t,
		filepath.Join(root, "generated.go"),
		`// Code generated by fixture. DO NOT EDIT.
package sample
import (
	"bytes"
	"fmt"
	"strings"
	"time"
)
type Generated struct{}
func (g Generated) First() {}
func (generated *Generated) Second() {}
func generated(text string) string {
	values := []string{text}
	low, high := 1, 2
	var buffer bytes.Buffer
	var explicit int = len(text)
	if low < high { low = high }
	if text == "placeholder" {}
	_ = string(text)
	_ = fmt.Sprintf("%s", text)
	if text == "" { return "" } else { return text }
	for _, _ = range values {}
	_ = func(value string) string { return strings.TrimSpace(value) }
	if values != nil && len(values) > 0 { /* condition example */ }
	_ = time.Now().Sub(time.Time{})
	_ = time.Time{}.Sub(time.Now())
	_ = string(buffer.Bytes())
	_ = fmt.Sprintf("literal")
	_ = strings.ToLower(text) == strings.ToLower("value")
	return text + string(rune(explicit + low))
}
`,
	)
	writeFixture(
		t,
		filepath.Join(root, "invalid", "invalid.go"),
		`package invalid
import (
	"bytes"
	"fmt"
	"strings"
	"time"
)
// State is an invalid fixture type.
type State struct{}
// First uses a value receiver.
func (s State) First() {}
// Second uses a pointer receiver.
func (state *State) Second() {}
func invalid(text string) string {
	values := []string{text}
	var buffer bytes.Buffer
	_ = string(text)
	_ = fmt.Sprintf("%s", text)
	if text == "" { return "" } else { return text }
	for _, _ = range values {}
	_ = func(value string) string { return strings.TrimSpace(value) }
	if values != nil && len(values) > 0 {}
	_ = time.Now().Sub(time.Time{})
	_ = time.Time{}.Sub(time.Now())
	_ = string(buffer.Bytes())
	_ = fmt.Sprintf("literal")
	_ = strings.ToLower(text) == strings.ToLower("value")
	var value string = 1
	_ = value
	return text
}
`,
	)

	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{rules.PresetPedantic},
			SourceGoVersion: "go1.25",
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"./..."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 3 || len(result.LoadDiagnostics) == 0 {
		t.Fatalf("pedantic policy result = %#v", result)
	}
	for _, file := range result.Files {
		switch filepath.Base(file.Path) {
		case "suppressed.go":
			if len(file.Diagnostics) != 0 || len(file.Suppressed) != 16 {
				t.Fatalf("suppressed pedantic result = %#v", file)
			}
			got := make([]string, len(file.Suppressed))
			for index, suppressed := range file.Suppressed {
				got[index] = suppressed.Diagnostic.RuleID
			}
			slices.Sort(got)
			want := []string{
				"buffer-string-conversion",
				"empty-branch",
				"inconsistent-receiver-name",
				"inefficient-string-comparison",
				"manual-min-max",
				"mixed-receiver-type",
				"needless-blank-identifier",
				"redundant-closure",
				"redundant-else",
				"redundant-nil-check",
				"redundant-type-declaration",
				"time-since",
				"time-until",
				"unnecessary-conversion",
				"unnecessary-format",
				"unnecessary-sprintf",
			}
			if !reflect.DeepEqual(got, want) {
				t.Fatalf("suppressed pedantic rules = %q, want %q", got, want)
			}
		case "generated.go":
			if len(file.Diagnostics) != 0 || len(file.Suppressed) != 0 {
				t.Fatalf("generated pedantic result = %#v", file)
			}
		case "invalid.go":
			if len(file.Diagnostics) != 2 ||
				file.Diagnostics[0].RuleID != "redundant-else" ||
				file.Diagnostics[1].RuleID != "empty-branch" ||
				len(file.Suppressed) != 0 {
				t.Fatalf("ill-typed pedantic result = %#v", file)
			}
		default:
			t.Fatalf("unexpected pedantic policy path %q", file.Path)
		}
	}

	selection, err := registry.ResolveOptions(
		rules.ResolveOptions{
			Presets: []rules.Preset{rules.PresetPedantic},
			SourceGoVersion: "go1.24",
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(selection) != 0 {
		t.Fatalf("pre-minimum pedantic selection = %#v", selection)
	}
}
