package rulecatalog_test

import (
	"context"
	"fmt"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/faustbrian/glippy/internal/analysis"
	"github.com/faustbrian/glippy/internal/rulecatalog"
	"github.com/faustbrian/glippy/internal/rules"
)

func TestInvalidRandomBoundCoversSupportedAPIs(t *testing.T) {
	t.Parallel()

	input := `package sample

import (
	"math/rand"
	randv2 "math/rand/v2"
)

func invalid(classic *rand.Rand, modern *randv2.Rand) {
	_ = rand.Intn(1)
	_ = rand.Int31n(1)
	_ = rand.Int63n(1)
	_ = classic.Intn(1)
	_ = classic.Int31n(1)
	_ = classic.Int63n(1)
	_ = randv2.IntN(1)
	_ = randv2.Int32N(1)
	_ = randv2.Int64N(1)
	_ = randv2.UintN(1)
	_ = randv2.Uint32N(1)
	_ = randv2.Uint64N(1)
	_ = randv2.N(1)
	_ = randv2.N[int](1)
	_ = modern.IntN(1)
	_ = modern.Int32N(1)
	_ = modern.Int64N(1)
	_ = modern.UintN(1)
	_ = modern.Uint32N(1)
	_ = modern.Uint64N(1)
}
`
	result := runInvalidRandomBound(t, input)
	if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != 20 {
		t.Fatalf("invalid-random-bound API result = %#v", result)
	}
	for index, diagnostic := range result.Files[0].Diagnostics {
		if diagnostic.RuleID != "invalid-random-bound" ||
			diagnostic.MessageKey != "constant-result" ||
			diagnostic.Message != "random call with bound 1 always returns zero" ||
			diagnostic.Range.Start < 0 ||
			diagnostic.Range.End > len(input) ||
			input[diagnostic.Range.Start:diagnostic.Range.End] != "1" ||
			len(diagnostic.Fixes) != 0 {
			t.Fatalf("diagnostic[%d] = %#v", index, diagnostic)
		}
	}
}

func TestInvalidRandomBoundReportsPanicsAndExcludesUnknownCalls(t *testing.T) {
	t.Parallel()

	input := `package sample

import (
	"math/rand"
	randv2 "math/rand/v2"
)

const one = 1

type localRand struct{}

func (localRand) Intn(int) int { return 0 }

func inspect(bound int, local localRand) {
	_ = rand.Intn(0)
	_ = rand.Intn(-1)
	_ = rand.Intn(one)
	_ = randv2.UintN(0)

	_ = rand.Intn(2)
	_ = rand.Intn(bound)
	_ = local.Intn(1)
	dynamic := rand.Intn
	_ = dynamic(1)
	modernDynamic := randv2.N[int]
	_ = modernDynamic(1)
}
`
	result := runInvalidRandomBound(t, input)
	if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != 4 {
		t.Fatalf("invalid-random-bound boundary result = %#v", result)
	}
	wantKeys := []string{"nonpositive", "nonpositive", "constant-result", "nonpositive"}
	wantText := []string{"0", "-1", "one", "0"}
	for index, diagnostic := range result.Files[0].Diagnostics {
		if diagnostic.RuleID != "invalid-random-bound" ||
			diagnostic.MessageKey != wantKeys[index] ||
			diagnostic.Range.Start < 0 ||
			diagnostic.Range.End > len(input) ||
			input[diagnostic.Range.Start:diagnostic.Range.End] != wantText[index] {
			t.Fatalf("diagnostic[%d] = %#v", index, diagnostic)
		}
	}
}

func TestInvalidRandomBoundMetadata(t *testing.T) {
	t.Parallel()

	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	metadata, found := registry.Metadata("invalid-random-bound")
	if !found ||
		metadata.DefaultSeverity != rules.SeverityWarn ||
		!reflect.DeepEqual(metadata.Presets, []rules.Preset{rules.PresetCorrectness}) ||
		metadata.MinimumGoVersion != "1.25" ||
		metadata.Requirement != rules.RequireTypes ||
		!reflect.DeepEqual(metadata.NodeInterests, []rules.NodeKind{rules.NodeCallExpr}) ||
		metadata.RunOnGenerated ||
		metadata.RunDespiteTypeErrors ||
		len(metadata.Fixes) != 0 {
		t.Fatalf("invalid-random-bound metadata = %#v, found = %v", metadata, found)
	}
}

func TestInvalidRandomBoundHonorsSharedSourcePolicies(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/random-bound-policy\n\ngo 1.25.0\n",
	)
	writeFixture(
		t,
		filepath.Join(root, "suppressed.go"),
		`package sample
import "math/rand"
func suppressed() int {
	//glippy:ignore invalid-random-bound -- deterministic compatibility path
	return rand.Intn(1)
}
`,
	)
	writeFixture(
		t,
		filepath.Join(root, "generated.go"),
		`// Code generated by fixture. DO NOT EDIT.
package sample
import "math/rand"
func generated() int { return rand.Intn(1) }
`,
	)
	writeFixture(
		t,
		filepath.Join(root, "invalid", "invalid.go"),
		`package invalid
import "math/rand"
func invalid() int {
	var text string = 1
	_ = text
	return rand.Intn(1)
}
`,
	)
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{
				"invalid-random-bound": rules.SeverityWarn,
			},
			SourceGoVersion: "go1.25",
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"./..."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 3 || len(result.LoadDiagnostics) == 0 {
		t.Fatalf("invalid-random-bound policy result = %#v", result)
	}
	for _, file := range result.Files {
		switch filepath.Base(file.Path) {
		case "suppressed.go":
			if len(file.Diagnostics) != 0 ||
				len(file.Suppressed) != 1 ||
				file.Suppressed[0].Diagnostic.RuleID != "invalid-random-bound" {
				t.Fatalf("suppressed result = %#v", file)
			}
		case "generated.go", "invalid.go":
			if len(file.Diagnostics) != 0 || len(file.Suppressed) != 0 {
				t.Fatalf("excluded result = %#v", file)
			}
		default:
			t.Fatalf("unexpected policy path %q", file.Path)
		}
	}
}

func runInvalidRandomBound(t *testing.T, input string) analysis.PackageResult {
	t.Helper()
	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/random-bound\n\ngo 1.25.0\n",
	)
	writeFixture(t, filepath.Join(root, "sample.go"), input)
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{
				"invalid-random-bound": rules.SeverityWarn,
			},
			SourceGoVersion: "go1.25",
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	return result
}

func BenchmarkInvalidRandomBound(b *testing.B) {
	root := b.TempDir()
	writeFixture(
		b,
		filepath.Join(root, "go.mod"),
		"module example.com/random-bound-benchmark\n\ngo 1.25.0\n",
	)
	var input strings.Builder
	input.WriteString("package sample\nimport \"math/rand\"\n")
	for index := range 100 {
		fmt.Fprintf(&input, "func random%d() int { return rand.Intn(1) }\n", index)
	}
	writeFixture(b, filepath.Join(root, "sample.go"), input.String())
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		b.Fatal(err)
	}
	b.ReportAllocs()
	b.ResetTimer()
	for range b.N {
		result, runErr := analysis.RunPackages(
			context.Background(),
			registry,
			analysis.RunOptions{
				Presets: []rules.Preset{},
				Overrides: map[string]rules.Severity{
					"invalid-random-bound": rules.SeverityWarn,
				},
				SourceGoVersion: "go1.25",
			},
			analysis.PackageLoadOptions{
				Dir: root,
				Patterns: []string{"."},
				ModuleMode: analysis.ModuleReadonly,
			},
		)
		if runErr != nil {
			b.Fatal(runErr)
		}
		if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != 100 {
			b.Fatalf("invalid-random-bound benchmark result = %#v", result)
		}
	}
}
