package rulecatalog_test

import (
	"context"
	"path/filepath"
	"reflect"
	"slices"
	"testing"

	"github.com/faustbrian/glippy/internal/analysis"
	"github.com/faustbrian/glippy/internal/rulecatalog"
	"github.com/faustbrian/glippy/internal/rules"
)

func TestResourceAndLockRulesHonorSharedPolicies(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/resourcelockpolicy\n\ngo 1.25.0\n",
	)
	writeFixture(
		t,
		filepath.Join(root, "suppressed.go"),
		`package sample
import ("os"; "sync"; "time")
func suppressed(mu *sync.Mutex) error {
	//glippy:ignore resource-not-closed -- process lifetime handle
	file, err := os.Open("input")
	if err != nil { return err }
	_ = file.Name()
	mu.Lock()
	//glippy:ignore lock-held-across-blocking-call -- deliberate serialized delay
	time.Sleep(time.Second)
	mu.Unlock()
	return nil
}
`,
	)
	writeFixture(
		t,
		filepath.Join(root, "generated.go"),
		`// Code generated by fixture. DO NOT EDIT.
package sample
import ("os"; "sync"; "time")
func generated(mu *sync.Mutex) { file, _ := os.Open("input"); _ = file.Name(); mu.Lock(); time.Sleep(time.Second) }
`,
	)
	writeFixture(
		t,
		filepath.Join(root, "invalid", "invalid.go"),
		`package invalid
import ("os"; "sync"; "time")
func invalid(mu *sync.Mutex) { file, _ := os.Open("input"); _ = file.Name(); mu.Lock(); time.Sleep(time.Second); var text string = 1; _ = text }
`,
	)
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	overrides := map[string]rules.Severity{
		"lock-held-across-blocking-call": rules.SeverityWarn,
		"resource-not-closed": rules.SeverityWarn,
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: overrides,
			SourceGoVersion: "go1.25",
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"./..."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 3 || len(result.LoadDiagnostics) == 0 {
		t.Fatalf("resource and lock policy result = %#v", result)
	}
	for _, file := range result.Files {
		switch filepath.Base(file.Path) {
		case "suppressed.go":
			if len(file.Diagnostics) != 0 || len(file.Suppressed) != 2 {
				t.Fatalf("suppressed result = %#v", file)
			}
			got := make([]string, len(file.Suppressed))
			for index, suppressed := range file.Suppressed {
				got[index] = suppressed.Diagnostic.RuleID
			}
			slices.Sort(got)
			want := []string{"lock-held-across-blocking-call", "resource-not-closed"}
			if !reflect.DeepEqual(got, want) {
				t.Fatalf("suppressed rules = %q, want %q", got, want)
			}
		case "generated.go", "invalid.go":
			if len(file.Diagnostics) != 0 || len(file.Suppressed) != 0 {
				t.Fatalf("excluded result = %#v", file)
			}
		default:
			t.Fatalf("unexpected file %q", file.Path)
		}
	}
	selection, err := registry.ResolveOptions(
		rules.ResolveOptions{
			Presets: []rules.Preset{},
			Overrides: overrides,
			SourceGoVersion: "go1.24",
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(selection) != 0 {
		t.Fatalf("pre-minimum selection = %#v", selection)
	}
}
