package rulecatalog_test

import (
	"context"
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"github.com/faustbrian/glippy/internal/analysis"
	"github.com/faustbrian/glippy/internal/rulecatalog"
	"github.com/faustbrian/glippy/internal/rules"
)

func TestRestrictionPolicyRulesMatchExactCalls(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/restrictions\n\ngo 1.26.0\n",
	)
	path := filepath.Join(root, "sample.go")
	writeFixture(
		t,
		path,
		`package sample

import (
	c "context"
	stdlog "log"
	system "os"
)

type lookalike struct{}

func (lookalike) Background() c.Context { return nil }
func (lookalike) TODO() c.Context { return nil }
func (lookalike) Exit(int) {}
func (lookalike) Fatal(...any) {}

func restricted() {
	panic("stop")
	system.Exit(1)
	stdlog.Fatal("stop")
	stdlog.Fatalf("%s", "stop")
	stdlog.Fatalln("stop")
	stdlog.Default().Fatal("stop")
	_ = c.Background()
	_ = c.TODO()
}

func allowed(value lookalike) {
	panic := func(any) {}
	panic("local")
	value.Exit(1)
	value.Fatal("local")
	_ = value.Background()
	_ = value.TODO()
}
`,
	)

	tests := []struct {
		id string
		want []string
	}{
		{id: "context-background", want: []string{"c.Background"}},
		{id: "context-todo", want: []string{"c.TODO"}},
		{id: "direct-panic", want: []string{"panic"}},
		{
			id: "process-exit",
			want: []string{
				"system.Exit",
				"stdlog.Fatal",
				"stdlog.Fatalf",
				"stdlog.Fatalln",
				"stdlog.Default().Fatal",
			},
		},
	}
	for _, test := range tests {
		test := test
		t.Run(
			test.id,
			func(t *testing.T) {
				t.Parallel()
				result := runRestrictionPolicyRules(t, root, false, test.id)
				if len(result.Files) != 1 ||
					len(result.Files[0].Diagnostics) != len(test.want) {
					t.Fatalf("%s diagnostics = %#v", test.id, result.Files)
				}
				content, err := os.ReadFile(path)
				if err != nil {
					t.Fatal(err)
				}
				for index, diagnostic := range result.Files[0].Diagnostics {
					if diagnostic.RuleID != test.id ||
						diagnostic.MessageKey == "" ||
						len(diagnostic.Fixes) != 0 ||
						string(
							content[diagnostic.
								Range.
								Start:diagnostic.Range.End],
						) !=
							test.want[index] {
						t.Fatalf(
							"%s diagnostic %d = %#v",
							test.id,
							index,
							diagnostic,
						)
					}
				}
			},
		)
	}
}

func TestRestrictionPolicyRulesHonorSuppressionAndFilePolicy(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/restrictionpolicy\n\ngo 1.26.0\n",
	)
	writeFixture(
		t,
		filepath.Join(root, "sample.go"),
		`package sample

import (
	"context"
	"log"
)

func run() {
	//glippy:ignore direct-panic -- this boundary deliberately aborts
	panic("stop")
	//glippy:ignore process-exit -- this command owns process termination
	log.Fatal("stop")
	//glippy:ignore context-background -- this process owns the root context
	_ = context.Background()
	//glippy:ignore context-todo -- the caller cannot provide a context yet
	_ = context.TODO()
}
`,
	)
	result := runRestrictionPolicyRules(
		t,
		root,
		false,
		"context-background",
		"context-todo",
		"direct-panic",
		"process-exit",
	)
	if len(result.Files) != 1 ||
		len(result.Files[0].Diagnostics) != 0 ||
		len(result.Files[0].Suppressed) != 4 {
		t.Fatalf("suppressed restriction result = %#v", result.Files)
	}

	testRoot := t.TempDir()
	writeFixture(
		t,
		filepath.Join(testRoot, "go.mod"),
		"module example.com/restrictiontests\n\ngo 1.26.0\n",
	)
	writeFixture(t, filepath.Join(testRoot, "sample.go"), "package sample\n")
	writeFixture(
		t,
		filepath.Join(testRoot, "sample_test.go"),
		`package sample

import (
	"context"
	"log"
	"testing"
)

func TestRestricted(t *testing.T) {
	panic("stop")
	log.Fatal("stop")
	_ = context.Background()
	_ = context.TODO()
}
`,
	)
	ruleIDs := []string{"context-background", "context-todo", "direct-panic", "process-exit"}
	withoutTests := runRestrictionPolicyRules(t, testRoot, false, ruleIDs...)
	if countPackageDiagnostics(withoutTests) != 0 {
		t.Fatalf("default test-file restriction result = %#v", withoutTests)
	}
	withTests := runRestrictionPolicyRules(t, testRoot, true, ruleIDs...)
	if countPackageDiagnostics(withTests) != 4 {
		t.Fatalf("included test-file restriction result = %#v", withTests)
	}

	generatedRoot := t.TempDir()
	writeFixture(
		t,
		filepath.Join(generatedRoot, "go.mod"),
		"module example.com/restrictiongenerated\n\ngo 1.26.0\n",
	)
	writeFixture(
		t,
		filepath.Join(generatedRoot, "sample.go"),
		"// Code generated by fixture. DO NOT EDIT.\npackage sample\nfunc run() { panic(\"stop\") }\n",
	)
	generated := runRestrictionPolicyRules(t, generatedRoot, false, "direct-panic")
	if countPackageDiagnostics(generated) != 0 {
		t.Fatalf("generated restriction result = %#v", generated)
	}

	illTypedRoot := t.TempDir()
	writeFixture(
		t,
		filepath.Join(illTypedRoot, "go.mod"),
		"module example.com/restrictioninvalid\n\ngo 1.26.0\n",
	)
	writeFixture(
		t,
		filepath.Join(illTypedRoot, "sample.go"),
		"package sample\nfunc run() { missing(); panic(\"stop\") }\n",
	)
	illTyped := runRestrictionPolicyRules(t, illTypedRoot, false, "direct-panic")
	if len(illTyped.LoadDiagnostics) == 0 || countPackageDiagnostics(illTyped) != 0 {
		t.Fatalf("ill-typed restriction result = %#v", illTyped)
	}
}

func TestRestrictionPolicyRuleMetadataRequiresExactOptIn(t *testing.T) {
	t.Parallel()

	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	if selection, resolveErr := registry.ResolveOptions(
		rules.ResolveOptions{
			Presets: []rules.Preset{rules.PresetRestriction},
			SourceGoVersion: "go1.26",
		},
	);
		resolveErr == nil || len(selection) != 0 {
		t.Fatalf("wholesale restriction result = %#v, err = %v", selection, resolveErr)
	}

	for _, id := range
		[]string{"context-background", "context-todo", "direct-panic", "process-exit"} {
		metadata, found := registry.Metadata(id)
		if !found ||
			metadata.DefaultSeverity != rules.SeverityWarn ||
			!reflect.DeepEqual(
				metadata.Presets,
				[]rules.Preset{rules.PresetRestriction},
			) ||
			metadata.MinimumGoVersion != "1.25" ||
			metadata.Requirement != rules.RequireTypes ||
			!reflect.DeepEqual(
				metadata.NodeInterests,
				[]rules.NodeKind{rules.NodeCallExpr},
			) ||
			metadata.RunOnGenerated ||
			metadata.RunDespiteTypeErrors ||
			len(metadata.Options) != 1 ||
			metadata.Options[0].Name != "include-tests" ||
			len(metadata.Fixes) != 0 ||
			len(metadata.Examples) == 0 ||
			len(metadata.KnownLimitations) == 0 {
			t.Fatalf("%s metadata = %#v, found = %v", id, metadata, found)
		}
		selection, resolveErr := registry.ResolveOptions(
			rules.ResolveOptions{
				Presets: []rules.Preset{},
				Overrides: map[string]rules.Severity{id: rules.SeverityWarn},
				SourceGoVersion: "go1.24",
			},
		)
		if resolveErr != nil || len(selection) != 0 {
			t.Fatalf(
				"old-version %s selection = %#v, err = %v",
				id,
				selection,
				resolveErr,
			)
		}
	}
}

func BenchmarkRestrictionPolicyRules(b *testing.B) {
	root := b.TempDir()
	writeFixture(
		b,
		filepath.Join(root, "go.mod"),
		"module example.com/restrictionbenchmark\n\ngo 1.26.0\n",
	)
	writeFixture(
		b,
		filepath.Join(root, "sample.go"),
		`package sample

import (
	"context"
	"log"
	"os"
)

func run() {
	panic("stop")
	os.Exit(1)
	log.Fatal("stop")
	_ = context.Background()
	_ = context.TODO()
}
`,
	)
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		b.Fatal(err)
	}
	ruleIDs := []string{"context-background", "context-todo", "direct-panic", "process-exit"}
	overrides := make(map[string]rules.Severity, len(ruleIDs))
	for _, id := range ruleIDs {
		overrides[id] = rules.SeverityWarn
	}
	benchmarkPackageRuns(
		b,
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: overrides,
			SourceGoVersion: "go1.26",
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			ModuleMode: analysis.ModuleReadonly,
		},
		5,
	)
}

func runRestrictionPolicyRules(
	t testing.TB,
	root string,
	includeTests bool,
	ruleIDs ...string,
) analysis.PackageResult {
	t.Helper()
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	overrides := make(map[string]rules.Severity, len(ruleIDs))
	options := make(map[string]rules.OptionSet, len(ruleIDs))
	for _, id := range ruleIDs {
		overrides[id] = rules.SeverityWarn
		options[id] = rules.NewOptionSet(
			map[string]rules.OptionValue{
				"include-tests": rules.BooleanOption(includeTests),
			},
		)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: overrides,
			RuleOptions: options,
			SourceGoVersion: "go1.26",
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			Tests: true,
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	return result
}
