package rulecatalog_test

import (
	"context"
	"path/filepath"
	"reflect"
	"slices"
	"strings"
	"testing"

	"github.com/faustbrian/glippy/internal/analysis"
	"github.com/faustbrian/glippy/internal/rulecatalog"
	"github.com/faustbrian/glippy/internal/rules"
)

func TestExpandedStandardLibraryRulesReportMisuse(t *testing.T) {
	t.Parallel()

	input := `package sample

import (
	"context"
	"errors"
	"time"
)

func contextUse(ctx context.Context) {}

type sampleError struct{}

func (*sampleError) Error() string { return "sample" }

func bad(err error) {
	contextUse(nil)
	time.Sleep(1)
	time.Parse("2006-02-01", "2026-08-13")
	var target error
	errors.As(err, target)
}

func good(ctx context.Context, err error) {
	contextUse(ctx)
	time.Sleep(time.Second)
	time.Parse("2006-01-02", "2026-08-13")
	var target *sampleError
	errors.As(err, &target)
}
`
	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/stdlibexpansion\n\ngo 1.25.0\n",
	)
	writeFixture(t, filepath.Join(root, "sample.go"), input)
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	overrides := map[string]rules.Severity{
		"errors-as-target": rules.SeverityWarn,
		"nil-context": rules.SeverityWarn,
		"time-duration-unit": rules.SeverityWarn,
		"time-layout": rules.SeverityWarn,
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: overrides,
			SourceGoVersion: "go1.25",
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	wantRules := []string{
		"nil-context",
		"time-duration-unit",
		"time-layout",
		"errors-as-target",
	}
	wantText := []string{"nil", "1", "2006-02-01", "errors.As(err, target)"}
	if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != len(wantRules) {
		t.Fatalf("expanded standard-library result = %#v", result)
	}
	searchFrom := 0
	for index, diagnostic := range result.Files[0].Diagnostics {
		relative := strings.Index(input[searchFrom:], wantText[index])
		if relative < 0 {
			t.Fatalf("missing diagnostic text %q", wantText[index])
		}
		start := searchFrom + relative
		wantFixes := 0
		if diagnostic.RuleID == "time-layout" {
			wantFixes = 1
		}
		if diagnostic.RuleID != wantRules[index] ||
			diagnostic.Range.Start != start ||
			diagnostic.Range.End != start + len(wantText[index]) ||
			len(diagnostic.Fixes) != wantFixes {
			t.Fatalf("diagnostic[%d] = %#v", index, diagnostic)
		}
		if diagnostic.RuleID == "time-layout" &&
			(diagnostic.Fixes[0].Safety != rules.FixSuggestion ||
				len(diagnostic.Fixes[0].Edits) != 1 ||
				diagnostic.Fixes[0].Edits[0].NewText != "2006-01-02") {
			t.Fatalf("time-layout fix = %#v", diagnostic.Fixes)
		}
		searchFrom = start + len(wantText[index])
	}
}

func TestDeprecatedIOUtilReportsExactMigrationAPIs(t *testing.T) {
	t.Parallel()

	input := `package sample

import (
	"io"
	legacy "io/ioutil"
	"os"
)

func migrate(path string, data []byte) ([]byte, error) {
	_, _ = io.ReadAll(nil)
	_, _ = os.ReadFile(path)
	_ = legacy.Discard
	_ = legacy.NopCloser(nil)
	_, _ = legacy.ReadAll(nil)
	_, _ = legacy.ReadDir(path)
	_, _ = legacy.ReadFile(path)
	_, _ = legacy.TempDir("", "sample")
	_, _ = legacy.TempFile("", "sample")
	return data, legacy.WriteFile(path, data, 0o600)
}

func suppressed(path string) {
	//glippy:ignore deprecated-ioutil -- migration is staged separately
	_, _ = legacy.ReadFile(path)
}
`
	root := t.TempDir()
	writeFixture(t, filepath.Join(root, "go.mod"), "module example.com/ioutil\n\ngo 1.25.0\n")
	writeFixture(t, filepath.Join(root, "sample.go"), input)
	dotInput := `package sample

import . "io/ioutil"

func migrateDot(path string) ([]byte, error) {
	return ReadFile(path)
}
`
	dotPath := filepath.Join(root, "dot.go")
	writeFixture(t, dotPath, dotInput)
	writeFixture(
		t,
		filepath.Join(root, "generated.go"),
		"// Code generated by fixture. DO NOT EDIT.\npackage sample\n\nimport legacy \"io/ioutil\"\n\nvar _ = legacy.Discard\n",
	)
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{
				"deprecated-ioutil": rules.SeverityWarn,
			},
			SourceGoVersion: "go1.25",
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 3 {
		t.Fatalf("deprecated ioutil result = %#v", result)
	}
	var sourceResult analysis.Result
	var dotResult analysis.Result
	for _, file := range result.Files {
		switch file.Path {
		case filepath.Join(root, "sample.go"):
			sourceResult = file
		case dotPath:
			dotResult = file
		default:
			if len(file.Diagnostics) != 0 || len(file.Suppressed) != 0 {
				t.Fatalf("generated deprecated ioutil result = %#v", file)
			}
		}
	}
	wantDotStart := strings.Index(dotInput, "ReadFile")
	if len(dotResult.Diagnostics) != 1 ||
		dotResult.Diagnostics[0].Range.Start != wantDotStart ||
		dotResult.Diagnostics[0].Range.End != wantDotStart + len("ReadFile") {
		t.Fatalf("dot-imported deprecated ioutil result = %#v", dotResult)
	}
	names := []string{
		"Discard",
		"NopCloser",
		"ReadAll",
		"ReadDir",
		"ReadFile",
		"TempDir",
		"TempFile",
		"WriteFile",
	}
	if len(sourceResult.Diagnostics) != len(names) || len(sourceResult.Suppressed) != 1 {
		t.Fatalf("deprecated ioutil source result = %#v", sourceResult)
	}
	for index, name := range names {
		diagnostic := sourceResult.Diagnostics[index]
		selector := "legacy." + name
		wantStart := strings.Index(input, selector)
		if diagnostic.RuleID != "deprecated-ioutil" ||
			diagnostic.Range.Start != wantStart ||
			diagnostic.Range.End != wantStart + len(selector) {
			t.Fatalf("deprecated ioutil %s diagnostic = %#v", name, diagnostic)
		}
	}
	metadata, found := registry.Metadata("deprecated-ioutil")
	if !found ||
		!reflect.DeepEqual(metadata.Presets, []rules.Preset{rules.PresetMigration}) ||
		metadata.Requirement != rules.RequireTypes ||
		!reflect.DeepEqual(metadata.NodeInterests, []rules.NodeKind{rules.NodeFile}) ||
		len(metadata.Fixes) != 0 {
		t.Fatalf("deprecated ioutil metadata = %#v", metadata)
	}
	preMinimum, err := registry.ResolveOptions(
		rules.ResolveOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{
				"deprecated-ioutil": rules.SeverityWarn,
			},
			SourceGoVersion: "go1.24",
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(preMinimum) != 0 {
		t.Fatalf("pre-minimum deprecated ioutil selection = %#v", preMinimum)
	}
}

func TestExpandedStandardLibraryMetadata(t *testing.T) {
	t.Parallel()

	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	want := map[string]struct {
		presets []rules.Preset
		interests []rules.NodeKind
	}{
		"errors-as-target": {
			[]rules.Preset{rules.PresetCorrectness},
			[]rules.NodeKind{rules.NodeFile},
		},
		"nil-context": {
			[]rules.Preset{rules.PresetCorrectness},
			[]rules.NodeKind{rules.NodeCallExpr},
		},
		"time-duration-unit": {
			[]rules.Preset{rules.PresetSuspicious},
			[]rules.NodeKind{rules.NodeCallExpr},
		},
		"time-layout": {
			[]rules.Preset{rules.PresetCorrectness},
			[]rules.NodeKind{rules.NodeFile},
		},
	}
	for id, expected := range want {
		metadata, found := registry.Metadata(id)
		wantFixes := 0
		if id == "time-layout" {
			wantFixes = 1
		}
		if !found ||
			metadata.DefaultSeverity != rules.SeverityWarn ||
			!reflect.DeepEqual(metadata.Presets, expected.presets) ||
			metadata.MinimumGoVersion != "1.25" ||
			metadata.Requirement != rules.RequireTypes ||
			!reflect.DeepEqual(metadata.NodeInterests, expected.interests) ||
			metadata.RunOnGenerated ||
			metadata.RunDespiteTypeErrors ||
			len(metadata.Fixes) != wantFixes {
			t.Fatalf("%s metadata = %#v, found = %v", id, metadata, found)
		}
		if id == "nil-context" &&
			(len(metadata.Options) != 1 ||
				metadata.Options[0].Name != "include-tests" ||
				metadata.Options[0].Kind != rules.OptionBoolean ||
				metadata.Options[0].Default == nil ||
				metadata.Options[0].Default.String() != "false") {
			t.Fatalf("nil-context options = %#v", metadata.Options)
		}
		if id == "time-layout" && metadata.Fixes[0].Safety != rules.FixSuggestion {
			t.Fatalf("time-layout fix metadata = %#v", metadata.Fixes)
		}
	}
}

func TestNilContextCanIncludeTestFiles(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/nilcontexttests\n\ngo 1.25.0\n",
	)
	writeFixture(
		t,
		filepath.Join(root, "sample.go"),
		"package sample\nimport \"context\"\nfunc accept(context.Context) {}\n",
	)
	writeFixture(
		t,
		filepath.Join(root, "sample_test.go"),
		"package sample\nimport \"testing\"\nfunc TestNil(t *testing.T) { accept(nil) }\n",
	)
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	run := func(includeTests bool) analysis.PackageResult {
		t.Helper()
		result, runErr := analysis.RunPackages(
			context.Background(),
			registry,
			analysis.RunOptions{
				Presets: []rules.Preset{},
				Overrides: map[string]rules.Severity{
					"nil-context": rules.SeverityWarn,
				},
				RuleOptions: map[string]rules.OptionSet{
					"nil-context": rules.NewOptionSet(
						map[string]rules.OptionValue{
							"include-tests": rules.BooleanOption(
								includeTests,
							),
						},
					),
				},
				SourceGoVersion: "go1.25",
			},
			analysis.PackageLoadOptions{
				Dir: root,
				Patterns: []string{"."},
				Tests: true,
				ModuleMode: analysis.ModuleReadonly,
			},
		)
		if runErr != nil {
			t.Fatal(runErr)
		}
		return result
	}
	withoutTests := run(false)
	if countPackageDiagnostics(withoutTests) != 0 {
		t.Fatalf("default nil-context test-file result = %#v", withoutTests)
	}
	withTests := run(true)
	if countPackageDiagnostics(withTests) != 1 {
		t.Fatalf("included nil-context test-file result = %#v", withTests)
	}
}

func TestNilContextAllowsSourceProvenOptionalPrivateParameters(t *testing.T) {
	t.Parallel()

	input := `package sample

import (
	"context"

	"example.com/nilcontextoptional/dep"
)

type optionalHolder struct{}

type optionalContract interface {
	optional(context.Context) context.Context
}

func (optionalHolder) optional(ctx context.Context) context.Context {
	if ctx != nil {
		_ = ctx.Err()
	}
	if ctx != nil {
		_ = ctx.Done()
	}
	return ctx
}

func ExportedOptional(ctx context.Context) context.Context {
	if ctx != nil {
		_ = ctx.Err()
	}
	return ctx
}

func acceptsNil(ctx context.Context) {
	if ctx == nil {
		return
	}
	_ = ctx.Err()
}

func rejectsNil(ctx context.Context) {
	if ctx == nil {
		panic("nil context")
	}
}

func rejectNil() { panic("nil context") }

func rejectsNilIndirectly(ctx context.Context) {
	if ctx == nil {
		rejectNil()
	}
}

func requiresContext(ctx context.Context) {
	_ = ctx.Err()
}

func run() {
	_ = (optionalHolder{}).optional(nil)
	_ = ExportedOptional(nil)
	acceptsNil(nil)
	rejectsNil(nil)
	rejectsNilIndirectly(nil)
	requiresContext(nil)
	var dynamic optionalContract = optionalHolder{}
	_ = dynamic.optional(nil)
	function := optionalHolder{}.optional
	_ = function(nil)
	_ = optionalHolder.optional(optionalHolder{}, nil)
	dep.Accept(nil)
}
`
	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/nilcontextoptional\n\ngo 1.25.0\n",
	)
	writeFixture(t, filepath.Join(root, "sample.go"), input)
	writeFixture(
		t,
		filepath.Join(root, "dep", "dep.go"),
		"package dep\n\nimport \"context\"\n\nfunc Accept(context.Context) {}\n",
	)
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{"nil-context": rules.SeverityWarn},
			SourceGoVersion: "go1.25",
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != 8 {
		t.Fatalf("nil-context optional result = %#v", result)
	}
	wantCalls := []string{
		"ExportedOptional(nil)",
		"rejectsNil(nil)",
		"rejectsNilIndirectly(nil)",
		"requiresContext(nil)",
		"dynamic.optional(nil)",
		"function(nil)",
		"optionalHolder.optional(optionalHolder{}, nil)",
		"dep.Accept(nil)",
	}
	for index, diagnostic := range result.Files[0].Diagnostics {
		wantStart := strings.Index(input, wantCalls[index]) +
			strings.Index(wantCalls[index], "nil")
		if diagnostic.RuleID != "nil-context" ||
			diagnostic.Range.Start != wantStart ||
			diagnostic.Range.End != wantStart + len("nil") {
			t.Fatalf("nil-context optional diagnostic[%d] = %#v", index, diagnostic)
		}
	}
}

func TestExpandedStandardLibraryNativeRulesCoverSupportedCalls(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		ruleID string
		input string
		wantText []string
	}{
		{
			name: "context positions and variadic arguments",
			ruleID: "nil-context",
			input: `package sample
import "context"
type localContext interface { Done() <-chan struct{} }
func accept(first int, ctx context.Context, rest ...context.Context) {}
func local(localContext) {}
func run() {
	accept(0, nil)
	accept(0, context.Background(), nil)
	local(nil)
}
`,
			wantText: []string{"nil", "nil"},
		},
		{
			name: "waiting and timer APIs",
			ruleID: "time-duration-unit",
			input: `package sample
import "time"
func run() {
	time.Sleep(1)
	time.After(1)
	time.NewTimer(1)
	time.NewTicker(1)
	time.Tick(1)
	time.AfterFunc(1, func() {})
	time.Sleep(0)
	time.Sleep(delay)
	time.Sleep(time.Duration(1))
	time.Sleep(1 * time.Nanosecond)
}
const delay = 1
`,
			wantText: []string{"1", "1", "1", "1", "1", "1"},
		},
		{
			name: "parse and format layouts",
			ruleID: "time-layout",
			input: `package sample
import "time"
func run(value string) {
	time.Parse("2006-02-01", value)
	time.Now().Format("2006-02-01")
}
`,
			wantText: []string{"2006-02-01", "2006-02-01"},
		},
	}
	for _, test := range tests {
		t.Run(
			test.name,
			func(t *testing.T) {
				t.Parallel()

				root := t.TempDir()
				writeFixture(
					t,
					filepath.Join(root, "go.mod"),
					"module example.com/stdlibsupportedcalls\n\ngo 1.25.0\n",
				)
				writeFixture(t, filepath.Join(root, "sample.go"), test.input)
				registry, err := rulecatalog.NewRegistry()
				if err != nil {
					t.Fatal(err)
				}
				result, err := analysis.RunPackages(
					context.Background(),
					registry,
					analysis.RunOptions{
						Presets: []rules.Preset{},
						Overrides: map[string]rules.Severity{
							test.ruleID: rules.SeverityWarn,
						},
						SourceGoVersion: "go1.25",
					},
					analysis.PackageLoadOptions{
						Dir: root,
						Patterns: []string{"."},
						ModuleMode: analysis.ModuleReadonly,
					},
				)
				if err != nil {
					t.Fatal(err)
				}
				if len(result.Files) != 1 ||
					len(result.Files[0].Diagnostics) != len(test.wantText) {
					t.Fatalf("%s result = %#v", test.ruleID, result)
				}
				searchFrom := 0
				for index, diagnostic := range result.Files[0].Diagnostics {
					relative := strings.Index(
						test.input[searchFrom:],
						test.wantText[index],
					)
					if relative < 0 {
						t.Fatalf(
							"missing diagnostic text %q",
							test.wantText[index],
						)
					}
					start := searchFrom + relative
					if diagnostic.RuleID != test.ruleID ||
						diagnostic.Range.Start != start ||
						diagnostic.Range.End !=
							start + len(test.wantText[index]) {
						t.Fatalf(
							"%s diagnostic[%d] = %#v",
							test.ruleID,
							index,
							diagnostic,
						)
					}
					searchFrom = start + len(test.wantText[index])
				}
			},
		)
	}
}

func TestExpandedStandardLibraryRulesHonorSharedPolicies(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/stdlibexpansionpolicy\n\ngo 1.25.0\n",
	)
	writeFixture(
		t,
		filepath.Join(root, "suppressed.go"),
		`package sample

import (
	"context"
	"errors"
	"net/http"
	"time"
)

func accept(context.Context) {}

func suppressed(err error, header http.Header) {
	//glippy:ignore nil-context -- compatibility call
	accept(nil)
	//glippy:ignore time-duration-unit -- measured nanosecond delay
	time.Sleep(1)
	//glippy:ignore time-layout -- legacy wire layout
	time.Parse("2006-02-01", "2026-08-13")
	var target error
	//glippy:ignore errors-as-target -- compatibility target
	errors.As(err, target)
	//glippy:ignore http-canonical-header-key -- upstream preserves raw casing
	_ = header["content-type"]
}
`,
	)
	writeFixture(
		t,
		filepath.Join(root, "generated.go"),
		`// Code generated by fixture. DO NOT EDIT.
package sample

import (
	"context"
	"errors"
	"net/http"
	"time"
)

func generatedAccept(context.Context) {}

func generated(err error, header http.Header) {
	generatedAccept(nil)
	time.Sleep(1)
	time.Parse("2006-02-01", "2026-08-13")
	var target error
	errors.As(err, target)
	_ = header["content-type"]
}
`,
	)
	writeFixture(
		t,
		filepath.Join(root, "invalid", "invalid.go"),
		`package invalid

import (
	"context"
	"errors"
	"net/http"
	"time"
)

func accept(context.Context) {}

func invalid(err error, header http.Header) {
	accept(nil)
	time.Sleep(1)
	time.Parse("2006-02-01", "2026-08-13")
	var target error
	errors.As(err, target)
	_ = header["content-type"]
	var text string = 1
	_ = text
}
`,
	)
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	overrides := map[string]rules.Severity{
		"errors-as-target": rules.SeverityWarn,
		"http-canonical-header-key": rules.SeverityWarn,
		"nil-context": rules.SeverityWarn,
		"time-duration-unit": rules.SeverityWarn,
		"time-layout": rules.SeverityWarn,
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: overrides,
			SourceGoVersion: "go1.25",
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"./..."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 3 || len(result.LoadDiagnostics) == 0 {
		t.Fatalf("expanded standard-library policy result = %#v", result)
	}
	for _, file := range result.Files {
		switch filepath.Base(file.Path) {
		case "suppressed.go":
			if len(file.Diagnostics) != 0 || len(file.Suppressed) != 5 {
				t.Fatalf("suppressed result = %#v", file)
			}
			got := make([]string, len(file.Suppressed))
			for index, suppressed := range file.Suppressed {
				got[index] = suppressed.Diagnostic.RuleID
			}
			slices.Sort(got)
			want := []string{
				"errors-as-target",
				"http-canonical-header-key",
				"nil-context",
				"time-duration-unit",
				"time-layout",
			}
			if !reflect.DeepEqual(got, want) {
				t.Fatalf("suppressed rules = %q, want %q", got, want)
			}
		case "generated.go", "invalid.go":
			if len(file.Diagnostics) != 0 || len(file.Suppressed) != 0 {
				t.Fatalf("excluded result = %#v", file)
			}
		default:
			t.Fatalf("unexpected policy path %q", file.Path)
		}
	}
	selection, err := registry.ResolveOptions(
		rules.ResolveOptions{
			Presets: []rules.Preset{},
			Overrides: overrides,
			SourceGoVersion: "go1.24",
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(selection) != 0 {
		t.Fatalf("pre-minimum selection = %#v", selection)
	}
}

func BenchmarkExpandedStandardLibraryPackageAnalysis(b *testing.B) {
	root := b.TempDir()
	writeFixture(
		b,
		filepath.Join(root, "go.mod"),
		"module example.com/stdlibexpansionbenchmark\n\ngo 1.25.0\n",
	)
	writeFixture(
		b,
		filepath.Join(root, "sample.go"),
		`package sample
import ("context"; "errors"; "io/ioutil"; "time")
func accept(context.Context) {}
func run(err error) { accept(nil); time.Sleep(1); time.Parse("2006-02-01", "2026-08-13"); var target error; errors.As(err, target); _ = ioutil.Discard }
`,
	)
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		b.Fatal(err)
	}
	for _, ruleID := range
		[]string{
			"deprecated-ioutil",
			"errors-as-target",
			"nil-context",
			"time-duration-unit",
			"time-layout",
		} {
		ruleID := ruleID
		b.Run(
			ruleID,
			func(b *testing.B) {
				benchmarkPackageRuns(
					b,
					registry,
					analysis.RunOptions{
						Presets: []rules.Preset{},
						Overrides: map[string]rules.Severity{
							ruleID: rules.SeverityWarn,
						},
						SourceGoVersion: "go1.25",
					},
					analysis.PackageLoadOptions{
						Dir: root,
						Patterns: []string{"."},
						ModuleMode: analysis.ModuleReadonly,
					},
					1,
				)
			},
		)
	}
}
