package rulecatalog_test

import (
	"context"
	"fmt"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/faustbrian/glippy/internal/analysis"
	"github.com/faustbrian/glippy/internal/rulecatalog"
	"github.com/faustbrian/glippy/internal/rules"
)

func TestTypedNilErrorReturnReportsDefinitelyNilConcreteErrors(t *testing.T) {
	t.Parallel()

	input := `package sample

type problem struct{}
func (*problem) Error() string { return "problem" }
func (*problem) Code() int { return 1 }

type problemList []string
func (problemList) Error() string { return "problems" }

type richError interface {
	error
	Code() int
}

func zeroValue() error {
	var zeroErr *problem
	return zeroErr
}

func explicitNil() error {
	return (*problem)(nil)
}

func richNil() richError {
	var richErr *problem
	return richErr
}

func nilSlice() error {
	var listErr problemList
	return listErr
}

func multipleResults() (int, error) {
	var resultErr *problem
	return 0, resultErr
}

func explicitInterfaceNil() error {
	return nil
}

func interfaceValue(err error) error {
	return err
}

func concreteValue(err *problem) error {
	return err
}

func nonNil() error {
	return &problem{}
}
`
	result := runTypedNilErrorReturn(t, input, nil)
	if len(result.Files[0].Diagnostics) != 5 {
		t.Fatalf("typed-nil-error-return result = %#v", result)
	}
	for index, marker := range
		[]string{
			"return zeroErr",
			"return (*problem)(nil)",
			"return richErr",
			"return listErr",
			"return 0, resultErr",
		} {
		diagnostic := result.Files[0].Diagnostics[index]
		expression := marker[strings.LastIndex(marker, " ") + 1:]
		wantStart := strings.Index(input, marker) + strings.LastIndex(marker, " ") + 1
		if diagnostic.RuleID != "typed-nil-error-return" ||
			diagnostic.MessageKey != "typed-nil-error-return" ||
			diagnostic.Range.Start != wantStart ||
			diagnostic.Range.End != wantStart + len(expression) {
			t.Fatalf("typed-nil-error-return diagnostic[%d] = %#v", index, diagnostic)
		}
	}
}

func TestTypedNilErrorReturnHandlesJoinsConservatively(t *testing.T) {
	t.Parallel()

	input := `package sample

type problem struct{}
func (*problem) Error() string { return "problem" }

func allNil(condition bool) error {
	var joinedErr *problem
	if condition {
		joinedErr = nil
	}
	return joinedErr
}

func maybeNonNil(condition bool) error {
	var err *problem
	if condition {
		err = &problem{}
	}
	return err
}
`
	result := runTypedNilErrorReturn(t, input, nil)
	if len(result.Files[0].Diagnostics) != 1 {
		t.Fatalf("typed-nil-error-return result = %#v", result)
	}
	diagnostic := result.Files[0].Diagnostics[0]
	wantStart := strings.Index(input, "return joinedErr") + len("return ")
	if diagnostic.RuleID != "typed-nil-error-return" ||
		diagnostic.MessageKey != "typed-nil-error-return" ||
		diagnostic.Range.Start != wantStart ||
		diagnostic.Range.End != wantStart + len("joinedErr") {
		t.Fatalf("typed-nil-error-return diagnostic = %#v", diagnostic)
	}
}

func TestTypedNilErrorReturnMetadata(t *testing.T) {
	t.Parallel()

	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	metadata, found := registry.Metadata("typed-nil-error-return")
	if !found ||
		metadata.DefaultSeverity != rules.SeverityWarn ||
		!reflect.DeepEqual(metadata.Presets, []rules.Preset{rules.PresetSuspicious}) ||
		metadata.MinimumGoVersion != "1.25" ||
		metadata.Requirement != rules.RequireSSA ||
		metadata.RunOnGenerated ||
		metadata.RunDespiteTypeErrors ||
		!reflect.DeepEqual(
			metadata.Categories,
			[]rules.Category{rules.CategoryCorrectness},
		) ||
		len(metadata.Fixes) != 0 ||
		len(metadata.Examples) == 0 ||
		len(metadata.KnownLimitations) == 0 {
		t.Fatalf("typed-nil-error-return metadata = %#v, found = %v", metadata, found)
	}
}

func TestTypedNilErrorReturnHonorsSharedPolicies(t *testing.T) {
	t.Parallel()

	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/typednilerrorreturnpolicy\n\ngo 1.25.0\n",
	)
	writeFixture(
		t,
		filepath.Join(root, "suppressed.go"),
		`package sample

type suppressedProblem struct{}
func (*suppressedProblem) Error() string { return "problem" }

func suppressed() error {
	var problem *suppressedProblem
	//glippy:ignore typed-nil-error-return -- compatibility requires the non-nil interface
	return problem
}
`,
	)
	writeFixture(
		t,
		filepath.Join(root, "generated.go"),
		`// Code generated by fixture. DO NOT EDIT.
package sample

type generatedProblem struct{}
func (*generatedProblem) Error() string { return "problem" }

func generated() error {
	var problem *generatedProblem
	return problem
}
`,
	)
	writeFixture(
		t,
		filepath.Join(root, "invalid", "invalid.go"),
		`package invalid

type problem struct{}
func (*problem) Error() string { return "problem" }

func invalid() error {
	var problem *problem
	var broken string = 1
	_ = broken
	return problem
}
`,
	)
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{
				"typed-nil-error-return": rules.SeverityError,
			},
			SourceGoVersion: "go1.25",
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"./..."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 3 || len(result.LoadDiagnostics) == 0 {
		t.Fatalf("typed-nil-error-return policy result = %#v", result)
	}
	for _, file := range result.Files {
		switch filepath.Base(file.Path) {
		case "suppressed.go":
			if len(file.Diagnostics) != 0 ||
				len(file.Suppressed) != 1 ||
				file.Suppressed[0].Diagnostic.RuleID != "typed-nil-error-return" ||
				file.Suppressed[0].Diagnostic.Severity != rules.SeverityError {
				t.Fatalf("suppressed typed-nil-error-return result = %#v", file)
			}
		case "generated.go", "invalid.go":
			if len(file.Diagnostics) != 0 || len(file.Suppressed) != 0 {
				t.Fatalf("excluded typed-nil-error-return result = %#v", file)
			}
		default:
			t.Fatalf("unexpected policy file %q", file.Path)
		}
	}
	selection, err := registry.ResolveOptions(
		rules.ResolveOptions{
			Presets: []rules.Preset{rules.PresetSuspicious},
			SourceGoVersion: "go1.24",
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	for _, selected := range selection {
		if selected.ID == "typed-nil-error-return" {
			t.Fatalf("pre-minimum typed-nil-error-return selection = %#v", selection)
		}
	}
}

func runTypedNilErrorReturn(
	t *testing.T,
	input string,
	overrides map[string]rules.Severity,
) analysis.PackageResult {
	t.Helper()
	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/typednilerrorreturn\n\ngo 1.25.0\n",
	)
	writeFixture(t, filepath.Join(root, "sample.go"), input)
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	if overrides == nil {
		overrides = map[string]rules.Severity{"typed-nil-error-return": rules.SeverityWarn}
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: overrides,
			SourceGoVersion: "go1.25",
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 1 || !strings.HasSuffix(result.Files[0].Path, "sample.go") {
		t.Fatalf("typed-nil-error-return result = %#v", result)
	}
	return result
}

func BenchmarkTypedNilErrorReturnPackageAnalysis(b *testing.B) {
	root := b.TempDir()
	writeFixture(
		b,
		filepath.Join(root, "go.mod"),
		"module example.com/typednilerrorreturnbenchmark\n\ngo 1.25.0\n",
	)
	var input strings.Builder
	input.WriteString(
		"package sample\ntype problem struct{}\nfunc (*problem) Error() string { return \"problem\" }\n",
	)
	for index := range 100 {
		fmt.Fprintf(
			&input,
			"func run%d() error { var problem *problem; return problem }\n",
			index,
		)
	}
	writeFixture(b, filepath.Join(root, "sample.go"), input.String())
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		b.Fatal(err)
	}
	benchmarkPackageRuns(
		b,
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{
				"typed-nil-error-return": rules.SeverityWarn,
			},
			SourceGoVersion: "go1.25",
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			ModuleMode: analysis.ModuleReadonly,
		},
		100,
	)
}
