package rulecatalog_test

import (
	"context"
	"fmt"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/faustbrian/glippy/internal/analysis"
	"github.com/faustbrian/glippy/internal/rulecatalog"
	"github.com/faustbrian/glippy/internal/rules"
	"github.com/faustbrian/glippy/internal/source"
)

func TestUncatchableSignalReportsUncatchableSignals(t *testing.T) {
	t.Parallel()

	input := `package sample

import (
	"context"
	"os"
	"os/signal"
	"syscall"
)

func run(ctx context.Context, channel chan<- os.Signal) {
	signal.Notify(channel, os.Kill, syscall.SIGKILL)
	_, _ = signal.NotifyContext(ctx, syscall.SIGSTOP)
	signal.Ignore(os.Signal(syscall.SIGKILL))
	signal.Reset(syscall.SIGSTOP)
	signal.Notify(channel, os.Interrupt)
	signal.Ignore(syscall.SIGTERM)
	signal.Reset()
}
`
	result := runUncatchableSignal(t, input, nil)
	want := []string{
		"os.Kill",
		"syscall.SIGKILL",
		"syscall.SIGSTOP",
		"os.Signal(syscall.SIGKILL)",
		"syscall.SIGSTOP",
	}
	if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != len(want) {
		t.Fatalf("result = %#v, want %d uncatchable-signal diagnostics", result, len(want))
	}
	searchStart := 0
	for index, expression := range want {
		offset := strings.Index(input[searchStart:], expression)
		if offset < 0 {
			t.Fatalf("input does not contain %q after %d", expression, searchStart)
		}
		offset += searchStart
		diagnostic := result.Files[0].Diagnostics[index]
		if diagnostic.RuleID != "uncatchable-signal" ||
			diagnostic.MessageKey != "uncatchable-signal" ||
			diagnostic.Message != "this signal cannot be caught or affected by os/signal" ||
			diagnostic.Help != "remove the uncatchable signal from this call" ||
			diagnostic.Range != (source.Range{Start: offset, End: offset + len(expression)}) ||
			len(diagnostic.Fixes) != 0 {
			t.Fatalf("diagnostic %d = %#v", index, diagnostic)
		}
		searchStart = offset + len(expression)
	}
}

func TestUncatchableSignalExcludesUnprovenAndCatchableSignals(t *testing.T) {
	t.Parallel()

	input := `package sample

import (
	"os"
	"os/signal"
	"syscall"
)

const localConstant = syscall.SIGKILL

func Notify(chan<- os.Signal, ...os.Signal) {}

func run(channel chan<- os.Signal) {
	localValue := syscall.SIGSTOP
	notify := signal.Notify
	signal.Notify(channel, os.Interrupt, syscall.SIGTERM)
	signal.Notify(channel, localConstant, localValue)
	signal.Notify(channel, syscall.Signal(9), os.Signal(9))
	notify(channel, syscall.SIGKILL)
	Notify(channel, syscall.SIGSTOP)
}
`
	result := runUncatchableSignal(t, input, nil)
	if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != 0 {
		t.Fatalf("result = %#v, want no diagnostics", result)
	}
}

func TestUncatchableSignalMetadata(t *testing.T) {
	t.Parallel()

	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	metadata, found := registry.Metadata("uncatchable-signal")
	if !found ||
		metadata.DefaultSeverity != rules.SeverityWarn ||
		!slices.Equal(metadata.Presets, []rules.Preset{rules.PresetCorrectness}) ||
		metadata.MinimumGoVersion != "1.25" ||
		metadata.Requirement != rules.RequireTypes ||
		!slices.Equal(metadata.NodeInterests, []rules.NodeKind{rules.NodeCallExpr}) ||
		metadata.RunOnGenerated ||
		metadata.RunDespiteTypeErrors ||
		!slices.Equal(
			metadata.Categories,
			[]rules.Category{rules.CategoryCorrectness, rules.CategorySafety},
		) ||
		len(metadata.Fixes) != 0 ||
		len(metadata.Examples) == 0 ||
		len(metadata.KnownLimitations) == 0 {
		t.Fatalf("uncatchable-signal metadata = %#v, found = %v", metadata, found)
	}
}

func TestUncatchableSignalHonorsSharedPolicies(t *testing.T) {
	t.Parallel()

	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/uncatchablesignalpolicy\n\ngo 1.25.0\n",
	)
	writeFixture(
		t,
		filepath.Join(root, "suppressed.go"),
		`package sample

import (
	"os/signal"
	"syscall"
)

func suppressed() {
	//glippy:ignore uncatchable-signal -- process supervisor owns shutdown
	signal.Reset(syscall.SIGSTOP)
}
`,
	)
	writeFixture(
		t,
		filepath.Join(root, "generated.go"),
		`// Code generated by fixture. DO NOT EDIT.
package sample

import (
	"os/signal"
	"syscall"
)

func generated() {
	signal.Ignore(syscall.SIGKILL)
}
`,
	)
	writeFixture(
		t,
		filepath.Join(root, "invalid", "invalid.go"),
		`package invalid

import (
	"os/signal"
	"syscall"
)

func invalid() {
	var broken string = 1
	_ = broken
	signal.Reset(syscall.SIGSTOP)
}
`,
	)
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{
				"uncatchable-signal": rules.SeverityError,
			},
			SourceGoVersion: "go1.25",
		},
		analysis.PackageLoadOptions{
			Dir:        root,
			Patterns:   []string{"./..."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 3 || len(result.LoadDiagnostics) == 0 {
		t.Fatalf("uncatchable-signal policy result = %#v", result)
	}
	for _, file := range result.Files {
		switch filepath.Base(file.Path) {
		case "suppressed.go":
			if len(file.Diagnostics) != 0 ||
				len(file.Suppressed) != 1 ||
				file.Suppressed[0].Diagnostic.RuleID != "uncatchable-signal" ||
				file.Suppressed[0].Diagnostic.Severity != rules.SeverityError {
				t.Fatalf("suppressed uncatchable-signal result = %#v", file)
			}
		case "generated.go", "invalid.go":
			if len(file.Diagnostics) != 0 || len(file.Suppressed) != 0 {
				t.Fatalf("excluded uncatchable-signal result = %#v", file)
			}
		default:
			t.Fatalf("unexpected policy file %q", file.Path)
		}
	}
	selection, err := registry.ResolveOptions(rules.ResolveOptions{
		Presets:         []rules.Preset{rules.PresetCorrectness},
		SourceGoVersion: "go1.24",
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, selected := range selection {
		if selected.ID == "uncatchable-signal" {
			t.Fatalf("pre-minimum uncatchable-signal selection = %#v", selection)
		}
	}
}

func runUncatchableSignal(
	t *testing.T,
	input string,
	overrides map[string]rules.Severity,
) analysis.PackageResult {
	t.Helper()
	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/uncatchablesignal\n\ngo 1.25.0\n",
	)
	writeFixture(t, filepath.Join(root, "sample.go"), input)
	if overrides == nil {
		overrides = map[string]rules.Severity{
			"uncatchable-signal": rules.SeverityWarn,
		}
	}
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets:         []rules.Preset{},
			Overrides:       overrides,
			SourceGoVersion: "go1.25",
		},
		analysis.PackageLoadOptions{
			Dir:        root,
			Patterns:   []string{"."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	return result
}

func BenchmarkUncatchableSignalPackageAnalysis(b *testing.B) {
	root := b.TempDir()
	writeFixture(
		b,
		filepath.Join(root, "go.mod"),
		"module example.com/uncatchablesignalbenchmark\n\ngo 1.25.0\n",
	)
	var input strings.Builder
	input.WriteString(
		"package sample\nimport (\"os/signal\"; \"syscall\")\n",
	)
	for index := range 100 {
		fmt.Fprintf(
			&input,
			"func run%d() { signal.Reset(syscall.SIGKILL) }\n",
			index,
		)
	}
	writeFixture(b, filepath.Join(root, "sample.go"), input.String())
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		b.Fatal(err)
	}
	benchmarkPackageRuns(
		b,
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{
				"uncatchable-signal": rules.SeverityWarn,
			},
			SourceGoVersion: "go1.25",
		},
		analysis.PackageLoadOptions{
			Dir:        root,
			Patterns:   []string{"."},
			ModuleMode: analysis.ModuleReadonly,
		},
		100,
	)
}
