package rulecatalog_test

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/faustbrian/glippy/internal/analysis"
	"github.com/faustbrian/glippy/internal/rulecatalog"
	"github.com/faustbrian/glippy/internal/rules"
)

func TestUncheckedScannerErrorRequiresObservationOnEveryNormalReturn(t *testing.T) {
	t.Parallel()

	input := `package sample

import "bufio"

func unchecked(scanner *bufio.Scanner) {
	for scanner.Scan() {}
}

func partial(scanner *bufio.Scanner, report bool) error {
	for scanner.Scan() {}
	if report {
		return scanner.Err()
	}
	return nil
}

func ignored(scanner *bufio.Scanner) {
	for scanner.Scan() {}
	_ = scanner.Err()
}

func expressionStatement(scanner *bufio.Scanner) {
	for scanner.Scan() {}
	scanner.Err()
}

func reassigned(scanner, other *bufio.Scanner) error {
	for scanner.Scan() {}
	scanner = other
	return scanner.Err()
}

func checked(scanner *bufio.Scanner) error {
	for scanner.Scan() {}
	return scanner.Err()
}

func checkedAfterOuterBranch(scanner *bufio.Scanner, iterate bool) error {
	if iterate {
		for scanner.Scan() {}
	}
	return scanner.Err()
}

func checkedCondition(scanner *bufio.Scanner) error {
	for scanner.Scan() {}
	if err := scanner.Err(); err != nil {
		return err
	}
	return nil
}

func noReturnPath(scanner *bufio.Scanner, fail bool) error {
	for scanner.Scan() {}
	if fail {
		panic("failed")
	}
	return scanner.Err()
}

func constantFalse(scanner *bufio.Scanner) {
	if false {
		for scanner.Scan() {}
	}
}

type localScanner struct{}
func (*localScanner) Scan() bool { return false }
func (*localScanner) Err() error { return nil }
func unrelated(scanner *localScanner) {
	for scanner.Scan() {}
}
`
	root := t.TempDir()
	writeFixture(t, filepath.Join(root, "go.mod"), "module example.com/scanner\n\ngo 1.26.0\n")
	path := filepath.Join(root, "scanner.go")
	writeFixture(t, path, input)
	result := runUncheckedScannerError(t, root, "go1.26", nil)
	if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != 5 {
		t.Fatalf("unchecked scanner diagnostics = %#v", result.Files)
	}
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	wantStarts := lifecycleDiagnosticStarts(
		t,
		input,
		"scanner.Scan()",
		"unchecked",
		"partial",
		"ignored",
		"expressionStatement",
		"reassigned",
	)
	for _, diagnostic := range result.Files[0].Diagnostics {
		if diagnostic.RuleID != "unchecked-scanner-error" ||
			string(content[diagnostic.Range.Start:diagnostic.Range.End]) !=
				"scanner.Scan()" ||
			!wantStarts[diagnostic.Range.Start] ||
			len(diagnostic.Fixes) != 0 {
			t.Fatalf("unchecked scanner diagnostic = %#v", diagnostic)
		}
		delete(wantStarts, diagnostic.Range.Start)
	}
	if len(wantStarts) != 0 {
		t.Fatalf("missing unchecked scanner diagnostics at %#v", wantStarts)
	}
}

func TestUncheckedScannerErrorUsesExactTypeIdentityAcrossHelperPackages(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(t, filepath.Join(root, "go.mod"), "module example.com/scanner\n\ngo 1.26.0\n")
	writeFixture(
		t,
		filepath.Join(root, "helper", "helper.go"),
		`package helper
import "bufio"
func Open() *bufio.Scanner { return nil }
`,
	)
	writeFixture(
		t,
		filepath.Join(root, "scanner.go"),
		`package sample
import "example.com/scanner/helper"
func run() {
	scanner := helper.Open()
	for scanner.Scan() {}
}
`,
	)
	result := runUncheckedScannerError(t, root, "go1.26", nil)
	if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != 1 {
		t.Fatalf("helper-returned scanner diagnostics = %#v", result.Files)
	}
}

func TestUncheckedScannerErrorHonorsSharedPolicyAndMetadata(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(t, filepath.Join(root, "go.mod"), "module example.com/scanner\n\ngo 1.26.0\n")
	writeFixture(
		t,
		filepath.Join(root, "scanner.go"),
		`package sample
import "bufio"
func run(scanner *bufio.Scanner) {
	//glippy:ignore unchecked-scanner-error -- best effort stream
	for scanner.Scan() {}
}
`,
	)
	suppressed := runUncheckedScannerError(t, root, "go1.26", nil)
	if len(suppressed.Files) != 1 ||
		len(suppressed.Files[0].Diagnostics) != 0 ||
		len(suppressed.Files[0].Suppressed) != 1 {
		t.Fatalf("suppressed result = %#v", suppressed)
	}

	generatedRoot := t.TempDir()
	writeFixture(
		t,
		filepath.Join(generatedRoot, "go.mod"),
		"module example.com/scannergenerated\n\ngo 1.26.0\n",
	)
	writeFixture(
		t,
		filepath.Join(generatedRoot, "scanner.go"),
		`// Code generated by fixture. DO NOT EDIT.
package sample
import "bufio"
func run(scanner *bufio.Scanner) { for scanner.Scan() {} }
`,
	)
	generated := runUncheckedScannerError(t, generatedRoot, "go1.26", nil)
	if len(generated.Files) != 1 || len(generated.Files[0].Diagnostics) != 0 {
		t.Fatalf("generated result = %#v", generated)
	}

	illTypedRoot := t.TempDir()
	writeFixture(
		t,
		filepath.Join(illTypedRoot, "go.mod"),
		"module example.com/scannerinvalid\n\ngo 1.26.0\n",
	)
	writeFixture(
		t,
		filepath.Join(illTypedRoot, "scanner.go"),
		`package sample
import "bufio"
func run(scanner *bufio.Scanner) { missing(); for scanner.Scan() {} }
`,
	)
	illTyped := runUncheckedScannerError(t, illTypedRoot, "go1.26", nil)
	if len(illTyped.LoadDiagnostics) == 0 ||
		len(illTyped.Files) != 1 ||
		len(illTyped.Files[0].Diagnostics) != 0 {
		t.Fatalf("ill-typed result = %#v", illTyped)
	}

	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	selection, err := registry.ResolveOptions(
		rules.ResolveOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{
				"unchecked-scanner-error": rules.SeverityWarn,
			},
			SourceGoVersion: "go1.24",
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(selection) != 0 {
		t.Fatalf("old-version selection = %#v", selection)
	}

	severityRoot := t.TempDir()
	writeFixture(
		t,
		filepath.Join(severityRoot, "go.mod"),
		"module example.com/scannerseverity\n\ngo 1.26.0\n",
	)
	writeFixture(
		t,
		filepath.Join(severityRoot, "scanner.go"),
		`package sample
import "bufio"
func run(scanner *bufio.Scanner) { for scanner.Scan() {} }
`,
	)
	severity := runUncheckedScannerError(
		t,
		severityRoot,
		"go1.26",
		map[string]rules.Severity{"unchecked-scanner-error": rules.SeverityError},
	)
	if len(severity.Files) != 1 ||
		len(severity.Files[0].Diagnostics) != 1 ||
		severity.Files[0].Diagnostics[0].Severity != rules.SeverityError {
		t.Fatalf("severity result = %#v", severity)
	}

	metadata, found := registry.Metadata("unchecked-scanner-error")
	if !found ||
		metadata.Requirement != rules.RequireControlFlow ||
		metadata.DefaultSeverity != rules.SeverityWarn ||
		metadata.MinimumGoVersion != "1.25" ||
		metadata.RunOnGenerated ||
		metadata.RunDespiteTypeErrors ||
		len(metadata.NodeInterests) != 0 ||
		len(metadata.Fixes) != 0 ||
		len(metadata.Presets) != 1 ||
		metadata.Presets[0] != rules.PresetSuspicious ||
		len(metadata.Examples) == 0 ||
		len(metadata.KnownLimitations) == 0 {
		t.Fatalf("metadata = %#v, found = %v", metadata, found)
	}
}

func BenchmarkUncheckedScannerErrorSharedCFG(b *testing.B) {
	var input strings.Builder
	input.WriteString("package sample\nimport \"bufio\"\n")
	for index := range 100 {
		input.WriteString("func run")
		input.WriteString(strings.Repeat("x", index + 1))
		input.WriteString(
			"(scanner *bufio.Scanner) error { for scanner.Scan() {} ; return scanner.Err() }\n",
		)
	}
	root := b.TempDir()
	writeFixture(
		b,
		filepath.Join(root, "go.mod"),
		"module example.com/scannerbench\n\ngo 1.26.0\n",
	)
	writeFixture(b, filepath.Join(root, "scanner.go"), input.String())
	for b.Loop() {
		result := runUncheckedScannerError(b, root, "go1.26", nil)
		if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != 0 {
			b.Fatalf("benchmark result = %#v", result)
		}
	}
}

func runUncheckedScannerError(
	t testing.TB,
	root string,
	goVersion string,
	overrides map[string]rules.Severity,
) analysis.PackageResult {
	t.Helper()
	if overrides == nil {
		overrides = map[string]rules.Severity{"unchecked-scanner-error": rules.SeverityWarn}
	}
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: overrides,
			SourceGoVersion: goVersion,
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	return result
}
