package rulecatalog_test

import (
	"context"
	"fmt"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/faustbrian/glippy/internal/analysis"
	"github.com/faustbrian/glippy/internal/rulecatalog"
	"github.com/faustbrian/glippy/internal/rules"
)

func TestZeroReplaceCountReportsExactStandardAPIs(t *testing.T) {
	t.Parallel()

	input := `package sample

import (
	bytepkg "bytes"
	textpkg "strings"
)

const zero = 0

type localText struct{}

func (localText) Replace(string, string, string, int) string { return "" }

func inspect(count int, local localText) {
	_ = textpkg.Replace("source", "old", "new", 0)
	_ = bytepkg.Replace([]byte("source"), []byte("old"), []byte("new"), zero)
	_ = textpkg.Replace("source", "old", "new", 1 - 1)

	_ = textpkg.Replace("source", "old", "new", 1)
	_ = bytepkg.Replace([]byte("source"), []byte("old"), []byte("new"), -1)
	_ = textpkg.Replace("source", "old", "new", count)
	_ = local.Replace("source", "old", "new", 0)
	dynamic := textpkg.Replace
	_ = dynamic("source", "old", "new", 0)
}
`
	result := runZeroReplaceCount(t, input)
	if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != 3 {
		t.Fatalf("zero-replace-count result = %#v", result)
	}
	wantText := []string{"0", "zero", "1 - 1"}
	for index, diagnostic := range result.Files[0].Diagnostics {
		if diagnostic.RuleID != "zero-replace-count" ||
			diagnostic.MessageKey != "zero-count" ||
			diagnostic.Message != "replacement count zero replaces no occurrences" ||
			diagnostic.Range.Start < 0 ||
			diagnostic.Range.End > len(input) ||
			input[diagnostic.Range.Start:diagnostic.Range.End] != wantText[index] ||
			len(diagnostic.Fixes) != 0 {
			t.Fatalf("diagnostic[%d] = %#v", index, diagnostic)
		}
	}
}

func TestZeroReplaceCountMetadata(t *testing.T) {
	t.Parallel()

	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	metadata, found := registry.Metadata("zero-replace-count")
	if !found ||
		metadata.DefaultSeverity != rules.SeverityWarn ||
		!reflect.DeepEqual(metadata.Presets, []rules.Preset{rules.PresetCorrectness}) ||
		metadata.MinimumGoVersion != "1.25" ||
		metadata.Requirement != rules.RequireTypes ||
		!reflect.DeepEqual(metadata.NodeInterests, []rules.NodeKind{rules.NodeCallExpr}) ||
		metadata.RunOnGenerated ||
		metadata.RunDespiteTypeErrors ||
		len(metadata.Fixes) != 0 {
		t.Fatalf("zero-replace-count metadata = %#v, found = %v", metadata, found)
	}
	older, err := registry.ResolveOptions(
		rules.ResolveOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{
				"zero-replace-count": rules.SeverityWarn,
			},
			SourceGoVersion: "go1.24",
		},
	)
	if err != nil || len(older) != 0 {
		t.Fatalf("go1.24 zero-replace-count selection = %#v, %v", older, err)
	}
}

func TestZeroReplaceCountHonorsSharedSourcePolicies(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/zero-replace-policy\n\ngo 1.25.0\n",
	)
	writeFixture(
		t,
		filepath.Join(root, "suppressed.go"),
		`package sample
import "strings"
func suppressed(path string) string {
	//glippy:ignore zero-replace-count -- compatibility fixture
	return strings.Replace(path, "\\", "/", 0)
}
`,
	)
	writeFixture(
		t,
		filepath.Join(root, "generated.go"),
		`// Code generated by fixture. DO NOT EDIT.
package sample
import "strings"
func generated(path string) string { return strings.Replace(path, "\\", "/", 0) }
`,
	)
	writeFixture(
		t,
		filepath.Join(root, "invalid", "invalid.go"),
		`package invalid
import "strings"
func invalid(path string) string {
	var text string = 1
	_ = text
	return strings.Replace(path, "\\", "/", 0)
}
`,
	)
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{
				"zero-replace-count": rules.SeverityWarn,
			},
			SourceGoVersion: "go1.25",
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"./..."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 3 || len(result.LoadDiagnostics) == 0 {
		t.Fatalf("zero-replace-count policy result = %#v", result)
	}
	for _, file := range result.Files {
		switch filepath.Base(file.Path) {
		case "suppressed.go":
			if len(file.Diagnostics) != 0 ||
				len(file.Suppressed) != 1 ||
				file.Suppressed[0].Diagnostic.RuleID != "zero-replace-count" {
				t.Fatalf("suppressed result = %#v", file)
			}
		case "generated.go", "invalid.go":
			if len(file.Diagnostics) != 0 || len(file.Suppressed) != 0 {
				t.Fatalf("excluded result = %#v", file)
			}
		default:
			t.Fatalf("unexpected policy path %q", file.Path)
		}
	}
}

func runZeroReplaceCount(t *testing.T, input string) analysis.PackageResult {
	t.Helper()
	root := t.TempDir()
	writeFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/zero-replace-count\n\ngo 1.25.0\n",
	)
	writeFixture(t, filepath.Join(root, "sample.go"), input)
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		t.Fatal(err)
	}
	result, err := analysis.RunPackages(
		context.Background(),
		registry,
		analysis.RunOptions{
			Presets: []rules.Preset{},
			Overrides: map[string]rules.Severity{
				"zero-replace-count": rules.SeverityWarn,
			},
			SourceGoVersion: "go1.25",
		},
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			ModuleMode: analysis.ModuleReadonly,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	return result
}

func BenchmarkZeroReplaceCount(b *testing.B) {
	root := b.TempDir()
	writeFixture(
		b,
		filepath.Join(root, "go.mod"),
		"module example.com/zero-replace-benchmark\n\ngo 1.25.0\n",
	)
	var input strings.Builder
	input.WriteString("package sample\nimport \"strings\"\n")
	for index := range 100 {
		fmt.Fprintf(
			&input,
			"func replace%d(value string) string { return strings.Replace(value, \"old\", \"new\", 0) }\n",
			index,
		)
	}
	writeFixture(b, filepath.Join(root, "sample.go"), input.String())
	registry, err := rulecatalog.NewRegistry()
	if err != nil {
		b.Fatal(err)
	}
	b.ReportAllocs()
	b.ResetTimer()
	for range b.N {
		result, runErr := analysis.RunPackages(
			context.Background(),
			registry,
			analysis.RunOptions{
				Presets: []rules.Preset{},
				Overrides: map[string]rules.Severity{
					"zero-replace-count": rules.SeverityWarn,
				},
				SourceGoVersion: "go1.25",
			},
			analysis.PackageLoadOptions{
				Dir: root,
				Patterns: []string{"."},
				ModuleMode: analysis.ModuleReadonly,
			},
		)
		if runErr != nil {
			b.Fatal(runErr)
		}
		if len(result.Files) != 1 || len(result.Files[0].Diagnostics) != 100 {
			b.Fatalf("zero-replace-count benchmark result = %#v", result)
		}
	}
}
