package source_test

import (
	"bytes"
	"slices"
	"strings"
	"testing"

	"github.com/faustbrian/gox/internal/source"
)

func TestLoadBuildsALosslessPhysicalSourceLedger(t *testing.T) {
	t.Parallel()

	input := []byte("\xef\xbb\xbf//go:build linux\r\n\r\npackage hostile\r\n\r\n//go:generate echo generated\r\nfunc run() { value := `first\rsecond`; value++ }\r\n")
	file, err := source.Load("./fixture.go", input)
	if err != nil {
		t.Fatal(err)
	}

	if got := file.Metadata(); !got.HasBOM || got.Newlines != source.NewlineCRLF || !got.FinalNewline {
		t.Fatalf("Metadata() = %#v, want BOM, CRLF, and final newline", got)
	}
	if got := reconstruct(file.Pieces()); !bytes.Equal(got, input) {
		t.Fatalf("physical ledger reconstructed %q, want exact input %q", got, input)
	}

	var explicit, inserted bool
	var rawLiteral string
	for _, item := range file.Tokens() {
		switch item.Semicolon {
		case source.SemicolonExplicit:
			explicit = true
		case source.SemicolonInserted:
			inserted = true
		}
		if item.Raw == "`first\rsecond`" {
			rawLiteral = item.Raw
		}
	}
	if !explicit || !inserted || rawLiteral == "" {
		t.Fatalf("token ledger lost semicolon origin or raw literal: explicit=%t inserted=%t raw=%q", explicit, inserted, rawLiteral)
	}

	wantDirectives := []source.DirectiveKind{source.DirectiveBuildConstraint, source.DirectiveGoGenerate}
	gotDirectives := make([]source.DirectiveKind, 0, len(file.Directives()))
	for _, directive := range file.Directives() {
		gotDirectives = append(gotDirectives, directive.Kind)
	}
	if !slices.Equal(gotDirectives, wantDirectives) {
		t.Fatalf("Directives() kinds = %v, want %v", gotDirectives, wantDirectives)
	}
}

func TestLoadKeepsPhysicalOffsetsWhenLineDirectivesAdjustDiagnostics(t *testing.T) {
	t.Parallel()

	input := []byte("//line generated.go:100\npackage physical\nvar value = 1\n")
	file, err := source.Load("physical.go", input)
	if err != nil {
		t.Fatal(err)
	}

	var packageToken source.Token
	for _, item := range file.Tokens() {
		if item.Raw == "package" {
			packageToken = item
			break
		}
	}
	if packageToken.Range.Start != bytes.Index(input, []byte("package")) {
		t.Fatalf("package physical offset = %d, want %d", packageToken.Range.Start, bytes.Index(input, []byte("package")))
	}
	directives := file.Directives()
	if len(directives) != 1 || directives[0].Kind != source.DirectiveLine {
		t.Fatalf("Directives() = %#v, want one line directive", directives)
	}
}

func TestLoadReturnsDiagnosticOnlyStateForInvalidSource(t *testing.T) {
	t.Parallel()

	input := []byte("package invalid\nfunc broken( {\n")
	file, err := source.Load("invalid.go", input)
	if err == nil {
		t.Fatal("Load() must report invalid Go")
	}
	if file == nil || file.CanFormat() {
		t.Fatalf("Load() file = %#v, want a diagnostic-only source unit", file)
	}
	if got := reconstruct(file.Pieces()); !bytes.Equal(got, input) {
		t.Fatalf("invalid-source ledger reconstructed %q, want %q", got, input)
	}
}

func TestLoadRejectsMalformedBuildConstraints(t *testing.T) {
	t.Parallel()

	input := []byte("// +build " + strings.Repeat("tag ", 102) + "\n\npackage invalid_constraint\n")
	file, err := source.Load("constraint.go", input)
	if err == nil {
		t.Fatal("Load() must reject a malformed build constraint")
	}
	if file == nil || file.CanFormat() {
		t.Fatalf("Load() file = %#v, want malformed constraint to be diagnostic-only", file)
	}
}

func TestSourceBytesAreReturnedByValue(t *testing.T) {
	t.Parallel()

	input := []byte("package immutable\n")
	file, err := source.Load("immutable.go", input)
	if err != nil {
		t.Fatal(err)
	}

	first := file.Bytes()
	first[0] = 'X'
	if got := file.Bytes(); !bytes.Equal(got, input) {
		t.Fatalf("Bytes() exposed mutable source storage: got %q, want %q", got, input)
	}
}

func TestLoadIndexesTriviaCommentsAndAnchoredDirectives(t *testing.T) {
	t.Parallel()

	input := []byte("\xef\xbb\xbf// Code generated by fixture. DO NOT EDIT.\npackage cgo_fixture\n\n/*\n#cgo CFLAGS: -DVALUE=1\n*/\nimport \"C\"\n")
	file, err := source.Load("cgo.go", input)
	if err != nil {
		t.Fatal(err)
	}

	trivia := file.Trivia()
	if len(trivia) == 0 || trivia[0].Kind != source.TriviaBOM || trivia[0].Raw != "\xef\xbb\xbf" {
		t.Fatalf("Trivia() = %#v, want a distinct leading BOM", trivia)
	}
	comments := file.Comments()
	if len(comments) != 2 || comments[0].Raw != "// Code generated by fixture. DO NOT EDIT." || comments[1].Raw != "/*\n#cgo CFLAGS: -DVALUE=1\n*/" {
		t.Fatalf("Comments() = %#v, want exact generated marker and cgo preamble", comments)
	}

	want := []source.DirectiveKind{source.DirectiveGenerated, source.DirectiveCgoPreamble}
	got := make([]source.DirectiveKind, 0, len(file.Directives()))
	for _, directive := range file.Directives() {
		got = append(got, directive.Kind)
	}
	if !slices.Equal(got, want) {
		t.Fatalf("Directives() kinds = %v, want %v", got, want)
	}
	if !file.Metadata().Generated {
		t.Fatal("Metadata().Generated must follow the generated-file marker")
	}
}

func reconstruct(pieces []source.Piece) []byte {
	var result []byte
	for _, piece := range pieces {
		result = append(result, piece.Raw...)
	}
	return result
}
