package analysis_test

import (
	"context"
	"errors"
	"fmt"
	"go/ast"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/faustbrian/glippy/internal/analysis"
	"github.com/faustbrian/glippy/internal/rules"
	"golang.org/x/tools/go/cfg"
)

type controlFlowRule struct {
	metadata rules.Metadata
	run func(*rules.ControlFlowContext) ([]rules.Finding, error)
}

type ambiguousControlFlowRule struct {
	controlFlowRule
}

func (r ambiguousControlFlowRule) RunTypes(*rules.TypesContext, ast.Node) ([]rules.Finding, error) {
	return nil, nil
}

func (r controlFlowRule) Metadata() rules.Metadata {
	return r.metadata
}

func (r controlFlowRule) RunControlFlow(ctx *rules.ControlFlowContext) ([]rules.Finding, error) {
	return r.run(ctx)
}

func TestRunControlFlowSharesGraphAndVisitsFunctionsCanonically(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeTypesFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/project\n\ngo 1.26.0\n",
	)
	path := filepath.Join(root, "project.go")
	writeTypesFixture(
		t,
		path,
		`package project

func outer(value bool) {
	if value { target() }
	_ = func() { target() }
}

func target() {}
`,
	)
	loaded, err := analysis.LoadPackages(
		context.Background(),
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			Requirement: rules.RequireControlFlow,
		},
	)
	if err != nil {
		t.Fatal(err)
	}

	graphs := make(map[int][]*cfg.CFG)
	var visits []string
	newRule := func(id string) controlFlowRule {
		return controlFlowRule{
			metadata: controlFlowMetadata(id),
			run: func(ctx *rules.ControlFlowContext) ([]rules.Finding, error) {
				if ctx.File().Path() != path ||
					ctx.PackageID() != "example.com/project" ||
					ctx.Package().Path() != "example.com/project" ||
					ctx.Info() == nil ||
					ctx.Body() == nil ||
					ctx.Graph() == nil ||
					ctx.IllTyped() {
					t.Fatalf("control-flow context = %#v", ctx)
				}
				range_, err := ctx.Range(ctx.Function())
				if err != nil {
					return nil, err
				}
				graphs[range_.Start] = append(graphs[range_.Start], ctx.Graph())
				visits = append(visits, id + ":" + functionKind(ctx.Function()))
				return []rules.Finding{
					{MessageKey: id, Message: id, Range: range_},
				}, nil
			},
		}
	}
	registry, err := rules.NewRegistry(newRule("z-cfg"), newRule("a-cfg"))
	if err != nil {
		t.Fatal(err)
	}
	selection, err := registry.Resolve(rules.PresetCorrectness, nil)
	if err != nil {
		t.Fatal(err)
	}
	diagnostics, err := analysis.RunControlFlow(
		context.Background(),
		loaded,
		registry,
		selection,
	)
	if err != nil {
		t.Fatal(err)
	}

	wantVisits := []string{
		"a-cfg:declaration",
		"z-cfg:declaration",
		"a-cfg:literal",
		"z-cfg:literal",
		"a-cfg:declaration",
		"z-cfg:declaration",
	}
	if !reflect.DeepEqual(visits, wantVisits) {
		t.Fatalf("control-flow visits = %#v, want %#v", visits, wantVisits)
	}
	if len(graphs) != 3 {
		t.Fatalf("control-flow graphs = %#v", graphs)
	}
	for start, functionGraphs := range graphs {
		if len(functionGraphs) != 2 || functionGraphs[0] != functionGraphs[1] {
			t.Fatalf("function at %d received graphs %#v", start, functionGraphs)
		}
	}
	if len(diagnostics) != 6 {
		t.Fatalf("RunControlFlow() diagnostics = %#v", diagnostics)
	}
	physical, found := loaded.Sources.Lookup(path)
	if !found {
		t.Fatal("control-flow source was not retained")
	}
	for index, diagnostic := range diagnostics {
		if diagnostic.Path != path ||
			diagnostic.RuleID !=
				[]string{
					"a-cfg",
					"z-cfg",
					"a-cfg",
					"z-cfg",
					"a-cfg",
					"z-cfg",
				}[index] {
			t.Fatalf("RunControlFlow()[%d] = %#v", index, diagnostic)
		}
		text, valid := physical.Slice(diagnostic.Range)
		if !valid || !strings.HasPrefix(text, "func") {
			t.Fatalf("RunControlFlow()[%d] physical range = %q, %t", index, text, valid)
		}
	}
}

func TestRunControlFlowHonorsGeneratedAndTypeErrorEligibility(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		source string
		metadata func(*rules.Metadata)
	}{
		{
			name: "generated file",
			source: "// Code generated by test. DO NOT EDIT.\npackage project\nfunc run() {}\n",
			metadata: func(metadata *rules.Metadata) {
				metadata.RunOnGenerated = true
			},
		},
		{
			name: "ill-typed package",
			source: "package project\nfunc run() { _ = missing }\n",
			metadata: func(metadata *rules.Metadata) {
				metadata.RunDespiteTypeErrors = true
			},
		},
	}
	for _, test := range tests {
		t.Run(
			test.name,
			func(t *testing.T) {
				t.Parallel()
				root := t.TempDir()
				writeTypesFixture(
					t,
					filepath.Join(root, "go.mod"),
					"module example.com/project\n\ngo 1.26.0\n",
				)
				path := filepath.Join(root, "project.go")
				writeTypesFixture(t, path, test.source)
				loaded, err := analysis.LoadPackages(
					context.Background(),
					analysis.PackageLoadOptions{
						Dir: root,
						Patterns: []string{"."},
						Requirement: rules.RequireControlFlow,
					},
				)
				if err != nil {
					t.Fatal(err)
				}
				newRule := func(id string, eligible bool) controlFlowRule {
					metadata := controlFlowMetadata(id)
					if eligible {
						test.metadata(&metadata)
					}
					return controlFlowRule{
						metadata: metadata,
						run: func(
							ctx *rules.ControlFlowContext,
						) ([]rules.Finding, error) {
							range_, err := ctx.Range(ctx.Function())
							if err != nil {
								return nil, err
							}
							return []rules.Finding{
								{
									MessageKey: id,
									Message: id,
									Range: range_,
								},
							}, nil
						},
					}
				}
				registry, err := rules.NewRegistry(
					newRule("eligible", true),
					newRule("ineligible", false),
				)
				if err != nil {
					t.Fatal(err)
				}
				selection, err := registry.Resolve(rules.PresetCorrectness, nil)
				if err != nil {
					t.Fatal(err)
				}
				diagnostics, err := analysis.RunControlFlow(
					context.Background(),
					loaded,
					registry,
					selection,
				)
				if err != nil {
					t.Fatal(err)
				}
				if len(diagnostics) != 1 ||
					diagnostics[0].RuleID != "eligible" ||
					diagnostics[0].Path != path {
					t.Fatalf("RunControlFlow() eligibility = %#v", diagnostics)
				}
			},
		)
	}
}

func TestRunControlFlowUsesConservativeBuiltinPanicPolicy(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeTypesFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/project\n\ngo 1.26.0\n",
	)
	writeTypesFixture(
		t,
		filepath.Join(root, "project.go"),
		`package project

func builtin() {
	panic("stop")
	target()
}

func parenthesized() {
	(panic)("stop")
	target()
}

func shadowed() {
	panic := func(string) {}
	panic("continue")
	target()
}

func target() {}
`,
	)
	loaded, err := analysis.LoadPackages(
		context.Background(),
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			Requirement: rules.RequireControlFlow,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	reachability := make(map[string]bool)
	rule := controlFlowRule{
		metadata: controlFlowMetadata("panic-policy"),
		run: func(ctx *rules.ControlFlowContext) ([]rules.Finding, error) {
			declaration, ok := ctx.Function().(*ast.FuncDecl)
			if !ok {
				return nil, nil
			}
			for _, block := range ctx.Graph().Blocks {
				if !block.Live {
					continue
				}
				for _, node := range block.Nodes {
					statement, ok := node.(*ast.ExprStmt)
					if !ok {
						continue
					}
					call, ok := statement.X.(*ast.CallExpr)
					if !ok {
						continue
					}
					identifier, named := call.Fun.(*ast.Ident)
					if named && identifier.Name == "target" {
						reachability[declaration.Name.Name] = true
					}
				}
			}
			return nil, nil
		},
	}
	registry, err := rules.NewRegistry(rule)
	if err != nil {
		t.Fatal(err)
	}
	selection, err := registry.Resolve(rules.PresetCorrectness, nil)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := analysis.RunControlFlow(context.Background(), loaded, registry, selection);
		err != nil {
		t.Fatal(err)
	}
	if reachability["builtin"] || reachability["parenthesized"] || !reachability["shadowed"] {
		t.Fatalf("target reachability = %#v", reachability)
	}
}

func TestRunControlFlowUsesPackageNoReturnSummaries(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeTypesFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/project\n\ngo 1.26.0\n",
	)
	writeTypesFixture(
		t,
		filepath.Join(root, "project.go"),
		`package project

func caller() {
	wrapper()
	target()
}

func wrapper() { stop() }
func stop() { panic("stop") }

func direct() {
	(stop)()
	target()
}

func dynamic(callback func()) {
	callback()
	target()
}

type stopper struct{}

func (stopper) stop() { panic("stop") }

func method() {
	(stopper{}).stop()
	target()
}

func recursiveA() {
	recursiveB()
	target()
}

func recursiveB() { recursiveA() }

func target() {}
`,
	)
	loaded, err := analysis.LoadPackages(
		context.Background(),
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			Requirement: rules.RequireControlFlow,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	reachability := make(map[string]bool)
	rule := controlFlowRule{
		metadata: controlFlowMetadata("package-no-return"),
		run: func(ctx *rules.ControlFlowContext) ([]rules.Finding, error) {
			declaration, ok := ctx.Function().(*ast.FuncDecl)
			if !ok {
				return nil, nil
			}
			for _, block := range ctx.Graph().Blocks {
				if !block.Live {
					continue
				}
				for _, node := range block.Nodes {
					statement, ok := node.(*ast.ExprStmt)
					if !ok {
						continue
					}
					call, ok := statement.X.(*ast.CallExpr)
					if !ok {
						continue
					}
					identifier, named := call.Fun.(*ast.Ident)
					if named && identifier.Name == "target" {
						reachability[declaration.Name.Name] = true
					}
				}
			}
			return nil, nil
		},
	}
	registry, err := rules.NewRegistry(rule)
	if err != nil {
		t.Fatal(err)
	}
	selection, err := registry.Resolve(rules.PresetCorrectness, nil)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := analysis.RunControlFlow(context.Background(), loaded, registry, selection);
		err != nil {
		t.Fatal(err)
	}
	if reachability["caller"] ||
		reachability["direct"] ||
		reachability["method"] ||
		!reachability["dynamic"] ||
		!reachability["recursiveA"] {
		t.Fatalf("target reachability = %#v", reachability)
	}
}

func TestRunControlFlowExposesPackageParameterEffects(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeTypesFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/project\n\ngo 1.26.0\n",
	)
	writeTypesFixture(
		t,
		filepath.Join(root, "project.go"),
		`package project

type closer interface { Close() error }

func borrow(value closer) {}
func borrowAll(values ...closer) {}
func borrowSecond(value closer) { borrowAll(nil, value) }
func closeFirst(values ...closer) { _ = values[0].Close() }
func close(value closer) { _ = value.Close() }

func inspect(value closer) {
	borrow(value)
	borrowAll(value, value)
	borrowSecond(value)
	closeFirst(value, value)
	close(value)
}
`,
	)
	loaded, err := analysis.LoadPackages(
		context.Background(),
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			Requirement: rules.RequireControlFlow,
			LoadEffectFacts: true,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	summaries := make(map[string]rules.ParameterEffectSummary)
	metadata := controlFlowMetadata("package-parameter-effects")
	metadata.RequiresEffectFacts = true
	rule := controlFlowRule{
		metadata: metadata,
		run: func(ctx *rules.ControlFlowContext) ([]rules.Finding, error) {
			declaration, ok := ctx.Function().(*ast.FuncDecl)
			if !ok || declaration.Name.Name != "inspect" {
				return nil, nil
			}
			ast.Inspect(
				declaration.Body,
				func(node ast.Node) bool {
					call, ok := node.(*ast.CallExpr)
					if !ok {
						return true
					}
					identifier, _ := call.Fun.(*ast.Ident)
					if identifier != nil {
						summaries[identifier.Name] = ctx.ParameterEffect(
							call,
							0,
						)
						if identifier.Name == "borrowAll" {
							summaries["borrowAllSecond"] = ctx.ParameterEffect(
								call,
								1,
							)
						}
						if identifier.Name == "closeFirst" {
							summaries["closeFirstSecond"] = ctx.ParameterEffect(
								call,
								1,
							)
						}
					}
					return true
				},
			)
			return nil, nil
		},
	}
	registry, err := rules.NewRegistry(rule)
	if err != nil {
		t.Fatal(err)
	}
	selection, err := registry.Resolve(rules.PresetCorrectness, nil)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := analysis.RunControlFlow(context.Background(), loaded, registry, selection);
		err != nil {
		t.Fatal(err)
	}
	if borrow := summaries["borrow"]; !borrow.Known || borrow.Always {
		t.Fatalf("borrow summary = %#v", borrow)
	}
	if close := summaries["close"]; !close.GuaranteesAny(rules.ParameterEffectClose) {
		t.Fatalf("close summary = %#v", close)
	}
	if second := summaries["borrowAllSecond"]; !second.Known || second.Always {
		t.Fatalf("variadic borrow summary = %#v", second)
	}
	if second := summaries["borrowSecond"]; !second.Known || second.Always {
		t.Fatalf("propagated variadic borrow summary = %#v", second)
	}
	if second := summaries["closeFirstSecond"]; second.Known {
		t.Fatalf("indexed variadic effect summary = %#v", second)
	}
}

func TestRunControlFlowDoesNotBuildParameterEffectsWithoutRequirement(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeTypesFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/project\n\ngo 1.26.0\n",
	)
	writeTypesFixture(
		t,
		filepath.Join(root, "project.go"),
		`package project

type closer interface { Close() error }

func close(value closer) { _ = value.Close() }
func inspect(value closer) { close(value) }
`,
	)
	loaded, err := analysis.LoadPackages(
		context.Background(),
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			Requirement: rules.RequireControlFlow,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	var summary rules.ParameterEffectSummary
	rule := controlFlowRule{
		metadata: controlFlowMetadata("no-parameter-effects"),
		run: func(ctx *rules.ControlFlowContext) ([]rules.Finding, error) {
			declaration, ok := ctx.Function().(*ast.FuncDecl)
			if !ok || declaration.Name.Name != "inspect" {
				return nil, nil
			}
			statement, _ := declaration.Body.List[0].(*ast.ExprStmt)
			call, _ := statement.X.(*ast.CallExpr)
			summary = ctx.ParameterEffect(call, 0)
			return nil, nil
		},
	}
	registry, err := rules.NewRegistry(rule)
	if err != nil {
		t.Fatal(err)
	}
	selection, err := registry.Resolve(rules.PresetCorrectness, nil)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := analysis.RunControlFlow(context.Background(), loaded, registry, selection);
		err != nil {
		t.Fatal(err)
	}
	if summary.Known {
		t.Fatalf("parameter effect was built without a declared requirement: %#v", summary)
	}
}

func TestRunControlFlowUsesAuthoritativeNoReturnFunctions(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeTypesFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/project\n\ngo 1.26.0\n",
	)
	writeTypesFixture(
		t,
		filepath.Join(root, "project.go"),
		`package project

import (
	"log"
	stdos "os"
	"runtime"
	"syscall"
	"testing"
)

func osExit() { stdos.Exit(1); target() }
func runtimeGoexit() { runtime.Goexit(); target() }
func syscallExit() { syscall.Exit(1); target() }
func logFatal() { log.Fatal("stop"); target() }
func logFatalf() { log.Fatalf("%s", "stop"); target() }
func logFatalln() { log.Fatalln("stop"); target() }
func logPanic() { log.Panic("stop"); target() }
func logPanicf() { log.Panicf("%s", "stop"); target() }
func logPanicln() { log.Panicln("stop"); target() }
func loggerFatal(logger *log.Logger) { logger.Fatal("stop"); target() }
func loggerFatalf(logger *log.Logger) { logger.Fatalf("%s", "stop"); target() }
func loggerFatalln(logger *log.Logger) { logger.Fatalln("stop"); target() }
func loggerPanic(logger *log.Logger) { logger.Panic("stop"); target() }
func loggerPanicf(logger *log.Logger) { logger.Panicf("%s", "stop"); target() }
func loggerPanicln(logger *log.Logger) { logger.Panicln("stop"); target() }
func testFailNow(t *testing.T) { t.FailNow(); target() }
func testFatal(t *testing.T) { t.Fatal("stop"); target() }
func testFatalf(t *testing.T) { t.Fatalf("%s", "stop"); target() }
func testSkipNow(t *testing.T) { t.SkipNow(); target() }
func testSkip(t *testing.T) { t.Skip("stop"); target() }
func testSkipf(t *testing.T) { t.Skipf("%s", "stop"); target() }

func launched() { go runtime.Goexit(); target() }
func deferred() { defer stdos.Exit(1); target() }
func dynamic(exit func(int)) { exit(1); target() }
func lookalike() { Exit(1); target() }
func logPrint() { log.Print("continue"); target() }
func testError(t *testing.T) { t.Error("continue"); target() }

func Exit(int) {}
func target() {}
`,
	)
	loaded, err := analysis.LoadPackages(
		context.Background(),
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			Requirement: rules.RequireControlFlow,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	if paths := loaded.Sources.Paths(); len(paths) != 1 {
		t.Fatalf("authoritative no-return retained dependency syntax: %q", paths)
	}
	reachability := make(map[string]bool)
	rule := controlFlowRule{
		metadata: controlFlowMetadata("authoritative-no-return"),
		run: func(ctx *rules.ControlFlowContext) ([]rules.Finding, error) {
			declaration, ok := ctx.Function().(*ast.FuncDecl)
			if !ok {
				return nil, nil
			}
			for _, block := range ctx.Graph().Blocks {
				if !block.Live {
					continue
				}
				for _, node := range block.Nodes {
					statement, ok := node.(*ast.ExprStmt)
					if !ok {
						continue
					}
					call, ok := statement.X.(*ast.CallExpr)
					if !ok {
						continue
					}
					identifier, named := call.Fun.(*ast.Ident)
					if named && identifier.Name == "target" {
						reachability[declaration.Name.Name] = true
					}
				}
			}
			return nil, nil
		},
	}
	registry, err := rules.NewRegistry(rule)
	if err != nil {
		t.Fatal(err)
	}
	selection, err := registry.Resolve(rules.PresetCorrectness, nil)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := analysis.RunControlFlow(context.Background(), loaded, registry, selection);
		err != nil {
		t.Fatal(err)
	}
	for _, name := range
		[]string{
			"osExit",
			"runtimeGoexit",
			"syscallExit",
			"logFatal",
			"logFatalf",
			"logFatalln",
			"logPanic",
			"logPanicf",
			"logPanicln",
			"loggerFatal",
			"loggerFatalf",
			"loggerFatalln",
			"loggerPanic",
			"loggerPanicf",
			"loggerPanicln",
			"testFailNow",
			"testFatal",
			"testFatalf",
			"testSkipNow",
			"testSkip",
			"testSkipf",
		} {
		if reachability[name] {
			t.Fatalf("target remains reachable after %s: %#v", name, reachability)
		}
	}
	for _, name := range
		[]string{"launched", "deferred", "dynamic", "lookalike", "logPrint", "testError"} {
		if !reachability[name] {
			t.Fatalf(
				"target is unexpectedly unreachable after %s: %#v",
				name,
				reachability,
			)
		}
	}
}

func TestRunControlFlowCancelsPackageNoReturnConstruction(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeTypesFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/project\n\ngo 1.26.0\n",
	)
	writeTypesFixture(
		t,
		filepath.Join(root, "project.go"),
		`package project

func caller() { stop1() }
func stop1() { stop2() }
func stop2() { stop3() }
func stop3() { panic("stop") }
`,
	)
	loaded, err := analysis.LoadPackages(
		context.Background(),
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			Requirement: rules.RequireControlFlow,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	ruleExecuted := false
	rule := controlFlowRule{
		metadata: controlFlowMetadata("cancel-package-no-return"),
		run: func(*rules.ControlFlowContext) ([]rules.Finding, error) {
			ruleExecuted = true
			return nil, nil
		},
	}
	registry, err := rules.NewRegistry(rule)
	if err != nil {
		t.Fatal(err)
	}
	selection, err := registry.Resolve(rules.PresetCorrectness, nil)
	if err != nil {
		t.Fatal(err)
	}
	ctx := newCancelAfterChecks(11)
	if _, err := analysis.RunControlFlow(ctx, loaded, registry, selection);
		!errors.Is(err, context.Canceled) {
		t.Fatalf("RunControlFlow error = %v, want context cancellation", err)
	}
	if ruleExecuted {
		t.Fatal("control-flow rule executed after no-return construction was canceled")
	}
}

func TestRunControlFlowPreservesCancellationAfterRuleExecution(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeTypesFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/project\n\ngo 1.26.0\n",
	)
	writeTypesFixture(t, filepath.Join(root, "project.go"), "package project\nfunc run() {}\n")
	loaded, err := analysis.LoadPackages(
		context.Background(),
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			Requirement: rules.RequireControlFlow,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithCancel(context.Background())
	rule := controlFlowRule{
		metadata: controlFlowMetadata("cancel-cfg"),
		run: func(ruleContext *rules.ControlFlowContext) ([]rules.Finding, error) {
			cancel()
			range_, err := ruleContext.Range(ruleContext.Function())
			if err != nil {
				return nil, err
			}
			return []rules.Finding{
				{MessageKey: "canceled", Message: "canceled", Range: range_},
			}, nil
		},
	}
	registry, err := rules.NewRegistry(rule)
	if err != nil {
		t.Fatal(err)
	}
	selection, err := registry.Resolve(rules.PresetCorrectness, nil)
	if err != nil {
		t.Fatal(err)
	}
	if diagnostics, err := analysis.RunControlFlow(ctx, loaded, registry, selection);
		!errors.Is(err, context.Canceled) || diagnostics != nil {
		t.Fatalf("RunControlFlow() = %#v, %v", diagnostics, err)
	}
}

func TestRunControlFlowRejectsInvalidExecutionContracts(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeTypesFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/project\n\ngo 1.26.0\n",
	)
	writeTypesFixture(t, filepath.Join(root, "project.go"), "package project\nfunc run() {}\n")
	loaded, err := analysis.LoadPackages(
		context.Background(),
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			Requirement: rules.RequireControlFlow,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	rule := controlFlowRule{
		metadata: controlFlowMetadata("valid-cfg"),
		run: func(*rules.ControlFlowContext) ([]rules.Finding, error) {
			return nil, nil
		},
	}
	registry, err := rules.NewRegistry(rule)
	if err != nil {
		t.Fatal(err)
	}
	selection, err := registry.Resolve(rules.PresetCorrectness, nil)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := analysis.RunControlFlow(nil, loaded, registry, selection); err == nil {
		t.Fatal("RunControlFlow() accepted nil context")
	}
	typesLoad := loaded
	typesLoad.Requirement = rules.RequireTypes
	if _, err := analysis.RunControlFlow(context.Background(), typesLoad, registry, selection);
		err == nil || !strings.Contains(err.Error(), "CFG-tier package load") {
		t.Fatalf("RunControlFlow() types-load error = %v", err)
	}
	invalidSeverity := append([]rules.Selection(nil), selection...)
	invalidSeverity[0].Severity = "fatal"
	if _, err := analysis.RunControlFlow(
		context.Background(),
		loaded,
		registry,
		invalidSeverity,
	);
		err == nil || !strings.Contains(err.Error(), "invalid severity") {
		t.Fatalf("RunControlFlow() invalid severity error = %v", err)
	}
	duplicate := append(append([]rules.Selection(nil), selection...), selection[0])
	if _, err := analysis.RunControlFlow(context.Background(), loaded, registry, duplicate);
		err == nil || !strings.Contains(err.Error(), "more than once") {
		t.Fatalf("RunControlFlow() duplicate selection error = %v", err)
	}

	missingMetadata := controlFlowMetadata("missing-cfg-execution")
	missingRegistry, err := rules.NewRegistry(metadataRuleAdapter{metadata: missingMetadata})
	if err != nil {
		t.Fatal(err)
	}
	missingSelection, _ := missingRegistry.Resolve(rules.PresetCorrectness, nil)
	if _, err := analysis.RunControlFlow(
		context.Background(),
		loaded,
		missingRegistry,
		missingSelection,
	);
		err == nil ||
			!strings.Contains(
				err.Error(),
				"does not implement control-flow execution",
			) {
		t.Fatalf("RunControlFlow() missing execution error = %v", err)
	}

	ambiguous := ambiguousControlFlowRule{
		controlFlowRule{
			metadata: controlFlowMetadata("ambiguous-cfg"),
			run: func(*rules.ControlFlowContext) ([]rules.Finding, error) {
				return nil, nil
			},
		},
	}
	ambiguousRegistry, err := rules.NewRegistry(ambiguous)
	if err != nil {
		t.Fatal(err)
	}
	ambiguousSelection, _ := ambiguousRegistry.Resolve(rules.PresetCorrectness, nil)
	if _, err := analysis.RunControlFlow(
		context.Background(),
		loaded,
		ambiguousRegistry,
		ambiguousSelection,
	);
		err == nil || !strings.Contains(err.Error(), "ambiguous control-flow execution") {
		t.Fatalf("RunControlFlow() ambiguous execution error = %v", err)
	}
}

func TestRunControlFlowAnalyzesEachPhysicalFunctionOnceAcrossTestVariants(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeTypesFixture(
		t,
		filepath.Join(root, "go.mod"),
		"module example.com/project\n\ngo 1.26.0\n",
	)
	projectPath := filepath.Join(root, "project.go")
	testPath := filepath.Join(root, "project_test.go")
	writeTypesFixture(t, projectPath, "package project\nfunc run() {}\n")
	writeTypesFixture(
		t,
		testPath,
		"package project\nimport \"testing\"\nfunc TestRun(t *testing.T) {}\n",
	)
	loaded, err := analysis.LoadPackages(
		context.Background(),
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			Requirement: rules.RequireControlFlow,
			Tests: true,
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	owners := make(map[string][]string)
	rule := controlFlowRule{
		metadata: controlFlowMetadata("variant-cfg"),
		run: func(ctx *rules.ControlFlowContext) ([]rules.Finding, error) {
			owners[ctx.File().Path()] = append(
				owners[ctx.File().Path()],
				ctx.PackageID(),
			)
			return nil, nil
		},
	}
	registry, err := rules.NewRegistry(rule)
	if err != nil {
		t.Fatal(err)
	}
	selection, err := registry.Resolve(rules.PresetCorrectness, nil)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := analysis.RunControlFlow(context.Background(), loaded, registry, selection);
		err != nil {
		t.Fatal(err)
	}
	if got := owners[projectPath]; !reflect.DeepEqual(got, []string{"example.com/project"}) {
		t.Fatalf("production owners = %#v", got)
	}
	if got := owners[testPath];
		len(got) != 1 || !strings.Contains(got[0], "[example.com/project.test]") {
		t.Fatalf("test owners = %#v", got)
	}
}

func BenchmarkRunControlFlowWithPackageNoReturnChain(b *testing.B) {
	root := b.TempDir()
	if err := os.WriteFile(
		filepath.Join(root, "go.mod"),
		[]byte("module example.com/project\n\ngo 1.26.0\n"),
		0o600,
	);
		err != nil {
		b.Fatal(err)
	}
	var input strings.Builder
	input.WriteString("package project\nfunc stop0() { panic(\"stop\") }\n")
	for index := 1; index < 100; index++ {
		fmt.Fprintf(&input, "func stop%d() { stop%d() }\n", index, index - 1)
	}
	input.WriteString("func caller() { stop99(); println(\"unreachable\") }\n")
	if err := os.WriteFile(filepath.Join(root, "project.go"), []byte(input.String()), 0o600);
		err != nil {
		b.Fatal(err)
	}
	loaded, err := analysis.LoadPackages(
		context.Background(),
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			Requirement: rules.RequireControlFlow,
		},
	)
	if err != nil {
		b.Fatal(err)
	}
	registry, err := rules.NewRegistry(
		controlFlowRule{
			metadata: controlFlowMetadata("package-no-return-benchmark"),
			run: func(*rules.ControlFlowContext) ([]rules.Finding, error) {
				return nil, nil
			},
		},
	)
	if err != nil {
		b.Fatal(err)
	}
	selection, err := registry.Resolve(rules.PresetCorrectness, nil)
	if err != nil {
		b.Fatal(err)
	}
	b.ReportAllocs()
	b.ResetTimer()
	for range b.N {
		if _, err := analysis.RunControlFlow(
			context.Background(),
			loaded,
			registry,
			selection,
		);
			err != nil {
			b.Fatal(err)
		}
	}
}

func BenchmarkRunControlFlowWithAuthoritativeNoReturnCalls(b *testing.B) {
	root := b.TempDir()
	if err := os.WriteFile(
		filepath.Join(root, "go.mod"),
		[]byte("module example.com/project\n\ngo 1.26.0\n"),
		0o600,
	);
		err != nil {
		b.Fatal(err)
	}
	var input strings.Builder
	input.WriteString("package project\nimport \"os\"\nfunc target() {}\n")
	for index := range 100 {
		fmt.Fprintf(&input, "func stop%d() { os.Exit(1); target() }\n", index)
	}
	if err := os.WriteFile(filepath.Join(root, "project.go"), []byte(input.String()), 0o600);
		err != nil {
		b.Fatal(err)
	}
	loaded, err := analysis.LoadPackages(
		context.Background(),
		analysis.PackageLoadOptions{
			Dir: root,
			Patterns: []string{"."},
			Requirement: rules.RequireControlFlow,
		},
	)
	if err != nil {
		b.Fatal(err)
	}
	registry, err := rules.NewRegistry(
		controlFlowRule{
			metadata: controlFlowMetadata("authoritative-no-return-benchmark"),
			run: func(*rules.ControlFlowContext) ([]rules.Finding, error) {
				return nil, nil
			},
		},
	)
	if err != nil {
		b.Fatal(err)
	}
	selection, err := registry.Resolve(rules.PresetCorrectness, nil)
	if err != nil {
		b.Fatal(err)
	}
	b.ReportAllocs()
	b.ResetTimer()
	for range b.N {
		if _, err := analysis.RunControlFlow(
			context.Background(),
			loaded,
			registry,
			selection,
		);
			err != nil {
			b.Fatal(err)
		}
	}
}

func functionKind(node ast.Node) string {
	switch node.(type) {
	case *ast.FuncDecl:
		return "declaration"
	case *ast.FuncLit:
		return "literal"
	default:
		return "unknown"
	}
}

type cancelAfterChecks struct {
	context.Context
	cancel context.CancelFunc
	checks int
	cancelAt int
}

func newCancelAfterChecks(cancelAt int) *cancelAfterChecks {
	ctx, cancel := context.WithCancel(context.Background())
	return &cancelAfterChecks{Context: ctx, cancel: cancel, cancelAt: cancelAt}
}

func (ctx *cancelAfterChecks) Err() error {
	ctx.checks++
	if ctx.checks >= ctx.cancelAt {
		ctx.cancel()
	}
	return ctx.Context.Err()
}

func controlFlowMetadata(id string) rules.Metadata {
	return rules.Metadata{
		ID: id,
		Summary: "reports control flow",
		Documentation: "Full control-flow rule documentation.",
		DefaultSeverity: rules.SeverityWarn,
		Presets: []rules.Preset{rules.PresetCorrectness},
		MinimumGoVersion: "1.22",
		Requirement: rules.RequireControlFlow,
		Categories: []rules.Category{rules.CategoryCorrectness},
		Examples: []rules.Example{{Incorrect: "bad()", Correct: "good()"}},
	}
}
